### ISSUE TITLE
No Horovod Tensorflow  image newer than 1.13 in ECR . 

### ISSUE THREAD

**Issue by whatdhack** [awslabs/amazon-sagemaker-examples#1004]
Was not able to find any 1.14 Horovod Tensorflow  image in the ECR repository - 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:1.13-horovod-gpu-py36-cu100-ubuntu16.04-v2.0 . 

Are they available elsewhere or will be made available ?

**Comment by knakad** [comment]
Thanks for reaching out!

The new Tensorflow images have Horovod support despite not having horovod in the tag: https://docs.aws.amazon.com/dlami/latest/devguide/deep-learning-containers-images.html

Hope that helps =)
