### ISSUE TITLE
Pass custom arguments when creating an endpoint

### ISSUE THREAD

**Issue by MTDzi** [awslabs/amazon-sagemaker-examples#1010]
I'd like to create an endpoint and be able to control, for example, the number of worker processes spawned by gunicorn. I'd like to be able to change this parameter along with instance type (the latter is already parametrizable in AWS CLI) to match SLAs. On the one hand, I want the cheapest instance, but on the other I'd like to have more than one worker process (to handle greater loads). Autoscaling incurs additional costs, so I'd rather have a single instance with as many workers as possible.

A concrete example: [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/253c6a28fb8c16cba475301ba4197537f44fc536/advanced_functionality/scikit_bring_your_own/container/decision_trees/nginx.conf#L1) is a config that contains the `worker_processes`. Currently, the only solution I see is to build several images that would differ only in the number of worker nodes.

But that's absurd, there has to be another way...
Right? ;)

**Comment by fm1ch4** [comment]
You can achieve this by changing having the `worker_processes` config take a value from an environment variable, and then specify that environment variable in the [Environment](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ContainerDefinition.html#sagemaker-Type-ContainerDefinition-Environment) field of the CreateModel API.

**Comment by MTDzi** [comment]
@fm1ch4 thanks!
