### ISSUE TITLE
Local training takes very long to abort on success

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#1068]
I've created a BYO docker image/training script. I'm testing it in local mode, and the elapsed time inside the `train.py` script is about 60 seconds until I get the message:

> 2020-02-29 13:53:49,328 sagemaker-containers INFO     Reporting training SUCCESS
> tmpxyobh8pn_algo-1-h70nf_1 exited with code 0
> Aborting on container exit...

However, it sometimes takes up to another 10 minutes before the cell that ran the `.fit` call unblocks so that I can test local deployment. Does anyone happen to know what's going on in the interim and how I can speed this process up?

**Comment by laurenyu** [comment]
@austinmw sorry for the delayed response here

After the docker-compose command finishes, [the model artifacts are collected and temporary files are cleaned up](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/image.py#L162-L168). Without further info, my best guess would be that the time is spent with [creating model.tar.gz and output.tar.gz](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/image.py#L225-L294) - do you have a lot of model and output files?

**Comment by austinmw** [comment]
Sorry should have closed this, yep that was the issue. Was using AutoGluon and the /opt/ml/model directory got huge. Thanks.
