### ISSUE TITLE
Increasing size of non-persistent storage in /tmp

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#1069]
I'm attempting to train an AutoGluon script in local mode on a SageMaker notebook instance. AutoGluon uses the tmp directory pretty heavily, and when trying to train a model, I'm running out of non-persistent storage, even if I clear it right before calling `estimator.fit`:

> OSError: [Errno 28] No space left on device: '/tmp/tmp1y49cd2e/artifacts'

It looks like tmp is capped at around 20GB regardless of my volume size. Is there any way to increase this?

**Comment by het90** [comment]
Hi @austinmw,
Apologies for the late response.

Are you still facing this issue? I was able to run this successfully on t2.medium instance.
<img width="1373" alt="Screen Shot 2020-04-20 at 12 40 56 PM" src="https://user-images.githubusercontent.com/7501485/79792731-404b3580-8304-11ea-8346-e5d0d7b4a828.png">

Thanks,
Hetal

**Comment by austinmw** [comment]
It works with a low `time_limits` setting, but if you set this to say, 30 mins, it will probably fill up /tmp in local mode.

**Comment by meglerv** [comment]
Suffering from the same problem.

**Comment by neelamgehlot** [comment]
Hi @austinmw ,

Thanks for using Amazon SageMaker.

SageMaker Notebook Instances has 2 storage volume attached to it. 

1. The volume mounted at `/home/ec2-user/SageMaker` is user volume, anything stored here will be persisted across Notebook Instance restarts, size of this volume is controlled by user. User can choose any size from 5 GB and 16384 GB in 1 GB increments (5 GB being default). 

2. The volume mounted at `/` is root volume. This is an instant store, anything stored here won't be persisted. Size for this volume is not controlled by User. This volume stores the AMI from which the Notebook Instance was launched and we guarantee that there is at least 10 GB of free space available for user.

You can read more about this here https://docs.aws.amazon.com/sagemaker/latest/dg/howitworks-create-ws.html under **Attaches an ML storage volume**.

We are always re-evaluating our backlog of features based on customer requests, so we appreciate the feedback on this feature. I have updated our backlog with this request.
    
Let us know if there is anything else we can help you with.

Thanks,
Neelam

**Comment by BaoshengHeTR** [comment]
> Hi @austinmw ,
> 
> Thanks for using Amazon SageMaker.
> 
> SageMaker Notebook Instances has 2 storage volume attached to it.
> 
> 1. The volume mounted at `/home/ec2-user/SageMaker` is user volume, anything stored here will be persisted across Notebook Instance restarts, size of this volume is controlled by user. User can choose any size from 5 GB and 16384 GB in 1 GB increments (5 GB being default).
> 2. The volume mounted at `/` is root volume. This is an instant store, anything stored here won't be persisted. Size for this volume is not controlled by User. This volume stores the AMI from which the Notebook Instance was launched and we guarantee that there is at least 10 GB of free space available for user.
> 
> You can read more about this here https://docs.aws.amazon.com/sagemaker/latest/dg/howitworks-create-ws.html under **Attaches an ML storage volume**.
> 
> We are always re-evaluating our backlog of features based on customer requests, so we appreciate the feedback on this feature. I have updated our backlog with this request.
> 
> Let us know if there is anything else we can help you with.
> 
> Thanks,
> Neelam

So how the problem is solved. I have the same issue.

**Comment by paldana-ISI** [comment]
I'm having the same issue, however it's not explicitly stating that it's the /tmp directory, although I think it is as I have 100GB of EBS assigned to my notebook instance. I'm getting "OSError: [Errno 28] No space left on device" right off the bat when trying to run my training in local mode. 

`!df
Filesystem     1K-blocks     Used Available Use% Mounted on
devtmpfs         8051492       76   8051416   1% /dev
tmpfs            8062192        0   8062192   0% /dev/shm
/dev/nvme0n1p1  97918600 97748076     70276 100% /
/dev/nvme1n1   103146424    93876  98779044   1% /home/ec2-user/SageMaker
`

Anyone knows how to expand the /tmp directory to potentially solve this issue?

**Comment by CliveMathe1273** [comment]
Hi @austinmw, @BaoshengHeTR, @paldana-ISI, @het90, did you manage to fix the issue? Would be greatly interested in the solution.

Regards,

CliveMonk

**Comment by BaoshengHeTR** [comment]
Here is a post I found useful. I used it to solve some of my problems here.
https://medium.com/dev-genius/ec2-no-space-left-on-device-error-539fac18ac24

**Comment by CliveMonk** [comment]
Thank you @BaoshengHeTR , it solved the issue

**Comment by narendranathchalla** [comment]
Same issue!
