### ISSUE TITLE
SageMaker Processing: how to parallelize when instance_count > 1 ?

### ISSUE THREAD

**Issue by peacej** [awslabs/amazon-sagemaker-examples#1075]
It's not clear what happens when we increase the instance_count to a value more than 1.
Is my understanding correct that the burden is on the developer to somehow orchestrate the parallelization ?  For example, if I have a python script (not using Spark) to load 100 large files from S3, filter them, and write back to S3, what is the simplest way to take advantage of multiple machines (e.g. instance_count = 5) ?

**Comment by andremoeller** [comment]
Hey @peacej ,

If you have 100 large files in S3 and use a `ProcessingInput` with `s3_data_distribution_type="ShardedByS3Key"` (instead of `FullyReplicated`), the objects in your S3 prefix will be sharded and distributed to your instances. 

For example, if you have 100 large files and want to filter records from them using SKLearn on 5 instances, the `s3_data_distribution_type="ShardedByS3Key"` will put 20 objects on each instance, and each instance can read the files from its own path to filter records.

Does this answer your question? Please feel free to reach back out if not. Thank you!

**Comment by peacej** [comment]
Yes, that is very helpful! (it was not clear from the documentation) Thanks a bunch!

**Comment by anotinelg** [comment]
hi @andremoeller,
  i run into that question, and i wonder how can you  `pass that information in to the job so each instance can know how to filter.` 
As far as i know, i can not see any parameters that i can tweak to send to  each instances launched? Should i use an environment variable like the one i used for distributed training (SM_CURRENT_HOST)?
Thanks

**Comment by andremoeller** [comment]
Hi @anotinelg ,

You can get information like the hostname or number of hosts from the file at ` /opt/ml/config/resourceconfig.json`:

```
{
  "current_host": "algo-1",
  "hosts": ["algo-1","algo-2","algo-3"]
}

```

From https://docs.aws.amazon.com/sagemaker/latest/dg/build-your-own-processing-container.html

Thanks!

**Comment by tomaszdudek7** [comment]
@andremoeller Will the file be shuffles/sharded automatically by SageMaker? Or is there some kind of naming convention required to be done by us?


Can I just upload `n` files with random names to S3, run `instance_count=4` processing containers with `s3_data_distribution_type="ShardedByS3Key"` and each of them will automatically get `n/4` files?

**Comment by andremoeller** [comment]
@tomaszdudek7 

> Will the file be shuffles/sharded automatically by SageMaker? Or is there some kind of naming convention required to be done by us?

Nope, no special naming convention needed to shard the files -- the S3 key is hashed to distribute objects over instances.

>Can I just upload n files with random names to S3, run instance_count=4 processing containers with s3_data_distribution_type="ShardedByS3Key" and each of them will automatically get n/4 files?

Yes.
