### ISSUE TITLE
Broken Links in readme

### ISSUE THREAD

**Issue by LiutongZhou** [awslabs/amazon-sagemaker-examples#1156]
The link in readme is 404

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_abalone_age_predictor_using_layers

TensorFlow Networks with Keras trains a basic neural network on the abalone dataset using TensorFlow and Keras

**Comment by laurenyu** [comment]
sorry for the delayed response here - the broken link was removed in #1226
