### ISSUE TITLE
Unzip doesn't work in SageMaker Studio using (Data Science) Python 3

### ISSUE THREAD

**Issue by ericangelokim** [awslabs/amazon-sagemaker-examples#1181]
https://github.com/awslabs/amazon-sagemaker-examples/blob/e463a7b158651a0a1888082a4673695a9acada73/introduction_to_applying_machine_learning/xgboost_direct_marketing/xgboost_direct_marketing_sagemaker.ipynb#L125

This line fails to unzip the data files in SageMaker Studio. Found when I was going through this blog: https://aws.amazon.com/blogs/aws/amazon-sagemaker-autopilot-fully-managed-automatic-machine-learning/

**Comment by ai2441** [comment]
I'm having the same issue in several of the SageMaker Studio examples.  My workaround is to unzip the file manually and then upload the individual files.  But would be great if the command worked.  :)

**Comment by neelamgehlot** [comment]
Hi @ericangelokim and @ai2441 ,

Thank you for using Amazon SageMaker. 

We are aware of the issue that unzip is missing in Data Science image and working on fixing it.

In the meantime, you can install unzip by running `!conda install -y -c conda-forge unzip` before using unzip.

Let us know if there is anything else we can help you with.

I am closing this issue for now, please feel free to re-open if suggested workaround doesn't work for you.

Thanks,
Neelam

**Comment by PVNPSPT** [comment]
Hello fellas,
I was also on the same boat. But found a work around...This worked for me. Hope this helps!
1. From within the SageMaker Studio interface, click the upload button and upload the ZIP file into SageMaker Studio:
![image](https://user-images.githubusercontent.com/52334354/96945930-045c7d00-14ad-11eb-9119-53ee80f8e8b0.png)

Next, go to File -> New -> Terminal to open a Terminal in the SageMaker Studio interface.
Once the Terminal is open, type **sudo yum install -y unzip**. This will install the unzip package, which we need in the following step.
![image](https://user-images.githubusercontent.com/52334354/96945964-15a58980-14ad-11eb-9ccc-4777939f7410.png)

Next, type **unzip sagemakerlabs.zip** in the Terminal. This will extract the lab files/directories, which will then appear within the left-hand file browser pane.

**Comment by jamcody** [comment]
Great solution, it works 👍

**Comment by sandu345** [comment]
if you are getting sudo: command not found error, try this.

open sagemaker terminal

1. conda install unzip

2. unzip "path_to_zip_folder"

**Comment by SatinderSidhu** [comment]
This is great guys. 
sudo yum install -y unzip worked for me like a charm
