### ISSUE TITLE
LifeCycle Configurations for R kernel: install R packages

### ISSUE THREAD

**Issue by MiguelSotelo2** [awslabs/amazon-sagemaker-examples#1197]
Good afternoon
I have a question regarding the problem posted [here](https://github.com/awslabs/amazon-sagemaker-examples/issues/320)

The standard R kernel when making a SageMaker notebook instance from Jupyter does not have some packages I would like installed. Manually installing them (`R: install.packages("rjson")`) takes a very long time. Some of the packages I want to install are 'rstan', 'survival', 'tidyverse'.

I would like to create a Lifecycle configurations script that automatically installs these packages when creating a notebook instance.

My current configurations file is:
`#!/bin/bash`
`sudo -u ec2-user -i <<'EOF'`
`conda install --yes --name R --channel r r-essentials=3.6.0`
`EOF`
After creating the notebook instance and starting a new notebook (R-kernel), I run 
`("rjson" %in% installed.packages())`
`("r-rjson" %in% installed.packages())`
To test whether _at the very least_ rjson is installed. However, it is not

**Any help in getting my configurations script would be appreciated!!**

Edit: I want a functionality like [this](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/persistent-conda-ebs)

**Comment by MiguelSotelo2** [comment]
following up on this. Appreciate the help!

**Comment by neelamgehlot** [comment]
Hi @MiguelSotelo2 ,

The R kernel on Notebook Instance already have `r-essentials` installed, which doesn't have `rjson` so you would need to install that package explicitly. I used following Lifecycle configuration and after Notebook Instance was created, launched a R kernel and got following output.

Lifecycle Configuration
```
#!/bin/bash

set -e

# OVERVIEW
# This script installs a single conda package in a single SageMaker conda environments.

sudo -u ec2-user -i <<'EOF'
conda install "r-rjson" --name "R" --yes
EOF
```
Output in R kernel for rjson installation status
```
sh-4.2$ source activate R
(R) sh-4.2$ R

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ("rjson" %in% installed.packages())
[1] TRUE
```

Similarly you can install other packages you mentioned 'rstan', 'survival', and 'tidyverse' using
```
conda install "r-rstan" --name "R" --yes
conda install "r-survival" --name "R" --yes
conda install "r-tidyverse" --name "R" --yes
```

For more SageMaker Notebook Instance Lifecycle configuration samples checkout this GitHub repository https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples .

Let us know if there is anything else we can help you with.

Please re-open this issue if suggested Lifecycle config doesn't work fo you.

Thanks,
Neelam

**Comment by MiguelSotelo2** [comment]
Thank you! this worked very well

I modified the `sudo` line to read
`nohup sudo -b -u ec2-user -i <<'EOF'`

As indicated [here](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/issues/7)
