### ISSUE TITLE
how to set maximum run time for HPO in sagemaker.tuner.HyperparameterTuner

### ISSUE THREAD

**Issue by vinayakkailas** [awslabs/amazon-sagemaker-examples#1230]
i am using sagemaker.tuner.HyperparameterTuner for tuning my estimator. I cannot find any documentation how to set maximum run time here

**Comment by AdnanKukuljac** [comment]
HyperparameterTuner receives estimator which has the param 'train_max_run' (Timeout in seconds for training (default: 24 * 60 * 60). After this amount of time Amazon SageMaker terminates the job regardless of its current status.) More about this here: https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.EstimatorBase
