### ISSUE TITLE
SageMaker Xgboost 1.0-1 not found with older SageMaker SDK

### ISSUE THREAD

**Issue by dhawalkp** [awslabs/amazon-sagemaker-examples#1285]
There are several Notebooks in "Introduction to Amazon SageMaker Algorithms" section demonstrating use of Amazon SageMaker XGboost Algorithm. The notebooks that uses xgboost 1.0-1 latest version are emitting a warning message "WARNING:root:There is a more up to date SageMaker XGBoost image. To use the newer image, please set 'repo_version'='0.90-1'." and due to that the training jobs are failing subsequently. This is due to older AWS SageMaker SDK on the SageMaker notebook conda environments. 
I will push the fix shortly for this problem.
Thanks
Dhawal

**Comment by iyerr3** [comment]
Fixed by #1287
