### ISSUE TITLE
PyTorch Extending our Containers:  `get-login` deprecated 

### ISSUE THREAD

**Issue by daniel-fudge** [awslabs/amazon-sagemaker-examples#1288]
The `build-and-push.sh` script won't as-is with new CLI.  The `aws ecr get-login` commands need to be replaced with the form below.

`aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account}.dkr.ecr.${region}.amazonaws.com`

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/pytorch_extending_our_containers/pytorch_extending_our_containers.ipynb

This is related to issue #858.

**Comment by daniel-fudge** [comment]
**_Currently:_**
$(aws ecr get-login --region ${region} --no-include-email)

**_Should be_**
aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $account.dkr.ecr.$region.amazonaws.com

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/pytorch_extending_our_containers/container/build_and_push.sh#L42

**Comment by daniel-fudge** [comment]
This line also needs to change but I can't figure out the new syntax.

`aws ecr get-login --registry-ids 520713654638 --region ${region} --no-include-email`

https://github.com/awslabs/amazon-sagemaker-examples/blob/c70e97962148bcdda77284cde044772c0b1c1f63/advanced_functionality/pytorch_extending_our_containers/container/build_and_push.sh#L45

**Comment by laurenyu** [comment]
Thanks for the feedback! I've opened https://github.com/awslabs/amazon-sagemaker-examples/pull/1292 to address this.
