### ISSUE TITLE
Error in 3d_point_cloud_input_data_processing example

### ISSUE THREAD

**Issue by dralipeker** [awslabs/amazon-sagemaker-examples#1305]
Hi,

I am trying the 3D example when  I try to call 

sagemaker_client.create_labeling_job(**ground_truth_request)

I am receiving this error

ParamValidationError: Parameter validation failed:
Missing required parameter in HumanTaskConfig.UiConfig: "UiTemplateS3Uri"
Unknown parameter in HumanTaskConfig.UiConfig: "HumanTaskUiArn", must be one of: UiTemplateS3Uri

Contents of ground_truth_request are as follows

arn:aws:sagemaker:us-east-1:394669845002:human-task-ui/PointCloudObjectTracking
{'InputConfig': {'DataSource': {'S3DataSource': {'ManifestS3Uri': 's3://adastec1/pt/manifest.json'}}, 'DataAttributes': {'ContentClassifiers': ['FreeOfPersonallyIdentifiableInformation', 'FreeOfAdultContent']}}, 'OutputConfig': {'S3OutputPath': 's3://adastec1/pt'}, 'HumanTaskConfig': {'AnnotationConsolidationConfig': {'AnnotationConsolidationLambdaArn': 'arn:aws:lambda:us-east-1:432418664414:function:ACS-3DPointCloudObjectTracking'}, 'UiConfig': {'HumanTaskUiArn': 'arn:aws:sagemaker:us-east-1:394669845002:human-task-ui/PointCloudObjectTracking'}, 'WorkteamArn': 'arn:aws:sagemaker:us-east-1:930402901153:workteam/private-crowd/adasteclabelling', 'PreHumanTaskLambdaArn': 'arn:aws:lambda:us-east-1:432418664414:function:PRE-3DPointCloudObjectTracking', 'MaxConcurrentTaskCount': 200, 'NumberOfHumanWorkersPerDataObject': 1, 'TaskAvailabilityLifetimeInSeconds': 18000, 'TaskDescription': 'add a task description here', 'TaskKeywords': ['lidar', 'pointcloud'], 'TaskTimeLimitInSeconds': 3600, 'TaskTitle': 'Add a Task Title Here - This is Displayed to Workers'}, 'LabelingJobName': 'add-job-name', 'RoleArn': 'arn:aws:iam::930402901153:role/service-role/AmazonSageMaker-ExecutionRole-20200525T170068', 'LabelAttributeName': 'add-job-name-ref', 'LabelCategoryConfigS3Uri': 's3://adastec1/pt/label-category.json'}

**Comment by TEChopra1000** [comment]
@dralipeker are you using an Amazon SageMaker Jupyter Notebook instance? If so, try stopping and then restarting your notebook instance, and then adding a cell before the first code-cell and running: 

```
!pip install boto3==1.14.8
!pip install -U botocore
```

**Comment by dralipeker** [comment]
Hi

Thanks it worked.

Best regards

Dr. Ali U. Peker
CEO | Adastec Corp.
M: +1 (415) 619 08 51
E: ali@adastec.com
A: 353 Sacramento St. Suite 1812,
     CA 94111, San Francisco
www.adastec.com<http://www.adastec.com>

**Comment by natsirtguy** [comment]
Looks like this was resolved, closing.
