### ISSUE TITLE
Import error: No module named 'sagemaker.tensorflow.serving'

### ISSUE THREAD

**Issue by zhuhuang** [awslabs/amazon-sagemaker-examples#1373]
When executing [tensorflow_serving_container.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_serving_container/tensorflow_serving_container.ipynb), ran into the following error:
```
ModuleNotFoundError: No module named 'sagemaker.tensorflow.serving'
```
Is this related to the 2.0 release of sagemaker python sdk?

**Comment by metrizable** [comment]
Hello @zhuhuang ,
    
Thank you for using Amazon SageMaker. We have pinned the example notebook at version < 2 for the time being.

If you would like to use v2 of the SageMaker Python SDK, when cloning the example notebook, you can 1) apply the [automated upgrade tool](https://sagemaker.readthedocs.io/en/stable/v2.html#automatically-upgrade-your-code), 2) remove the `< 2` pin, and 3) restart your kernel.

Let us know if there is anything else we can be an assistance of.
    
Best regards.

**Comment by zhuhuang** [comment]
Thank you for resolving this.
