### ISSUE TITLE
Processing Data With Your Own Container using spacy 

### ISSUE THREAD

**Issue by kapilsingh421** [awslabs/amazon-sagemaker-examples#1374]
Hey, I am following the blog of Aws to use spaCy lib in docker container but in the blog, I am not able to find spacy_script.py and dataset .please help

Moreover, Preprocessing code is also not working

Reference:-https://aws.amazon.com/blogs/aws/amazon-sagemaker-processing-fully-managed-data-processing-and-model-evaluation/

**Comment by andremoeller** [comment]
Hey @kapilsingh421 ,

Unfortunately, that script and dataset weren't published, and the preprocessing script is just a placeholder (you can replace the `apply_mad_data_science_skills` function with a function that selects just a few of the input rows).

The `spacy` script in that example could use command-line arguments to choose whether to tokenize, lemmatize, or tag parts of speech on the input dataset using [spaCy's API](https://spacy.io/api/tokenizer).

HTH! Closing this issue -- please feel free to reach out if you have more questions or comments.
