### ISSUE TITLE
EnsembleLearnerCensusIncome.ipynb issues

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/amazon-sagemaker-examples#1427]
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/ensemble_modeling/EnsembleLearnerCensusIncome.ipynb

* Needs to have default bucket set.

**Comment by TEChopra1000** [comment]
Created PR to fix this: https://app.reviewnb.com/awslabs/amazon-sagemaker-examples/pull/1493/files/
