### ISSUE TITLE
Tensorboard not displaying scalars

### ISSUE THREAD

**Issue by vassiasim** [awslabs/amazon-sagemaker-examples#153]
The notebook example with Tensorboard `amazon-sagemaker-examples/sagemaker-python-sdk/tensorflow_resnet_cifar10_with_tensorboard/tensorflow_resnet_cifar10_with_tensorboard.ipynb` is not displaying scalars or images. Only the graph and projector are displayed.

If one run is terminated and a new one is started (using the same `base_job_name` so it starts from the previously saved checkpoint) by running again:
`estimator.fit(inputs, run_tensorboard_locally=True)`
then the scalars and images of the previous run are displayed on `Tensorboard` but they are not updated as training continues.

**Comment by mvsusp** [comment]
This issue if duplicated here https://github.com/aws/sagemaker-python-sdk/issues/26
