### ISSUE TITLE
SageMaker Example Notebooks 

### ISSUE THREAD

**Issue by ansylenium** [awslabs/amazon-sagemaker-examples#1534]
Most of the times the sagemaker notebooks show as not available

**Comment by ngluna** [comment]
Hi @ansylenium Can you provide more detailed information as to how you are running into this issue?

For example:
1) Give a specific example of a notebook that was not available.
2) Are you using a notebook instance? Studio? 
3) Are you pulling from the most recent main branch?
4) What region are you using to run the notebooks?

**Comment by ansylenium** [comment]
Closing the issue as the issue is fixed.
