### ISSUE TITLE
Error after SageMaker Introduction

### ISSUE THREAD

**Issue by leonardomedinac** [awslabs/amazon-sagemaker-examples#1564]
Today I started using SageMaker in Aws. After finishing the quickstart in SageMaker Studio, an alert showed up.
The message was:
The account-level service limit 'Total domains' is 1 Domains, with current utilization of 1 Domains and a request delta of 1 Domains. Please contact AWS support to request an increase for this limit.
What caused it and what should I do to keep using SageMaker free tier?

**Comment by aaronmarkham** [comment]
It sounds like you're already setup with Studio. You only need to do this once, but you can add more users to the Studio app if you want. As long as you can launch Studio, you should be good to go. 
This could just be a transient warning message. If it keeps happening and you can't launch Studio, please reopen this issue.

**Comment by orcaman** [comment]
Happens to me as well (I don't have any studio and can't create one after a failed attempt)

**Comment by albertsu1708** [comment]
Error Message : The account-level service limit 'Total domains' is 1 Domains, with current utilization of 1 Domains and a request delta of 1 Domains. Please contact AWS support to request an increase for this limit. We couldn’t see the failed domain at AWS Management Console.

Solution : Use AWS CLI ! 

$ aws sagemaker list-domains
There was a domain with status FAILED

Delete the failed domain: 
$ aws sagemaker delete-domain --domain-id DOMAIN_ID

After that we create the domain again and it is working!
