### ISSUE TITLE
video-game-sales-xboost s3 download do not have prefix

### ISSUE THREAD

**Issue by ronaldwidha** [awslabs/amazon-sagemaker-examples#166]
`s3.Bucket(bucket).download_file(raw_data_filename, 'raw_data.csv')`
should probably be:
`s3.Bucket(bucket).download_file(prefix + '/' + raw_data_filename, 'raw_data.csv')`

**Comment by djarpin** [comment]
Thanks @ronaldwidha !  Good catch.  Since preparing for this step is manual, the notebook should work as is, but I agree it would be nicer to have the raw data stored in the same prefix as the rest of the example notebook's work.  We'll make the change in a PR soon.

**Comment by djarpin** [comment]
The fix is included in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/174).  Thanks again for your interest in SageMaker example notebooks!
