### ISSUE TITLE
how to install scala kernel to sagemaker's jupyter?

### ISSUE THREAD

**Issue by richardxin** [awslabs/amazon-sagemaker-examples#175]
is scala supported in jupyter notebook under sagemaker? if not, how to install scala kernel to sagemaker's jupyter?

**Comment by vlall** [comment]
This doesnt work anymore.

**Comment by mct0006** [comment]
I can confirm @vlall's point--specifically, the ./jupyter-scala command returns an error. @richardxin, any idea as to how to install it now?

**Comment by chriszheng10** [comment]
Hi @vlall and @mct0006,

Looks like the repo @djarpin mentioned before has been revamped this year and the previous instructions are out of date. 

In the updated repo's README, I discovered the installation instructions through their project website: http://almond-sh.github.io/almond/stable/docs/quick-start-install
I was able to install the Scala kernel following those instructions. Hopefully that helps!

**Comment by dinhnguyen92** [comment]
Unfortunately, the original instruction is obsolete, and the installation instructions link above is now dead. For those who struggle with this like I did, here's how I installed the Scala kernel in my SageMaker Jupyter Notebook instance:

1/ Open Jupyter Lab (I personally find it easier to work in Jupyter Lab)
2/ File > New > Terminal
3/ In the terminal, run ```git clone https://github.com/jupyter-scala/jupyter-scala.git```
4/ Once the repository has been cloned, ```cd jupyter-scala```
5/ ```cd scripts```
6/ Run ```ls```. Verify that you have ```coursier.sh``` and ```generate-launcher.sh``` in the current directory
7/ Run ```vi generate-launcher.sh``` to edit this script
8/ Press "insert" to start editing. Find the line ```coursier bootstrap \``` and change it to ```./coursier.sh bootstrap\```. Save and exit vim
9/ Run ```./generate-launcher.sh```
10/ Run ```ls```. Verify that the file ```almond``` is now present in the current directory
11/ Run ```./almond --install```

**Comment by arash2060** [comment]
I've been happy with https://pypi.org/project/spylon-kernel/ both on my laptop and on sagemaker
