### ISSUE TITLE
tensorflow_resnet_cifar10_with_tensorboard - predict example

### ISSUE THREAD

**Issue by krishnabigdata** [awslabs/amazon-sagemaker-examples#176]
Hi,

I don't see an predict sample for tensorflow_resnet_cifar10_with_tensorboard model. Can you please provide it.

**Comment by djarpin** [comment]
Hi @krishnabigdata .  Thanks for you interest in this notebook!  The TensorFlow cifar10 model is mainly to show how to use TensorBoard within Amazon SageMaker, not necessarily to fit the best model on cifar10.  We'll look to add a prediction component in the future, but in the meantime, the other TensorFlow examples show how to generate predictions from deployed endpoints.  Are you able to use these to get yourself started?  If not, is there a specific use case you're working on where these other TensorFlow examples aren't helpful?  Thanks.

**Comment by thinkbigdata** [comment]
Hi @djarpin  . Thanks for your reply, I have already used other tensorflow models and it works fine but the dataset (images) available for those models are very less, that's being the reason I am interested in using cifar10 including predictions. Can you please me help on this to get the prediction for cifar10.

**Comment by djarpin** [comment]
Hi @thinkbigdata .  Sorry this took a bit, but the fix has been implemented in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/214).  Thanks again for using SageMaker examples.
