### ISSUE TITLE
Missing chmod command in build_and_push.sh in scikit_bring_your_own project

### ISSUE THREAD

**Issue by emkessler** [awslabs/amazon-sagemaker-examples#179]
In the build_and_push.sh script in the scikit_bring_your_own project there are a few missing lines (which are present in the corresponding notebook section):

```
#make the program executable
chmod +x decision_trees/train 
#On a SageMaker Notebook Instance, the docker daemon may need to be restarted in order
#to detect your network configuration correctly.  (This is a known issue.)
if [ -d "/home/ec2-user/SageMaker" ]; then
  sudo service docker restart
fi
```

**Comment by djarpin** [comment]
Thanks @emkessler !  We've actually removed the need for the `docker restart`, so with the PR to remove that, I'll include the `chmod +x` fix.

**Comment by djarpin** [comment]
Fixed in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/186#discussion_r165773775).
