### ISSUE TITLE
Using caffe with sagemaker

### ISSUE THREAD

**Issue by dholdaway** [awslabs/amazon-sagemaker-examples#192]
Hello,

Not really a issue but more of an request.

I have a caffe model, I also have a caffe docker docker container 

I was wondering if there was any plans to support caffe?

Thanks

**Comment by djarpin** [comment]
Thanks for your interest in Amazon SageMaker, @dholdaway !

Currently you could use Caffe in SageMaker by bringing your own container, similar to our [scikit example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb). That said, we use customer feedback to help us prioritize which features we add over time.  With that in mind, are there any specific aspects of bringing your own Caffe model to SageMaker that have been difficult or where we could make it easier/faster?

**Comment by dholdaway** [comment]
so I have a container running caffe but I am unsure of the next step.

**Comment by djarpin** [comment]
Thanks, @dholdaway .  Is your container setup according to the specifications in the [SageMaker AWS docs](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms.html)?  At a high level that means, if you intend to use it for training, you have a `train` function that reads data in from /opt/ml/input/data/<channel> and outputs a trained model to /opt/ml/model.  And/or if you intend to use it for hosting, you have a `serve` function that reads in your model artifact, takes in an HTTP POST request body, parses it, and returns a prediction.

If that's been setup, then all you should need to do is publish that container to AWS ECS.  Then you can either create a training job or a hosted endpoint.  At a high level, creating a training job means creating an estimator that points to your container image in ECS, specifies instance type and count, and points to your data in S3.  For hosting, if you've trained the model as an estimator in SageMaker you can just `.deploy` it.  If you're hosting a model artifact that was trained elsewhere, you'll need to create a SageMaker model by registering that model artifact, create an endpoint config with instance information, and then create the endpoint from the endpoint config.  More details on that process can be found in these examples, or the [API reference](https://docs.aws.amazon.com/sagemaker/latest/dg/API_Reference.html) in the docs.

**Comment by wilderfield** [comment]
I vote for this! Would love to use Sagemaker to parallelize some retraining of Caffe models, but I don't want to do all the extra work of setting up my own container, and writing my own train/serve functions.
