### ISSUE TITLE
Is xgboost instance weight supported?

### ISSUE THREAD

**Issue by seanxwang** [awslabs/amazon-sagemaker-examples#194]
Weight is an xgboost option to assign to each row of training data, usually there is a separate csv or txt file for it. 
http://xgboost.readthedocs.io/en/latest/input_format.html#instance-weight-file

Is it currently supported, or on the roadmap?

**Comment by djarpin** [comment]
Thanks @seanxwang .  At he moment, SageMaker XGBoost does not support instance weight files.  AWS uses customer feedback to help us prioritize feature development, so we'll use this feedback to help us plan our roadmap.
