### ISSUE TITLE
How to get the training job name inside train program?

### ISSUE THREAD

**Issue by ThisIsRick** [awslabs/amazon-sagemaker-examples#199]
I followed link [1] to build a docker image for training on ECS with my own model. Is there a way to get the current training job name inside train program? I want to find out the S3 folder where the model artifact is uploaded to. Because I want to upload the training logs and some other training intermediate data to the same folder. Sounds like sagemaker.Session should have property/method to support it but I didn't find it yet.

Or is there a way to pass in job name as parameter to train script? Actually, the job name is available when create training job.

Thanks!

[1] https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb

**Comment by ThisIsRick** [comment]
Work around by put the training job name in hyperparameter.

**Comment by andremoeller** [comment]
Hey @ThisIsRick 

Thanks for using Amazon SageMaker!

Amazon SageMaker doesn't have a built-in way of getting the training job name from within the running container. Passing this in as a hyperparameter is a good approach.

Thanks again.
