### ISSUE TITLE
Seq2seq .describe_training_job

### ISSUE THREAD

**Issue by araitatsuya** [awslabs/amazon-sagemaker-examples#200]
message = sage.describe_training_job(TrainingJobName=job_name)['FailureReason']

The part should be...
message = sagemaker_client.describe_training_job(TrainingJobName=job_name)['FailureReason']
(i.e. sage -> sagemaker_client)

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/seq2seq_translation_en-de/SageMaker-Seq2Seq-Translation-English-German.ipynb

**Comment by djarpin** [comment]
Thanks for calling this out @araitatsuya !  Fixed in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/203) .  I'll close the issue for now, but let me know if other issues come up.
