### ISSUE TITLE
SageMaker returns a 500 error after Installing the R Kernel

### ISSUE THREAD

**Issue by NelisVerhoef** [awslabs/amazon-sagemaker-examples#204]
As soon as I've run the command to install the R kernel, and I refresh the Jupyter dashboard I get a 500 error. 

I've tried through the notebook example in advanced_functionality and also through the terminal. I also tried upgrading conda first but same result.

**Comment by djarpin** [comment]
Thanks @NelisVerhoef for calling this out.  I can replicate your error and I've reached out to the engineering team to investigate the root cause.  I'll provide updates here when I can.

**Comment by apdove87** [comment]
I believe this was from automatically updating notebook.
Consider an older version of r-essentials like r-essentials=1.6.0 worked for me.

**Comment by djarpin** [comment]
Thanks @apdove87 !  I've updated the example notebook in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/206) and the team is working on longer term solutions.

**Comment by NelisVerhoef** [comment]
Thanks @apdove87 and @djarpin, working for me as well.

**Comment by djarpin** [comment]
Longer term solution fix is in #370 .
