### ISSUE TITLE
How do I perform A/B testing?

### ISSUE THREAD

**Issue by Katniss394** [awslabs/amazon-sagemaker-examples#205]
I'm trying to figure out how to perform A/B testing using AWS sagemaker. I understand setting the train_instance_count will distribute the training across two instances. But how do I specify the set the percentage of inference calls each model will handle and perform A/B testing?

**Comment by djarpin** [comment]
Thanks, @Katniss394 .  We don't currently have a detailed example of A|B testing (although it's a good suggestion to have one).  At the moment, this isn't supported in the SageMaker Python SDK, so you'd need to use the AWS SDK.  More detail can be found [here](https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateEndpointConfig.html).  Essentially, you'd need to create an `EndpointConfig` with multiple `ProductionVariants`, where the `InitialVariantWeight` value controls the percentage of traffic that goes to each model.

**Comment by Katniss394** [comment]
Thank you. Thats very heplful.
