### ISSUE TITLE
How to kill pending notebook instance?

### ISSUE THREAD

**Issue by dtsukiyama** [awslabs/amazon-sagemaker-examples#207]
I am attempting to launch a ml.p2.xlarge notebook instance. However, 30 minutes and counting, it still is in pending, and there is no way to kill it. What do I do about this? And what is the billing status of a notebook instance that is in its pending state?

**Comment by dtsukiyama** [comment]
Update: Eventually status was updated to Failed due to:
```
Insufficient notebook instance capacity. Retry later or with a different instance type.
```
 I am no longer able to select actions on this instance. However I did use this instance a few days ago; and now cannot access the notebooks on this instance.

**Comment by djarpin** [comment]
Thanks, @dtsukiyama , and sorry you're experiencing issues.  You may try starting the Notebook Instance again to see what happens.  It sounds like we may have temporarily just not had an p2 instances available in your region.  If you continue to experience issues, I think the quickest way to get help would be to cut a ticket with AWS Support.  That way, they can get the information needed for our engineering team dive in appropriately.  Thanks!

**Comment by dtsukiyama** [comment]
Hi @djarpin , thanks for replying. So I cut a ticket to support at the same time I reported this issue. They stated:

> I understand that you have attempted to launch a ml.p2.xlarge notebook instance which is reflecting in a pending state. I have thoroughly reviewed your account and can confirm that currently you are approved for 1  ml.p2.xlarge. Upon checks on your account, I can see that there is a ml.p2.xlarge reflecting in a stopped state. This would be the reason that you are unable to launch the new instance as this would be seen as a second instance launch which is currently not available.
> 
> In order to launch your ml.p2.xlarge, you will need to terminate the current ml.p2.xlarge that is currently in a stopped state.

So, it isn't quite clear what this means. This instance had been used before, I was attempting to re-start it, and it failed. But it looks like they are saying that launching this would be seen as a new instance?
A failed notebook instance needs to be terminated, which I take to mean deleted. In this case it is not a huge deal since I did not have anything really important on the instance, I did have code and a couple of Jupyter notebooks. Also I am sorry if this is not quite the place to address this, I was just wondering if it was a bug. Thanks again.

**Comment by djarpin** [comment]
Thanks @dtsukiyama , I'll reach out to the Notebook engineering team on this.  However, you can also submit a service limit increase so that you can have more than 1 ml.p2 Notebook Instance running at a time.  Thanks.

**Comment by djarpin** [comment]
@dtsukiyama - Just confirmed with the engineering team that this was a temporary issue of not having an ml.p2.xlarge instance available.  This can happen intermittently.  If you run into this problem in the future, feel free to just retry starting the notebook instance in a few minutes to see if one has become available, or change to a different instance type (if another instance type will meet your needs anyway).  Thanks.
