### ISSUE TITLE
Jupyter Lab is not the default

### ISSUE THREAD

**Issue by mehemken** [awslabs/amazon-sagemaker-examples#213]
This is great! However, Jupyter Lab is much more versatile and I'd like my team to work on Jupyter Lab. When will Jupyter Lab be the default UI for SageMaker?

Bibliography:
- [Why? Notebooks are featureless.](https://towardsdatascience.com/jupyter-notebooks-are-breathtakingly-featureless-use-jupyter-lab-be858a67b59d)
- [JupyterLab](https://channel9.msdn.com/Events/PyData/Seattle2017/BRK11)
- [Docs](http://jupyterlab.readthedocs.io/en/latest/)

--Marco

**Comment by djarpin** [comment]
Thanks @mehemken .  We really like Jupyter Lab too and have been keeping a close eye on it.  However, I don't currently have a date that I can share with you for it being available in SageMaker Notebook Instances.

**Comment by mehemken** [comment]
Ok thanks for the feedback.

**Comment by ryanpeach** [comment]
I'd rather this stay open. This is the natural growth of the platform. Needless to say, as convenient as jupyter notebooks are, full project management is a bit difficult on Sagemaker without a real IDE.

**Comment by djarpin** [comment]
I'll re-open the issue for visibility.  We definitely use customer feedback to help us prioritize SageMaker's feature roadmap.  However, I should note that the roadmap is independent from this specific repository.  So, even though I initially closed the issue, JupyterLab definitely didn't fall off of our radar.

I should also note that you can still use SageMaker Training and Hosting from your preferred IDE.  We think the SageMaker notebook instances are a great way of interacting with the rest of the service, but we also want customers to be able to use SageMaker functionality from their laptops, EC2 instances, Cloud9, etc.

Thanks!

**Comment by mehemken** [comment]
Thanks @djarpin, is there a place in the documentation that shows how to set that up?

**Comment by djarpin** [comment]
@mehemken - Correct.  I was referring to controlling the rest of the platform with an arbitrary IDE.

**Comment by newbeb** [comment]
@ellisonbg Looks like they are now installing JupyterLab. Changing /tree to /lab works in sagemaker when I try it today.

**Comment by djarpin** [comment]
We've also begun including a link at the top of the Jupyter Dashboard on SageMaker notebook instances to encourage users to try JupyterLab.  Closing this issue for now.  Thanks!

![screen shot 2018-09-17 at 1 01 29 pm](https://user-images.githubusercontent.com/6025741/45647102-e4f6f880-ba79-11e8-9d28-e8effd6e5fd0.png)

**Comment by techChanakya** [comment]
I was trying to launch jupyterlab on EMR jupyterhub but with no luck. These are the steps I followed

1. Created a new EMR cluster (AMI = 5.22.0) with JupyterHub selected

2. SSH into container 
sudo docker exec -it jupyterhub /bin/bash

3. Install jupyterlab
conda install jupyterlab

4. Enable jupyterlab 
jupyter serverextension enable --py jupyterlab --user

5. Access jupyerlab using below url
https://<master node public dns>:9443/user/jovyan/lab

I'm seeing a blank page without able to launch jupyterlab.

**Comment by dennari** [comment]
Hi! Jupyter Lab 1.0 has just been released. Could you update SageMaker to include that? I'd love to be able to use Altair plots.
