### ISSUE TITLE
Connecting to Tensorboard without using notebook?

### ISSUE THREAD

**Issue by OktayGardener** [awslabs/amazon-sagemaker-examples#227]
Hello.

I am trying to use `sagemaker.tensorflow.estimator.TensorFlow` for training a new tensorflow model on Sagemaker. I would love to have access to TensorBoard no matter what, but since this will be a job run through `airflow` on a machine dedicated to data pipeline jobs, I will not have access to the local TensorBoard link. I am not using notebooks either, so I can't really use this option to 'connect to' as mentioned in the [Resnet CIFAR 10 Example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_resnet_cifar10_with_tensorboard/tensorflow_resnet_cifar10_with_tensorboard.ipynb)

```You can access TensorBoard locally at http://localhost:6006 or using your SageMaker notebook instance proxy/6006/(TensorBoard will not work if forget to put the slash, '/', in end of the url).```

Is there a way to connect via proxy for a `job` instead, or another way if not using notebooks?

I instanciate `sagemaker.tensorflow.estimator.TensorFlow` in the following way:
```
        return TensorFlow(
            entry_point=self.entry_point,
            source_dir=self.source_dir,
            role=self.config.role,
            output_path=self.config.output_path,
            code_location=self.config.code_location,
            train_instance_count=self.config.train_instance_count,
            train_instance_type=self.config.train_instance_type,
            training_steps=self.config.training_steps,
            evaluation_steps=self.config.evaluation_steps
        )
```

I'm calling `fit` like:

```
            self.estimator.fit(
                self.config.train_data_location,
                job_name=self.training_job_name,
                run_tensorboard_locally=True,
            )
```

**Comment by yangaws** [comment]
Hi,

Thanks for using sagemaker.

As you quoted from documentation, we only support local and sagemaker notebook access to TensorBoard. So for now we don't have features that enable what your described.

 Since our codes are open source on https://github.com/aws/sagemaker-python-sdk , my suggestion would be:

1, You could develop the needed feature and contribute to the community!
2, You could submit a feature request issue for this. But since I am not an expert in airflow, I recommend you to give more descriptions on that, especially if the feature can be used more widely(not just airflow). 

Thanks!

**Comment by djarpin** [comment]
Closing for now.  Feel free to re-open if you continue to experience problems.  Thanks.

**Comment by elgalu** [comment]
Hi @djarpin , regarding:

> we only support local and sagemaker notebook access to TensorBoard

How can we subscribe to feature requests to get notified?

Given you close the issues doesn't look like I can subscribe here and expect this to be updated when the feature becomes available.

Thanks in advance.

**Comment by djarpin** [comment]
Hi @elgalu - AWS announces features via [What's New](https://aws.amazon.com/new/).  We also announce them on the [SageMaker AWS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=285&start=0).  Thanks.

**Comment by rex-yue-wu** [comment]
You are my hero!!! I spent the whole afternoon to fix the tensorboard issue, and it turns I am just one slash away from the right solution!!!

`(TensorBoard will not work if forget to put the slash, '/', in end of the url).`

> Hello.
> 
> I am trying to use `sagemaker.tensorflow.estimator.TensorFlow` for training a new tensorflow model on Sagemaker. I would love to have access to TensorBoard no matter what, but since this will be a job run through `airflow` on a machine dedicated to data pipeline jobs, I will not have access to the local TensorBoard link. I am not using notebooks either, so I can't really use this option to 'connect to' as mentioned in the [Resnet CIFAR 10 Example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_resnet_cifar10_with_tensorboard/tensorflow_resnet_cifar10_with_tensorboard.ipynb)
> 
> `You can access TensorBoard locally at http://localhost:6006 or using your SageMaker notebook instance proxy/6006/(TensorBoard will not work if forget to put the slash, '/', in end of the url).`
> 
> Is there a way to connect via proxy for a `job` instead, or another way if not using notebooks?
> 
> I instanciate `sagemaker.tensorflow.estimator.TensorFlow` in the following way:
> 
> ```
>         return TensorFlow(
>             entry_point=self.entry_point,
>             source_dir=self.source_dir,
>             role=self.config.role,
>             output_path=self.config.output_path,
>             code_location=self.config.code_location,
>             train_instance_count=self.config.train_instance_count,
>             train_instance_type=self.config.train_instance_type,
>             training_steps=self.config.training_steps,
>             evaluation_steps=self.config.evaluation_steps
>         )
> ```
> I'm calling `fit` like:
> 
> ```
>             self.estimator.fit(
>                 self.config.train_data_location,
>                 job_name=self.training_job_name,
>                 run_tensorboard_locally=True,
>             )
> ```

**Comment by elgalu** [comment]
`from sagemaker.debugger import TensorBoardOutputConfig` can also be useful https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_debugger.html#capture-real-time-tensorboard-data-from-the-debugging-hook
