### ISSUE TITLE
Invoke the endpoint in Sagemaker AWS via predictor.predict ()

### ISSUE THREAD

**Issue by PFE-Passau** [awslabs/amazon-sagemaker-examples#229]
Hello SageMaker Community, 

I have a probem when I call predictor.predict(" txt format ") in Sagemaker notebook, I get this error according to the format of the parameter to test 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-114-5828681b8210> in <module>()
      8 
      9 
---> 10 print(predictor.predict("the password is 15jdgvd "))

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data)
     72         """
     73         if self.serializer is not None:
---> 74             data = self.serializer(data)
     75 
     76         request_args = {

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in __call__(self, data)
    247             return _json_serialize_from_buffer(data)
    248 
--> 249         raise ValueError("Unable to handle input format: {}".format(type(data)))
    250 
    251 

ValueError: Unable to handle input format: <class 'str'>

**Comment by djarpin** [comment]
Thanks @PFE-Passau .

I think you'll need to set predictor.serializer to a function that can convert your string to the request body format your model is expecting when serving.  That may just mean setting `predictor.serializer = None`.  Can you provide a bit more detail about the container you're using (i.e. are you bringing your own, using the pre-built TensorFlow or MXNet containers, or working with a built-in algorithm)?

**Comment by PFE-Passau** [comment]
Thanks a lot @djarpin 

I can share with you the code , in deed I work on Doc2vec model : 

from __future__ import print_function

import os
import json
import pickle
import StringIO
import sys
import signal
import traceback
import re
import json
import nltk
import os
from flask import jsonify
from json import dumps, loads, JSONEncoder, JSONDecoder
from operator import itemgetter
from nltk.corpus import stopwords
from nltk import word_tokenize
from operator import itemgetter
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.metrics.pairwise import cosine_similarity
import multiprocessing
import operator
import numpy as np
import pandas as pd
from nltk import sent_tokenize
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import gensim, logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

import flask

prefix = '/opt/ml/'
model_path = os.path.join(prefix, 'model')

# A singleton for holding the model. This simply loads the model and holds it.
# It has a predict function that does a prediction based on the model and the input data.

class ScoringService(object):
    model = None                # Where we keep the model when it's loaded
    control_dict = None
    @classmethod
    def get_model(cls):
        """Get the model object for this instance, loading it if it's not already loaded."""
        if cls.model == None:
            cls.model = gensim.models.doc2vec.Doc2Vec.load(os.path.join(model_path, 'Big_corpus.model'))
        return cls.model

    @classmethod
    def get_controls(cls):
        model = cls.get_model()
        controls = prefix + 'controls/controls en_US for NLP 2017-11-20.json'
        if cls.control_dict == None:
            with gensim.utils.smart_open(controls, encoding='UTF-8') as f:
                data = json.load(f)
                control_dict=[]
                input_libId=[]
                for i in data:
                    dict_io={}
                    dict_io['libId']=i['libId']
                    input_libId.append( dict_io['libId'])
                    dict_io['statementSrc']=i['contentLang']['en_US']['statementSrc']
                    dict_io['control_statement'] = model.infer_vector(dict_io['statementSrc'])
                    control_dict.append(dict_io)
        return control_dict
        
    @classmethod
    def predict(cls,input):
        """For the input, do the predictions and return them.
        Args:
            input (a pandas dataframe): The data on which to do the predictions. There will be
                one prediction per row in the dataframe"""
        control_dict = cls.get_controls()
        model= ScoringService.get_model() 
        final_result=[]
        matchings=[]
        for i in range(len(control_dict)):
            result=cosine_similarity([control_dict[i]['control_statement']],input)
            dict_io={}
            dict_io['similarity']=result[0][0]
            dict_io['libId']=control_dict[i]['libId']
	    matchings.append(dict_io)
            

        X={}        
	sortedlist = sorted(matchings, key=itemgetter('similarity','libId'),reverse=True)       
        X['matchings']=sortedlist
        final_result.append(X)           
  
    
            
        return final_result

# The flask app for serving predictions
app = flask.Flask(__name__)

@app.route('/ping', methods=['GET'])
def ping():
    """Determine if the container is working and healthy. In this sample container, we declare
    it healthy if we can load the model successfully."""
    health = ScoringService.get_model() is not None  # You can insert a health check here

    status = 200 if health else 404
    return flask.Response(response='\n', status=status, mimetype='application/json')

@app.route('/invocations', methods=['POST'])
def transformation():
    """Do an inference on a single batch of data. In this sample server, we take data as CSV, convert
    it to a pandas data frame for internal use and then convert the predictions back to CSV (which really
    just means one prediction per line, since there's a single column.
    """
    data = None

    # Convert from text to vector
    #ground_truth = 's3://{}/ground_truth/truths.json'.format(bucket)
    if flask.request.content_type == 'application/json':
        data = flask.request.data.decode('utf-8')
        def preprocess(raw_text):
            
            letters_only_text = re.sub("[^a-zA-Z.?!]", " ", raw_text)

            words = letters_only_text.lower().split()

            stopword_set = set(stopwords.words("english"))
            meaningful_words = [w for w in words if w not in stopword_set]

            cleaned_word_list = " ".join(meaningful_words)

            return cleaned_word_list

        s = json.loads(data)
        X=preprocess(s['text'])
        model= ScoringService.get_model()
        w=sent_tokenize(X)
        ivec_input=[]
        for j in w:
            tokens=word_tokenize(j)
            print(tokens)
            ivec=model.infer_vector(tokens,steps=50,alpha=0.025,min_alpha=0.0001)
            ivec_input.append(ivec)
       
    else:
        return flask.Response(response='This predictor only supports text data', status=415, mimetype='text/plain')

    #print(ivec_input)

    # Do the prediction
    predictions = ScoringService.predict(ivec_input)
    
    out = StringIO.StringIO()
    pd.DataFrame({'results':predictions}).to_json(out)
    result = out.getvalue()
    #print(predictions)

    return flask.Response(response=result, status=200, mimetype='application/json')

**Comment by djarpin** [comment]
Closing for now.  Feel free to re-open if you continue to experience problems.  Thanks.

**Comment by RupKanji** [comment]
Hi All-  I have deployed a Keras model in SageMaker. The model has been trained outside. While predicting, I am getting the following error:
ValueError: ('Unable to handle input format: ', <class 'int'>)

I can't solve it. The test data is a pandas dataframe values (same format as training data).
Please advise. Thanks.
