### ISSUE TITLE
Gluon recommender system example causes kernel to crash

### ISSUE THREAD

**Issue by dammo001** [awslabs/amazon-sagemaker-examples#242]
When attempting to run this example, the kernel dies somewhere around `net.collectParams()` with an output that looks like 
`mfblock0_ (
  Parameter mfblock0_embedding0_weight (shape=(140344, 64), dtype=<class 'numpy.float32'>)
  Parameter mfblock0_embedding1_weight (shape=(38385, 64), dtype=<class 'numpy.float32'>)
  Parameter mfblock0_dense0_weight (shape=(64, 0), dtype=<class 'numpy.float32'>)
  Parameter mfblock0_dense0_bias (shape=(64,), dtype=<class 'numpy.float32'>)
)`
. The error log says `.../tensor_gpu-inl.h:35: Check failed: e == cudaSuccess CUDA: unknown error`.  Any thoughts?

**Comment by djarpin** [comment]
Closing for now.  Feel free to re-open if you have additional questions.
