### ISSUE TITLE
Can't run TensorFlow graphs without Estimator

### ISSUE THREAD

**Issue by grahammorehead** [awslabs/amazon-sagemaker-examples#243]
I have a unique model paradigm that does not fit the structure of an Estimator, i.e. There is no model_fn() definition such that I can get the correct inputs/outputs.  In other words, even under the rubric of custom estimators, I cannot use a tf.Estimator, and instead of have had to code everything using the low-level TF API.

Is there a low-level version of the Python SageMaker API such that I can define my graph and run it, using feed_dict as needed, and all the other low-level TF API features?

**Comment by djarpin** [comment]
Thanks @grahammorehead .

Currently, SageMaker's pre-built TensorFlow container requires you to operate within the tf.Estimator paradigm.  This is a constraint we're looking to remove in the future, but don't have an existing workaround for.

You could still use SageMaker by bringing your own TensorFlow container.  We've actually open sourced our TensorFlow container [here](https://github.com/aws/sagemaker-tensorflow-containers), which could give you a starting point to work from.

Best of luck, and thanks for using SageMaker!
