### ISSUE TITLE
Getting error while invoking sagemaker endpoint

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#245]
I created training job in sagemaker with my own training and inference code using MXNet framework. I am able to train the model successfully and created endpoint as well. But while inferring the model, I am getting the following error:
 ‘ClientError: An error occurred (413) when calling the InvokeEndpoint operation: HTTP content length exceeded 5246976 bytes.’
What I understood from my research is the error is due to the size of the image. The image shape is (480, 512, 3). I trained the model with images of same shape (480, 512, 3).

When I resized the image to (240, 256), the error was gone. But producing another error 'shape inconsistent in convolution' as I the trained the model with images of size (480, 512).

I didn’t understand why I am getting this error while inferring.
Can't we use images of larger size to infer the model?
Any suggestions will be helpful

Thanks, Harathi

**Comment by djarpin** [comment]
Thanks @Harathi123 .  Payloads for SageMaker invoke endpoint requests are limited to about 5MB.  So if you're storing the pixel values as 8 byte floats, then 480 * 512 * 3 * 8 will be larger than this 5MB payload limit.

One option for doing inference on larger images might be to pass in an S3 path in your invoke endpoint request and then write your scoring logic to copy the image stored at that S3 path before doing inference.

There may be other ways to get around this, like compressing the image before sending and then decompressing within the container before inference, but these may be very use case specific.

**Comment by Harathi123** [comment]
Hi David, thank you for the rely.
This is my transform function:
def transform_fn(net, data, input_content_type, output_content_type):
    image = json.loads(data)
    nda = nd.array(image)
    prediction = net(nda)
    
    response_body = json.dumps(decode(prediction.asnumpy()))
    return response_body, output_content_type

This is how i am invoking the endpoint. I am passing numpy array of image. 
import cv2
img = cv2.imread('image.png')
img = img.reshape((1, 3, 480, 512))
img = img.astype('float32')/ 255
pred = predictor.predict(img)

Can I pass in an S3 path to invoke endpoint request like this?
pred = predictor.predict(' .....S3 path......')

Thanks,
Harathi

**Comment by andremoeller** [comment]
Hi @Harathi123 ,

You could possibly pass in a dictionary, like

`{ 's3_path' : 's3://my-bucket/my-key' }`

And then, in your transform function, retrieve the value of `s3_path`, download that file from S3, and predict on it.

But it seems to me like the image you're invoking with should be small enough since you're using `float32` dtype now. Could you tell us what the value of `img.nbytes` is before predicting with `img`, and if InvokeEndpoint still says your payload is too large, could you post the stacktrace?

Thanks!

**Comment by austinmw** [comment]
@djarpin Is this 5MB a hard limit that is uneffected by how I change nginx.conf `client_max_body_size`? Where can I find more information about this? Is there any way to increase the limit? It seems very low and is causing a lot of pain and frustration in integrating the endpoint into a production pipeline. My team is currently evaluating these endpoints and this issue is a big one for us.

**Comment by djarpin** [comment]
Hi @austinmw ,
Yes, the 5MB is a hard limit imposed by the SageMaker platform as documented [here](https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipeline-troubleshoot.html).

Typically exceeding the 5MB limit is cause by:
1. Sending too many small records in a single request to a live endpoint.  In which case, batch transform could be used instead.
1. Having very large single records (e.g. videos or high resolution images).  In which case, storing the file in S3, sending the S3 path, and having the container pick up the S3 object based on the path is a common workaround.

Thanks.

**Comment by austinmw** [comment]
Thanks for your reply. I have a lot of high-res images to process and pulling them from S3 seems very inefficient. Especially if they aren't originally coming from S3 and I have to both upload/download each.  How do people typically handle large images in SageMaker?

**Comment by austinmw** [comment]
@djarpin Hi, also after testing, I believe the max payload size is 5 MiB not 5 MB.

**Comment by dorg-jmiller** [comment]
If you're using an `nginx` server as part of your custom Docker image, you may need to change the value of `client_max_body_size` within your `ngix.conf` file.

I set `client_max_body_size` to 0, which allows for an unlimited body size.

**Comment by austinmw** [comment]
@dorg-jmiller I tried that, but was still running into the 5MiB limit. Have you been able to send a large payload (for ex. 10 MB) by modifying `client_max_body_size`? AWS phone support told me that 5 MiB   was a hard limit regardless, but maybe they were wrong.

**Comment by austinmw** [comment]
@dorg-jmiller I think the 5 MiB mentioned doesn't effect batch transform jobs, but only live http endpoints. I should probably experiment with ways to take advantage of BT jobs more often, but currently I need realtime inference from stood up endpoints.

**Comment by dorg-jmiller** [comment]
Gotcha, that makes sense. From the _little_ bit I know, batch transform won't suffice when you need real time inference.

**Comment by tf401** [comment]
@austinmw 

I've run in into the same problem as you, having numpy arrays of (3, 218, 525, 3) reaches the limit with my current serialization. 

I'm really keen to know how you serialized your data
Thanks!

**Comment by SaschaHeyer** [comment]
A more up-to-date answer:
Use AWS SageMaker Async Inference 
https://docs.aws.amazon.com/sagemaker/latest/dg/async-inference.html

> Amazon SageMaker Asynchronous Inference is a new capability in SageMaker that queues incoming requests and processes them asynchronously. This option is ideal for requests with large payload sizes (up to 1GB), long processing times (up to 15 minutes), and near real-time latency requirements. Asynchronous Inference enables you to save on costs by autoscaling the instance count to zero when there are no requests to process, so you only pay when your endpoint is processing requests.
