### ISSUE TITLE
seq2seq_translation_en-de - bucket for pretrained model artifacts does not exist

### ISSUE THREAD

**Issue by robperc** [awslabs/amazon-sagemaker-examples#250]
Under the pre-trained model section of the seq2seq_translation_en-de.ipynb the instructions say to curl the model artifacts from "https://s3-us-west-2.amazonaws.com/gsaur-seq2seq-data/seq2seq/eng-german/full-nb-translation-eng-german-p2-16x-2017-11-24-22-25-53/output/"

When attempting to curl these artifacts you get the following error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>gsaur-seq2seq-data</BucketName>
<RequestId>689B28A38C6874F0</RequestId>
<HostId>
DB0wm6RExts0znrV1uBktPdZa7ore4QA2IhlP6F7usDNFaZ7I8DbnYVgRPobziNc7cbQzZ2pGps=
</HostId>
</Error>

Was this bucket deleted accidentally?

**Comment by orchidmajumder** [comment]
PR for the fix - https://github.com/awslabs/amazon-sagemaker-examples/pull/251

**Comment by djarpin** [comment]
Approved and merged the PR.
