### ISSUE TITLE
What is the 

### ISSUE THREAD

**Issue by araitats** [awslabs/amazon-sagemaker-examples#252]
Re: amazon-sagemaker-examples/introduction_to_applying_machine_learning/gluon_recommender_system/

import pip
pip.main(['install', 'pandas'])

This method is not working with the newer version of pip. p2.xlarge instance does not seem to be supporting pandas. What is the recommended/alternative method to install Python packages when training and inference do not support the particular modules?

Thank you.

**Comment by djarpin** [comment]
Thanks for alerting us to this @araitats .

Changing from:
```
import pip
pip.main(['install', 'pandas'])
```
to:
```
os.system('pip install pandas')
```
worked for me.  I've added the fix to this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/253).

Thanks.
