### ISSUE TITLE
Current cifar10 example uses ml.p2.xlarge which requires request to AWS support

### ISSUE THREAD

**Issue by fernando-mc** [awslabs/amazon-sagemaker-examples#263]
I was working through the CIFAR10 example [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_cifar10/mxnet_cifar10_with_gluon.ipynb) after launching a notebook in AWS and noticed that I can't complete the tutorial without requesting a limit increase.

The current tutorial says:
"If you want to try the example without requesting an increase, just change the train_instance_count value to 1." 

I did this but I still hit an AWS limit error:
```
ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The account-level service limit 'ml.p2.xlarge for training job usage' is 0 Instances, with current utilization of 0 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.
```

Looks like the current default limit is 0 now? Is there an alternative instance type you suggest to complete this or is a support request now required?

**Comment by djarpin** [comment]
Hi @fernando-mc .  Yes, you should be able to run the notebook by changing the instance type to a CPU instance (e.g. ml.c4.xlarge).  This will lengthen training time though, so I'd suggest reducing the number of epochs, or requesting a service limit increase so that you're able to train with a GPU instance.  Thanks.

**Comment by fernando-mc** [comment]
@djarpin thanks, sounds good. 

I'd still suggest changing the notebook text to recommend one of these options this since it looks like the defaults have changed.

**Comment by DinukaDayarathna** [comment]
@djarpin I tried changing the instance type to `ml.c4.xlarge`. It's not supporting for image classification. Got below error.
> ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Instance type ml.c4.xlarge is not supported by algorithm image-classification; only GPU instances are supported.

**Comment by djarpin** [comment]
Hi @DinukaDayarathna - SageMaker's built-in image classification algorithm does require GPU instances.  The original post referred to a CIFAR-10 notebook written in MXNet/Gluon, which doesn't impose the same restriction.  There are some similarities between the two, but the SageMaker image classification algorithm has additional functionality baked in, which may result in better models, whereas the MXNet example requires custom coding, but may provide greater flexibility.  Thanks.
