### ISSUE TITLE
Forbidden S3 bucket in the example: amazon-sagemaker-examples/introduction_to_applying_machine_learning/gluon_recommender_system/gluon_recommender_system.ipynb

### ISSUE THREAD

**Issue by pilhokim** [awslabs/amazon-sagemaker-examples#267]
In the example code "amazon-sagemaker-examples/introduction_to_applying_machine_learning/gluon_recommender_system/gluon_recommender_system.ipynb", I couldn't copy the data file located at "s3://amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz". Please check the below code part in[ that Jupyter file](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/gluon_recommender_system/gluon_recommender_system.ipynb) and replace the below code with a valid S3 address:

`
aws s3 cp s3://amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz /tmp/recsys/
`

**Comment by pilhokim** [comment]
A temporary solution I found (See [this discussion](https://stackoverflow.com/questions/36144757/aws-cli-s3-a-client-error-403-occurred-when-calling-the-headobject-operation)) is running the` s3 cp` command with `--no-sign-request` parameter as shown below:
`aws s3 --no-sign-request cp s3://amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz /tmp/recsys/`

**Comment by pilhokim** [comment]
After fixing the S3 issue, I kept running the rest of the code but the kernel (Both `conda_mxnet_p27` and `conda_mxnet_p36`) dying at `Let's initialize network weights and set our optimization parameters` section. See the attached screenshot. Could you advise what could be a cause of this problem?

<img width="974" alt="screen shot 2018-06-04 at 9 54 28 pm" src="https://user-images.githubusercontent.com/440701/40918710-116887e2-6842-11e8-8a74-d1ced82b76f4.png">

**Comment by djarpin** [comment]
Hi @pilhokim .  Could you confirm that you're running in a GPU instance?  The MXNet context is currently set at mx.gpu() which will fail if you're running in a CPU instance.  Thanks.

**Comment by pilhokim** [comment]
You are right, @djarpin! Thanks a lot for your advice. I forgot the fact that this code runs on the local machine, not deploying training instances. I tested `ctx = mx.cpu()` which works fine with my ml.m4x.xlarge SageMaker instance. I also created a ml.p2.xlarge SageMaker instance and set `ctx = mx.gpu`. Both work fine. This example, however, looks taking a long time to train. Thank you again.
