### ISSUE TITLE
Displaying training accuracy and validation accuracy on same tensorboard plot

### ISSUE THREAD

**Issue by superprachi** [awslabs/amazon-sagemaker-examples#281]
Hi, it would be nice to display both the training and validation accuracy on the same plot in tensorboard. When using tensorboard directly, I have been successful doing something like this (use the same summary object, but different writers). 
```
acc_summary = tf.summary.scalar('accuracy', accuracy)
file_writer1 = tf.summary.FileWriter(logdir+'/train', tf.get_default_graph())
file_writer2 = tf.summary.FileWriter(logdir+'/validation', tf.get_default_graph())
acc_train = acc_summary.eval(feed_dict={X:X_train, y:y_train})
acc_val   = acc_summary.eval(feed_dict={X:X_val, y:y_val})
file_writer1.add_summary(acc_train, epoch)
file_writer2.add_summary(acc_val, epoch)
```
This works very nicely, but is it possible to accomplish something like this in SageMaker? Currently I have (following the tensorboard example): 
```
        accuracy = tf.metrics.accuracy(labels, y_pred_cls)

        if mode == tf.estimator.ModeKeys.TRAIN:
            tf.identity(accuracy[1], name='train_accuracy')
            tf.summary.scalar('train_accuracy', accuracy[1])
            
        elif mode == tf.estimator.ModeKeys.EVAL:
            tf.identity(accuracy[1], name='val_accuracy')
            tf.summary.scalar('val_accuracy', accuracy[1])
```
which outputs both on separate graphs, and as an additional problem they appear as different "runs" on the left which is not very clean. Could someone also explain why the identity line and index [1] is necessary?

**Comment by inakaaay** [comment]
how did you solve this?

**Comment by prachiAeromana** [comment]
@inakaaay I was not able to.
