### ISSUE TITLE
Test accuracy in SageMaker?

### ISSUE THREAD

**Issue by superprachi** [awslabs/amazon-sagemaker-examples#285]
Is it possible to evaluate a model in SageMaker before deploying it?
I'd really like to be able to see how the model is performing on the validation dataset during training. I don't see this in any of the sagemaker examples or documentation. I'm using a custom TensorFlow model, which seems to have functions "fit" which trains the model, "deploy" to create an endpoint, and "predict" to get new predictions, is there no way to evaluate the model directly, even if it's after training?

**Comment by djarpin** [comment]
Duplicate.  Closing in favor of this [issue](https://github.com/awslabs/amazon-sagemaker-examples/issues/287).
