### ISSUE TITLE
Sagemaker notebook failed - no option to start no option to retrieve ipynb files

### ISSUE THREAD

**Issue by Kaidanov** [awslabs/amazon-sagemaker-examples#288]
I added activation code to the script start notebook script.
The notebook failed.
I restored the srcipt, but can't run the notebook.
The important ting is to get the code of the ipynb files inside. 
How can I restore the notebook or get the inner files data?

![image](https://user-images.githubusercontent.com/164266/41466132-98e8728a-70a9-11e8-8dee-8daeb65698d2.png)

![image](https://user-images.githubusercontent.com/164266/41466145-a92ff7e4-70a9-11e8-9422-8263c9d92a07.png)

![image](https://user-images.githubusercontent.com/164266/41473268-6ffef3f4-70c1-11e8-89b7-d5405eb67b7c.png)

![image](https://user-images.githubusercontent.com/164266/41473302-8a4fb540-70c1-11e8-83fd-59c9828cdc35.png)

**Comment by Kaidanov** [comment]
@juliensimon any solution?
all my code is inside... 
I will make a backup after restoring that's for sure..

**Comment by djarpin** [comment]
Hi @Kaidanov .  I'm sorry to hear you've run into troubles.  An AWS Support request is probably the best path here.  They should be able to dig into your account and resources more thoroughly to diagnose and hopefully resolve your problem.

On a side note, have you checked your CloudWatch logs for the notebook instance (CloudWatch -> Logs -> filter to the /aws/sagemaker/NotebookInstances Log Group)?  That may give you more insight into the problem.
Thanks.

**Comment by Kaidanov** [comment]
@djarpin 
I added activation code to the script start notebook script.
The notebook failed.
I restored the srcipt

The log shows the stage when the script was with the lines of python activate.
The issue is that the state of the notebook not renewed and I don't how to make it to reload from failed state ..

That's the log :

![image](https://user-images.githubusercontent.com/164266/41500515-871be922-719b-11e8-8ce3-5d6114bcb229.png)

**Comment by jaipreetss** [comment]
Hi @Kaidanov 
You may restart the failed notebook instance using the [AWS CLI or SDK's StartNotebookInstance API](https://docs.aws.amazon.com/cli/latest/reference/sagemaker/start-notebook-instance.html).  Note that you will need to fix the issue in your script that caused it to fail the first time for it to succeed.


```bash
aws sagemaker start-notebook-instance \

  --region us-west-2 \

  --notebook-instance-name <name>
```

**Comment by Kaidanov** [comment]
@jaipreetss thank you so much ! no words.. thanks alot

**Comment by djarpin** [comment]
Closing this issue.  Feel free to re-open as necessary.

**Comment by gkrishna9790** [comment]
Thanks for the solution @jaipreetss .. this saved my day !!! 👍 

The solution suggested by @jaipreetss can be implemented via **boto3** as well:

```
import boto3  
client = boto3.client('sagemaker')
response = client.start_notebook_instance(
    NotebookInstanceName='<Notebook-Name-to-Restart>'
)
```
