### ISSUE TITLE
scikit_bring_your_own deployement 

### ISSUE THREAD

**Issue by walidsliti** [awslabs/amazon-sagemaker-examples#290]
i'am trying to test the deployement of bring your own scikit algo but i get this error 
HTTP/1.1 403 Forbidden
Date: Mon, 18 Jun 2018 11:42:36 GMT
Content-Type: application/json
Content-Length: 42
Connection: keep-alive
x-amzn-RequestId: 5685a6bd-e20e-4250-a125-828b8e5a5199
x-amzn-ErrorType: MissingAuthenticationTokenException:http://internal.amazon.com/coral/com.amazon.coral.service/

{
  "message": "Missing Authentication Token"
}

Any idea

**Comment by djarpin** [comment]
Hi @walidsliti .  Can you elaborate a bit more on what you're trying to do?  Are you trying to call your successfully deployed endpoint without going through the [InvokeEndpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/API_runtime_InvokeEndpoint.html) API?  If so, [this SageMaker forum post](https://forums.aws.amazon.com/thread.jspa?messageID=823468&#823468) may be helpful.

**Comment by walidsliti** [comment]
thank you it was helpful
