### ISSUE TITLE
An error occurred (ValidationError) when calling the InvokeEndpoint

### ISSUE THREAD

**Issue by alberto33** [awslabs/amazon-sagemaker-examples#293]
I continue to get the error:

An error occurred (ValidationError) when calling the InvokeEndpoint operation: Endpoint DEMO-imageclassification-epc--2018-06-23-02-03-51 of account 548009560556 not found.

My command is:

#aws sagemaker-runtime invoke-endpoint --endpoint-name DEMO-imageclassification-epc--2018-06-23-02-03-51 --body fileb://tub.jpg --content-type "application/x-image" output.json

However, in the same session I do see the endpoint:

#aws sagemaker list-endpoints --region us-east-1
{
    "Endpoints": [
        {
            "EndpointName": "DEMO-imageclassification-ep--2018-06-24-19-59-29",
            "EndpointArn": "arn:aws:sagemaker:us-east-1:548009560556:endpoint/demo-imageclassification-ep--2018-06-24-19-59-29",
            "CreationTime": 1529870369.986,
            "LastModifiedTime": 1529870804.812,
            "EndpointStatus": "InService"
        },
        {
            "EndpointName": "DEMO-imageclassification-ep--2018-06-23-02-03-51",
            "EndpointArn": "arn:aws:sagemaker:us-east-1:548009560556:endpoint/demo-imageclassification-ep--2018-06-23-02-03-51",
            "CreationTime": 1529719431.741,
            "LastModifiedTime": 1529719802.981,
            "EndpointStatus": "InService"
        }
    ]
}

I did find a few similar threads with folks having the same issue but it seems like the problem disappeared once the endpoint came InService.

**Comment by djarpin** [comment]
There appears to be a version of this question on the [AWS SageMaker Forums](https://forums.aws.amazon.com/thread.jspa?threadID=284713&tstart=0).  It looks like the invocation call may be pointing at the endpoint configuration name, rather than the endpoint itself.  Thanks.

**Comment by cna274** [comment]
We have daily automated pipelines to run inference on SageMaker that ran perfectly fine for over a month failing once a few days ago with this error.

**Comment by djarpin** [comment]
Closing as the original requester's issue appears to have been resolved via the [forum](https://forums.aws.amazon.com/thread.jspa?threadID=284713&tstart=0).

@cna274 - If you're still experiencing issues, can you provide more detail (endpoint name and invocation call) in a separate issue?  Thanks.

**Comment by alberto33** [comment]
Yes. Thank you!

------

Thanks,


Alberto

908-307-7148

**Comment by maciej-nowicki-cg24** [comment]
The link to the forum is no longer working :(
