### ISSUE TITLE
Running Object Detection notebook ImportError: cannot import name 'get_image_uri'

### ISSUE THREAD

**Issue by renatodmb** [awslabs/amazon-sagemaker-examples#325]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-18869bb3a045> in <module>()
----> 1 training_image = get_image_uri(sess.boto_region_name, 'object-detection', repo_version="latest")
      2 print (training_image)

NameError: name 'get_image_uri' is not defined

**Comment by renatodmb** [comment]
Problem solved, just run a new version of sagemaker instance.

**Comment by ElaineYao** [comment]
Hi @renatodmb , I met the same problem with you. Could you show how you solve this in detail? Thanks.
