### ISSUE TITLE
ImportError: cannot import name 'get_image_uri'

### ISSUE THREAD

**Issue by ssmostagh** [awslabs/amazon-sagemaker-examples#331]
When running the breast cancer prediction notebook in SageMaker there is an issue running this cell:
`# See 'Algorithms Provided by Amazon SageMaker: Common Parameters' in the SageMaker documentation for an explanation of these values.
from sagemaker.amazon.amazon_estimator import get_image_uri
container = get_image_uri(boto3.Session().region_name, 'linear-learner')`
This leads to the error "ImportError: cannot import name 'get_image_uri'" and you are unable to proceed with the remainder of the notebook.

**Comment by ssmostagh** [comment]
Confirming that restarting the notebook instance fixed the misalignment and allowed get_image_uri to succeed.

**Comment by kdlin** [comment]
I ran into the same issue with xgboost_direct_marketing_sagemaker example. The command is:

from sagemaker.amazon.amazon_estimator import get_image_uri

I got the following error message: ImportError: cannot import name 'get_image_uri'

I restarted the notebook instance but it did not help. I am using conda_python3. What should I try next? Thanks.

**Comment by djarpin** [comment]
Can you try opening up a notebook with the conda_python3 kernel, run `!pip install -U sagemaker --user`, restart the notebook kernel, and then try importing get_image_uri?

**Comment by kdlin** [comment]
I did these and it still failed to import get_image_uri. When I did the pip install, it has the following message:
!pip install -U sagemaker --user

Looking in indexes: https://artifact.intuit.com/artifactory/api/pypi/pypi-intuit/simple
Requirement already up-to-date: sagemaker in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (1.5.2)
Requirement not upgraded as not directly required: urllib3>=1.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (1.22)
Requirement not upgraded as not directly required: numpy>=1.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (1.14.5)
Requirement not upgraded as not directly required: boto3>=1.4.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (1.7.50)
Requirement not upgraded as not directly required: PyYAML>=3.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (3.12)
Requirement not upgraded as not directly required: protobuf>=3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (3.5.2)
Requirement not upgraded as not directly required: scipy>=0.19.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker) (1.1.0)
Requirement not upgraded as not directly required: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.4.8->sagemaker) (0.9.3)
Requirement not upgraded as not directly required: botocore<1.11.0,>=1.10.50 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.4.8->sagemaker) (1.10.50)
Requirement not upgraded as not directly required: s3transfer<0.2.0,>=0.1.10 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.4.8->sagemaker) (0.1.13)
Requirement not upgraded as not directly required: six>=1.9 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from protobuf>=3.1->sagemaker) (1.11.0)
Requirement not upgraded as not directly required: setuptools in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from protobuf>=3.1->sagemaker) (39.1.0)
Requirement not upgraded as not directly required: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<1.11.0,>=1.10.50->boto3>=1.4.8->sagemaker) (2.7.3)
Requirement not upgraded as not directly required: docutils>=0.10 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<1.11.0,>=1.10.50->boto3>=1.4.8->sagemaker) (0.14)
distributed 1.21.8 requires msgpack, which is not installed.

**Comment by djarpin** [comment]
Hi @kdlin - It looks like your pip install is pointing at your company's own PyPI repository which has an older version of the SageMaker Python SDK.  Typically the output of the pip install command above would produce an output that started like:

```
Collecting sagemaker
  Downloading https://files.pythonhosted.org/packages/25/13/fed79ea3dc93aba0a982818640f58e657389730cc5e9fc241644da821753/sagemaker-1.8.0.tar.gz (164kB)
...
```

I'm guessing you may be running an internet-free notebook instance, but if not, you could pip install from git with `!pip install -U git+git://github.com/aws/sagemaker-python-sdk --user`.  Otherwise, you can set the container location manually, e.g. `container = 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest` where the account and region are set according to [this documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html).  This would unblock you until the SageMaker Python SDK is updated in your internal PyPI repository.

**Comment by kdlin** [comment]
Hi @djarpin Thanks. I tried the container = 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest command and got the following error message:

container = 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest
                               
SyntaxError: invalid syntax

**Comment by djarpin** [comment]
Hi @kdlin 
The container path needs to be a string. e.g.

`container = '433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest'`

Sorry, I left off the quotes last time.

**Comment by kdlin** [comment]
Thanks @djarpin ! It works now. :-)
