### ISSUE TITLE
xgboost import not working

### ISSUE THREAD

**Issue by ritu-rg** [awslabs/amazon-sagemaker-examples#336]
While using Sagemaker for Machine Learning with Python 3, I am not allowed to use the default version of xgboost (even  though installation was successful) - I understand that there is a AWS version - XGBoost

Please let me know if there is a way to use the default Python version (installation was successful but import is not working) - same issue for lightgbm

**Comment by djarpin** [comment]
Hi @ritu-rg - Can you elaborate a bit more on your problem?  Are you using a SageMaker notebook instance and trying to run XGBoost locally?  If so, have you tried running:

`!conda install -y -c conda-forge xgboost` 

from the notebook kernel that you'd like to have XGBoost installed into?  Amazon SageMaker notebook instances use conda environments, so sometimes installation can appear successful, but not actually be in the desired environment and kernel.  More details [here](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-add-external.html).
Thanks.

**Comment by ritu-rg** [comment]
Thank You, @djarpin - this resolved the issue. Earlier I was trying to install the package from the terminal outside of the notebook
Thanks,
