### ISSUE TITLE
Standard method to retrieve external SQL data

### ISSUE THREAD

**Issue by DrEhrfurchtgebietend** [awslabs/amazon-sagemaker-examples#338]
I am new to this but it seems there is a functionality gap for model deployment. There is currently two options for [deployment hosting](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-hosting.html) and [Batch Transform](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-batch.html). Neither of these really fit well to the use case I have come across most often. This is the case where you have a trained model (.pkl or otherwise) and you want to predict on the most recently processed data. This might be that last day or so of records where you run at a scheduled time.

The deployment hosting is set up like a typical API service so it is always on and would predict on a single instance. The batch transform is more similar in structure but seems to require an S3 bucket. I would like to connect to my company server and query the data to be predicted on then write to s3 or even back to the same server. There are many reasons from a functionality or security standpoint this architecture would be preferable.

Typically the process only takes a few minutes when done in house on the actual server so it should have nearly minimal cost when done in sagemaker if the docker container was closed after each run. I would be surprised if the parts are not all in the AWS ecosystem to do this but it is not clear what the best way to do it would be. Could an example of how to do this be made?

**Comment by djarpin** [comment]
Hi @DrEhrfurchtgebietend - Thanks for your question.

You should be able to use a combination of SageMaker and other AWS tools (e.g. Lambda) to output data from your server to S3, then start a SageMaker batch transform job that ingests that data and writes outputs back to S3, and then passes that information to the next stage (which may be the original server).

Alternatively, you could use SageMaker just for training and bring model artifact to your local environment.  This has the advantage that you wouldn't have to worry about orchestrating the movements of data, but would require you to write your own prediction code.

Thanks.

**Comment by djarpin** [comment]
Closing.  Feel free to re-open as necessary.  Thanks.

**Comment by DrEhrfurchtgebietend** [comment]
I will not re-open this as it does not seem to be an issue which SageMaker will put in scope. There are a number of third party tools which have this as their main business model. I have built it myself using AWS tools combined with the addition of docker. SageMaker was not useful at all for this and I do not think it can be without this kind of functionality being explicitly incorporated.

**Comment by djarpin** [comment]
Thanks.  We always try to incorporate customer feedback into our product roadmaps, so we appreciate you providing it.
