### ISSUE TITLE
Bring Your Own Model (k-means) - minor issue

### ISSUE THREAD

**Issue by samsammurphy** [awslabs/amazon-sagemaker-examples#340]
This is a minor issue, when read the following cell..

> **Convert**
> 
> The model format that Amazon SageMaker's k-means container expects is an MXNet NDArray
> 

It might be helpful to the reader if the paragraph starts with a quick explanation, e.g. something like..

> **Convert**
> 
> *We created a container in advance and uploaded it to ECR using Sagemaker. You can upload a wide variety of containers. This one is setup to run the scikit learn k-means clustering algorithm and expects an MXNET NDArray  ..*

That is assuming I understood correctly (?)

Cheers

**Comment by djarpin** [comment]
Hi @samsammurphy - "This one is setup to run the scikit learn k-means clustering algorithm" is not actually the case.  The container this example points to is the Amazon SageMaker k-means container, which uses a [different methodology](https://docs.aws.amazon.com/sagemaker/latest/dg/algo-kmeans-tech-notes.html) than scikit k-means.  The purpose of this notebook was to show how you could piggyback on the inference portion of a container that already exists.  Hope that clears things up, but let me know if you have any questions.  Thanks.

**Comment by samsammurphy** [comment]
I see. Thanks!
