### ISSUE TITLE
model_fn called on every InvokeEndpoint for Pytorch?

### ISSUE THREAD

**Issue by jackkosaian** [awslabs/amazon-sagemaker-examples#341]
Apologies if this question is covered elsewhere.

I'm using SageMaker to deploy a Pytorch model. My understanding of the SageMaker `model_fn` is that it is called once to load the model by each instance that is part of the endpoint.

However, based on the logs that I'm seeing in Cloudwatch for my deployed endoint, it seems that `model_fn` is perhaps being called on every GET or POST request to the endpoint's /invocations or /ping.

Here's a very simple `model_fn` to reproduce this which just uses a pretrained model from `torchvision`:
```python
import torchvision.models as models

def model_fn(model_dir):
    model = models.resnet152(pretrained=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("log message")
    model.eval()
    return model.to(device)
```

As I only wish to test deployment, I simply create a `sagemaker.pytorch.PytorchModel` and invoke its `deploy()` method to create the endpoint.

When I issue InvokeEndpoint requests, I see the following log messages in Cloudwatch:
```
[23/Jul/2018:02:42:29 +0000] "POST /invocations HTTP/1.1" 200 5 "-" "AHC/2.0"
log message
[23/Jul/2018:02:42:30 +0000] "POST /invocations HTTP/1.1" 200 5 "-" "AHC/2.0"
log message
...
```

Similarly, the log message I've added shows up following GETs to /ping in Cloudwatch as well:
```
[23/Jul/2018:02:42:29 +0000] "GET /ping HTTP/1.1" 200 0 "-" "AHC/2.0"
log message
```

The presence of "log message" indicates to me that `model_fn` is being called for every GET and POST request. If this is the case, then it seems that SageMaker would then be loading my model to GPU for every InvokeEndpoint request, which will incur considerable latency.

So my questions are as follows:

1) Are my observations and conclusions above correct that `model_fn` is called for every InvokeEndpoint call?
2) If yes to (1), is there a way to create an endpoint for a deployed Pytorch model such that the model is loaded into GPU only once?

Sorry for the lengthy message. I appreciate any help!

**Comment by yangaws** [comment]
Hi @jackkosaian ,

Thank for your info. Now we don't have a way to just call model_fn once. And we should fix it.

So we will take this as a feature request.

Thanks

**Comment by jesterhazy** [comment]
fix pending in https://github.com/aws/sagemaker-pytorch-container/pull/42

**Comment by jesterhazy** [comment]
related fix for chainer pending in https://github.com/aws/sagemaker-chainer-container/pull/51

**Comment by jesterhazy** [comment]
@jackkosaian this fix is released now. you'll need to create new endpoints to pick up the updated. please reopen the issue if you continue to see problems.
