### ISSUE TITLE
Advice to link numpy / scipy libraries not applicable after numpy update

### ISSUE THREAD

**Issue by ededdneddyfan** [awslabs/amazon-sagemaker-examples#344]
https://github.com/awslabs/amazon-sagemaker-examples/blob/8b83a62c5002e03e5adecb026e270d414c63ca83/advanced_functionality/scikit_bring_your_own/container/Dockerfile#L24

See discussion here - https://github.com/numpy/numpy/issues/11614

**Comment by djarpin** [comment]
Thanks @ededdneddyfan and sorry for the issue.  This has been resolved with PR #345 .
