### ISSUE TITLE
xgboost_mnist classification example calls predict & not predict_prob

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/amazon-sagemaker-examples#350]
I'm trying to find a way to have the sagemaker hosted xgboost binary classification model call predict_prob as opposed to predict. Looking at the xgboost_minst example it looks like a classification model is trained but the hosted section is just getting the results from predict. Is there anyway to have a sagemaker hosted xgboost classification model call predict_prob and not predict? I even tried switching to text/x-libsvm MIME type but it still is only returning the results of calling predict on the model.

**Comment by djarpin** [comment]
Hi @Zambonilli - XGBoost MNIST is a multiclass classification problem, and yes, the prediction result is just the class.  But, for binary classification (which it sounds like your use cases is), Sagemaker XGBoost's output is the probability.  For example, this [notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/xgboost_customer_churn/xgboost_customer_churn.ipynb) uses the prediction probabilities.

**Comment by Zambonilli** [comment]
Thanks @djarpin . You're correct in that we are using a binary classifier. Oddly, our existing production python container with xgboost was using version .60 and returned different predictions when calling predict vs predict_proba. It looks like the update to Sagemaker and xgboost:latest container is using a newer version of xgboost and now return the same values from the two different methods. Thank you for your help here.
