### ISSUE TITLE
Running pytorch_lstm_word_language_model in 'local_gpu' mode fails when trying to save a checkpoint

### ISSUE THREAD

**Issue by BartBaddeley** [awslabs/amazon-sagemaker-examples#368]
I have successfully run the pytorch_cnn_cifar10 example in 'local_gpu' mode however when I attempt to run pytorch_lstm_word_language_model it fails at the point where it tries to save a checkpoint. If I run using 'ml.p2.xlarge' it works fine. 
I really want to get to training my own models, but I need to be comfortable running things locally before spinning up large jobs.
I've spent 2 days on this and am at a complete loss as to how to proceed.

estimator.fit({'training': inputs})
INFO:sagemaker:Creating training-job with name: sagemaker-pytorch-2018-08-16-13-25-24-915
...
algo-1-N95ZQ_1  | 
algo-1-N95ZQ_1  | Invoking script with the following command:
algo-1-N95ZQ_1  | 
algo-1-N95ZQ_1  | /usr/bin/python -m train --epochs 6 --tied True
algo-1-N95ZQ_1  | 
algo-1-N95ZQ_1  | 
algo-1-N95ZQ_1  | Namespace(batch_size=20, bptt=35, clip=0.25, data_dir='/opt/ml/input/data/training', dropout=0.2, emsize=200, epochs=6, log_interval=200, lr=20, model_dir='/opt/ml/model', nhid=200, nlayers=2, output_data_dir='/opt/ml/output/data', seed=1111, tied=True)
algo-1-N95ZQ_1  | Load data
algo-1-N95ZQ_1  | Batchify dataset
algo-1-N95ZQ_1  | Build the model
algo-1-N95ZQ_1  | Starting training.
algo-1-N95ZQ_1  | | epoch   1 |   200/ 2983 batches | lr 20.00 | ms/batch 132.20 | loss  8.34 | ppl  4170.69
algo-1-N95ZQ_1  | | epoch   1 |   400/ 2983 batches | lr 20.00 | ms/batch 130.82 | loss  7.33 | ppl  1526.82
algo-1-N95ZQ_1  | | epoch   1 |   600/ 2983 batches | lr 20.00 | ms/batch 131.50 | loss  6.84 | ppl   931.69
algo-1-N95ZQ_1  | | epoch   1 |   800/ 2983 batches | lr 20.00 | ms/batch 130.20 | loss  6.65 | ppl   773.86
algo-1-N95ZQ_1  | | epoch   1 |  1000/ 2983 batches | lr 20.00 | ms/batch 131.37 | loss  6.42 | ppl   612.90
algo-1-N95ZQ_1  | | epoch   1 |  1200/ 2983 batches | lr 20.00 | ms/batch 144.49 | loss  6.36 | ppl   577.66
algo-1-N95ZQ_1  | | epoch   1 |  1400/ 2983 batches | lr 20.00 | ms/batch 147.81 | loss  6.29 | ppl   538.71
algo-1-N95ZQ_1  | | epoch   1 |  1600/ 2983 batches | lr 20.00 | ms/batch 149.79 | loss  6.28 | ppl   535.09
algo-1-N95ZQ_1  | | epoch   1 |  1800/ 2983 batches | lr 20.00 | ms/batch 152.39 | loss  6.08 | ppl   436.85
algo-1-N95ZQ_1  | | epoch   1 |  2000/ 2983 batches | lr 20.00 | ms/batch 152.36 | loss  6.05 | ppl   422.20
algo-1-N95ZQ_1  | | epoch   1 |  2200/ 2983 batches | lr 20.00 | ms/batch 153.27 | loss  5.91 | ppl   368.56
algo-1-N95ZQ_1  | | epoch   1 |  2400/ 2983 batches | lr 20.00 | ms/batch 153.32 | loss  5.95 | ppl   384.13
algo-1-N95ZQ_1  | | epoch   1 |  2600/ 2983 batches | lr 20.00 | ms/batch 155.87 | loss  5.93 | ppl   375.15
algo-1-N95ZQ_1  | | epoch   1 |  2800/ 2983 batches | lr 20.00 | ms/batch 157.07 | loss  5.82 | ppl   336.95
algo-1-N95ZQ_1  | -----------------------------------------------------------------------------------------
algo-1-N95ZQ_1  | | end of epoch   1 | time: 449.71s | valid loss  6.03 | valid ppl   413.73
algo-1-N95ZQ_1  | -----------------------------------------------------------------------------------------
algo-1-N95ZQ_1  | Saving the best model: {'val_loss': 6.025203372840166, 'epoch': 1, 'val_ppl': 413.72577405337285, 'lr': 20}
algo-1-N95ZQ_1  | 2018-08-16 13:33:47,846 sagemaker-containers ERROR    ExecuteUserScriptError:
algo-1-N95ZQ_1  | Command "/usr/bin/python -m train --epochs 6 --tied True"
algo-1-N95ZQ_1  | Traceback (most recent call last):
algo-1-N95ZQ_1  |   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
algo-1-N95ZQ_1  |     "__main__", mod_spec)
algo-1-N95ZQ_1  |   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
algo-1-N95ZQ_1  |     exec(code, run_globals)
algo-1-N95ZQ_1  |   File "/usr/local/lib/python3.5/dist-packages/train.py", line 227, in <module>
algo-1-N95ZQ_1  |     with open(checkpoint_path, 'wb') as f:
algo-1-N95ZQ_1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/output/data/model.pth'

tmpt0u39mhk_algo-1-N95ZQ_1 exited with code 1
Aborting on container exit...

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/local/image.py in train(self, input_data_config, hyperparameters)
    110         try:
--> 111             _stream_output(process)
    112         except RuntimeError as e:

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/local/image.py in _stream_output(process)
    588     if exit_code != 0:
--> 589         raise RuntimeError("Process exited with code: %s" % exit_code)
    590 

RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-1505f00b5677> in <module>()
----> 1 estimator.fit({'training': inputs})

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    177         self._prepare_for_training(job_name=job_name)
    178 
--> 179         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    180         if wait:
    181             self.latest_training_job.wait(logs=logs)

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/estimator.py in start_new(cls, estimator, inputs)
    400                                           job_name=estimator._current_job_name, output_config=config['output_config'],
    401                                           resource_config=config['resource_config'], hyperparameters=hyperparameters,
--> 402                                           stop_condition=config['stop_condition'], tags=estimator.tags)
    403 
    404         return cls(estimator.sagemaker_session, estimator._current_job_name)

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/session.py in train(self, image, input_mode, input_config, role, job_name, output_config, resource_config, hyperparameters, stop_condition, tags)
    262         LOGGER.info('Creating training-job with name: {}'.format(job_name))
    263         LOGGER.debug('train request: {}'.format(json.dumps(train_request, indent=4)))
--> 264         self.sagemaker_client.create_training_job(**train_request)
    265 
    266     def tune(self, job_name, strategy, objective_type, objective_metric_name,

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/local/local_session.py in create_training_job(self, TrainingJobName, AlgorithmSpecification, RoleArn, InputDataConfig, OutputDataConfig, ResourceConfig, StoppingCondition, HyperParameters, Tags)
     73                                    data_distribution)
     74 
---> 75         self.s3_model_artifacts = self.train_container.train(InputDataConfig, HyperParameters)
     76 
     77     def describe_training_job(self, TrainingJobName):

/home/bart/anaconda3/envs/pytorch/lib/python3.5/site-packages/sagemaker/local/image.py in train(self, input_data_config, hyperparameters)
    114             # which contains the exit code and append the command line to it.
    115             msg = "Failed to run: %s, %s" % (compose_command, str(e))
--> 116             raise RuntimeError(msg)
    117 
    118         s3_artifacts = self.retrieve_artifacts(compose_data)

RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpt0u39mhk/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

**Comment by BartBaddeley** [comment]
I have solved this problem with a hack to the code by creating the missing directory.
pathlib.Path(args.output_data_dir).mkdir(parents=True, exist_ok=True)
However, I would still like to understand the reason it works for the hosted version and not in the local mode.

**Comment by djarpin** [comment]
Hi @BartBaddeley - Thank you.  Currently we don't create output_data_dir as part of SageMaker local mode (even though it is created in SageMaker training).  This is something we'll look at add in the near future.
