### ISSUE TITLE
scikit_bring_your_own:  Failed Reason: AlgorithmError: Exit Code: 1

### ISSUE THREAD

**Issue by cnasri** [awslabs/amazon-sagemaker-examples#372]
Hello, 

I try to reproduce the same example "scikit_bring_your_own"
Here my code : 

```
classifier = sage.estimator.Estimator(
    image, 
    role, 
    1, 
    'ml.c4.2xlarge', 
    output_path="s3://{}/output".format(sess.default_bucket()),
    sagemaker_session=sess)
```

But I get an error some few seconds
```
INFO:sagemaker:Creating training-job with name: inteldatastore-decision-2018-08-17-22-29-40-668

..............

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-103-17bf378fe011> in <module>()
----> 1 classifier.fit('s3://inteldatastore-sagemaker-cyrine/iris.csv')

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    179         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    180         if wait:
--> 181             self.latest_training_job.wait(logs=logs)
    182 
    183     @classmethod

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
    406     def wait(self, logs=True):
    407         if logs:
--> 408             self.sagemaker_session.logs_for_job(self.job_name, wait=True)
    409         else:
    410             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll)
    884 
    885         if wait:
--> 886             self._check_job_status(job_name, description, 'TrainingJobStatus')
    887             if dot:
    888                 print()

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
    611         if status != 'Completed' and status != 'Stopped':
    612             reason = desc.get('FailureReason', '(No reason provided)')
--> 613             raise ValueError('Error training {}: {} Reason: {}'.format(job, status, reason))
    614 
    615     def wait_for_endpoint(self, endpoint, poll=5):
ValueError: Error training inteldatastore-decision-2018-08-17-22-29-40-668: Failed Reason: AlgorithmError: Exit Code: 1
```

Can you help me to resolve this problem?
thanks

**Comment by djarpin** [comment]
Hi @cnasri - Can you check your CloudWatch jobs for this log to see if there's any more detail?  They should be under the "/aws/sagemaker/TrainingJobs" log group and then in the "inteldatastore-decision-2018-08-17-22-29-40-668" log stream.  Thanks.

**Comment by cnasri** [comment]
Hi @djarpin, there is "No Log Streams To Show" unfortunately.

**Comment by cnasri** [comment]
I see in the aws tutorial that : If a job fails and logs do not appear in CloudWatch, it's likely that an error occurred before the start of training. Reasons include specifying the wrong training image or S3 location. 
...

**Comment by djarpin** [comment]
Hi @cnasri - Yes, if the job fails before the algorithm code begins executing, you won't get any CloudWatch logs, and typically this is because of issues with the training image or S3 location.  However, in those cases, you'll typically get an error like:
```
Invalid training image. Please provide a valid Amazon Elastic Container Registry path of the Docker image that contains the training algorithm.
```
or
```
ClientError: Data download failed:S3 key: s3://path/to/data matched no files on s3
```

Have you tried running the scikit bring your own example without any modifications?  There could be several places where errors or slipping in (permissions, S3, the container itself, etc.).  An AWS Support Case may be more efficient here as their access allows them to troubleshoot your code and process more thoroughly.

**Comment by cnasri** [comment]
Ok thank you @djarpin . 
I just running the scikit bring your own example as it is . I didn't change nothing in the code..

**Comment by djarpin** [comment]
Hi @cnasri - The code you pasted above:
```Python
classifier = sage.estimator.Estimator(
    image, 
    role, 
    1, 
    'ml.c4.2xlarge', 
    output_path="s3://{}/output".format(sess.default_bucket()),
    sagemaker_session=sess)
```
doesn't seem to align with the [scikit bring your own notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb)
```Python
tree = sage.estimator.Estimator(image,
                       role, 1, 'ml.c4.2xlarge',
                       output_path="s3://{}/output".format(sess.default_bucket()),
                       sagemaker_session=sess)

tree.fit(data_location)
```

In addition, your data_location doesn't appear to use the default SageMaker bucket like the scikit BYO example does.  Did I misunderstand or are we perhaps looking at two different things?
Thanks.

**Comment by mvsusp** [comment]
Hi @cnasri ,

I am closing this ticket for now. Feel free to reopen it if you have additional question.

Thanks for using SageMaker!
