### ISSUE TITLE
transform_fn in sagemaker examples?

### ISSUE THREAD

**Issue by plynch-chewy** [awslabs/amazon-sagemaker-examples#375]
Based on the gluon recommender examples, we use a `transform_fn` for serving:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/gluon_recommender_system/gluon_recommender_system.ipynb
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/gluon_recommender_system/recommender.py#L208

However in the readme for sagemaker mxnet, we should use `input_fn`, `predict_fn`, `output_fn`:
https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/mxnet#model-serving

Is the `transform_fn` correct still?

**Comment by djarpin** [comment]
Hi @plynch-chewy - Both options work.  `transform_fn` is just kind of a shorthand if you want to process input data, generate predictions, and return final output within a single function.  In some cases it probably makes more sense to break your code into the three separate `input_fn`, `predict_fn`, and `output_fn`functions.  Thanks.

**Comment by plynch-chewy** [comment]
Ok cool, thanks for response.
