### ISSUE TITLE
Getting 'AssertionError: Could not compute output Tensor("dense/truediv:0", shape=(?, ?, 114), dtype=float32)' error with custom keras model

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#378]
Hi, 

I am trying to deploy custom Keras model on Sagemaker. I am following the https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/tensorflow_keras_cifar10 example to implement that.

I am getting 'AssertionError: Could not compute output Tensor("dense/truediv:0", shape=(?, ?, 114), dtype=float32)' error while training. The full trace back is as follows:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 69, in train
    estimator = self._build_estimator(run_config=run_config)
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 95, in _build_estimator
    model = self.customer_script.keras_model_fn(hyperparameters)
  File "/opt/ml/code/spell_tensorflow.py", line 265, in keras_model_fn
    model.compile(optimizer=tf.keras.optimizers.Adam(lr=lr), loss='categorical_crossentropy', metrics=['categorical_accuracy'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 682, in compile
    masks = self.compute_mask(self.inputs, mask=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 792, in compute_mask
    _, output_masks = self._run_internal_graph(inputs, masks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/network.py", line 939, in _run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("dense/truediv:0", shape=(?, ?, 114), dtype=float32)

I am implementing LSTM seq to seq model. For that, I have to inputs to the model 'encoder inputs', decoder inputs'.

Any suggestions will be helpful...

Thanks,
Harathi

**Comment by laurenyu** [comment]
hi @Harathi123, can you provide your code and data so that we can reproduce the error on our end?

**Comment by Harathi123** [comment]
Hi @laurenyu,

I am able to train the model on my machine. It seems the issue is with the versions i am using and versions on sagemaker. I am using tensorflow 1.9 version and keras 2.2.2. But when i tried to give framework_version='1.9' in tensorflow estimator, I am getting the following error.

ValueError: Error training sagemaker-tensorflow-2018-08-22-16-38-13-997: Failed Reason: ClientError: Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.

Thanks,
Harathi

**Comment by laurenyu** [comment]
hi @Harathi123, there's not a good way to share the code privately, but as long as you can provide something similar (e.g. with fake data, etc.) that would allow someone else to run it and get the same error, that would be sufficient.

Unfortunately, we do not currently support TensorFlow 1.9 in SageMaker. We do expect to in the future, as we started with 1.4 and have launched a new container for all versions of TensorFlow since.

Can you use TensorFlow 1.8 in the meantime? If so, then don't specify `framework_version` arg when constructing an estimator.

If you need TensorFlow 1.9, then you'll want to build your own image (or just wait). You can find an example explaining how to create your own TensorFlow container here: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_bring_your_own/tensorflow_bring_your_own.ipynb

**Comment by Harathi123** [comment]
Ok @laurenyu,

Please find the code below:
#!/usr/bin/env python3

from __future__ import print_function

import tensorflow as tf
#from tensorflow.python.keras._impl.keras.backend.tensorflow_backend import set_session
from tensorflow.python.keras.layers import Input, LSTM, Dense, Bidirectional, Concatenate, GRU
from tensorflow.python.keras.models import Model
from tensorflow.python.keras import optimizers
#from tensorflow.python.keras.callbacks import ModelCheckpoint, TensorBoard, LearningRateScheduler
from tensorflow.python.saved_model.signature_constants import PREDICT_INPUTS
import numpy as np
import os
import logging
import json

logging.basicConfig(level=logging.DEBUG)

batch_size = 64  # Batch size for training.
epochs = 2  
lr = 0.01

SAGEMAKER_DATA_PATH = '/opt/ml/input/data/training'

# allows script to be executed inside and outside the container
base_dir = SAGEMAKER_DATA_PATH if os.path.exists(SAGEMAKER_DATA_PATH) else 'data'
   
np_files = np.load(os.path.join(base_dir, 'vocab.npz'))

vocab_to_int = np_files['vocab_to_int'].item()
int_to_vocab = np_files['int_to_vocab'].item()
max_sent_len = np_files['max_sent_len'].item()
min_sent_len = np_files['min_sent_len'].item()

with open(os.path.join(base_dir, 'variables.json'), 'r') as fp:
    var_dict = json.load(fp)
    
input_characters = var_dict['input_characters']
num_encoder_tokens = var_dict['num_encoder_tokens']
num_decoder_tokens = var_dict['num_decoder_tokens']
max_encoder_seq_length = var_dict['max_encoder_seq_length']
max_decoder_seq_length = var_dict['max_decoder_seq_length']

latent_dim = 256 #Latent dimensionality of the encoding space.

def calculate_WER_sent(gt, pred):
    '''
    calculate_WER('calculating wer between two sentences', 'calculate wer between two sentences')
    '''
    gt_words = gt.lower().split(' ')
    pred_words = pred.lower().split(' ')
    d = np.zeros(((len(gt_words) + 1), (len(pred_words) + 1)), dtype=np.uint8)
    # d = d.reshape((len(gt_words)+1, len(pred_words)+1))

    # Initializing error matrix
    for i in range(len(gt_words) + 1):
        for j in range(len(pred_words) + 1):
            if i == 0:
                d[0][j] = j
            elif j == 0:
                d[i][0] = i

    # computation
    for i in range(1, len(gt_words) + 1):
        for j in range(1, len(pred_words) + 1):
            if gt_words[i - 1] == pred_words[j - 1]:
                d[i][j] = d[i - 1][j - 1]
            else:
                substitution = d[i - 1][j - 1] + 1
                insertion = d[i][j - 1] + 1
                deletion = d[i - 1][j] + 1
                d[i][j] = min(substitution, insertion, deletion)
    return d[len(gt_words)][len(pred_words)]

def calculate_WER(gt, pred):
    '''

    :param gt: list of sentences of the ground truth
    :param pred: list of sentences of the predictions
    both lists must have the same length
    :return: accumulated WER
    '''
#    assert len(gt) == len(pred)
    WER = 0
    nb_w = 0
    for i in range(len(gt)):
        #print(gt[i])
        #print(pred[i])
        WER += calculate_WER_sent(gt[i], pred[i])
        nb_w += len(gt[i])

    return WER / nb_w
    


def vectorize_data(input_texts, target_texts, max_encoder_seq_length, num_encoder_tokens, vocab_to_int):
    '''Prepares the input text and targets into the proper seq2seq numpy arrays'''
    encoder_input_data = np.zeros(
    (len(input_texts), max_encoder_seq_length, num_encoder_tokens),
    dtype='float32')
    decoder_input_data = np.zeros(
        (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
        dtype='float32')
    decoder_target_data = np.zeros(
        (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
        dtype='float32')

    for i, (input_text, target_text) in enumerate(zip(input_texts, target_texts)):
        for t, char in enumerate(input_text):
            # c0..cn
            encoder_input_data[i, t, vocab_to_int[char]] = 1.
        for t, char in enumerate(target_text):
            # c0'..cm'
            # decoder_target_data is ahead of decoder_input_data by one timestep
            decoder_input_data[i, t, vocab_to_int[char]] = 1.
            if t > 0:
                # decoder_target_data will be ahead by one timestep
                # and will not include the start character.
                decoder_target_data[i, t - 1, vocab_to_int[char]] = 1.
                
    return encoder_input_data, decoder_input_data, decoder_target_data

def decode_sequence(input_seq, encoder_model, decoder_model, num_decoder_tokens, int_to_vocab):
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)

    # Generate empty target sequence of length 1.
    target_seq = np.zeros((1, 1, num_decoder_tokens))
    # Populate the first character of target sequence with the start character.
    target_seq[0, 0, vocab_to_int['\t']] = 1.

    # Sampling loop for a batch of sequences
    # (to simplify, here we assume a batch of size 1).
    stop_condition = False
    decoded_sentence = ''
    while not stop_condition:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value)

        # Sample a token
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_char = int_to_vocab[sampled_token_index]
        decoded_sentence += sampled_char

        # Exit condition: either hit max length
        # or find stop character.
        if (sampled_char == '\n' or
           len(decoded_sentence) > max_decoder_seq_length):
            stop_condition = True

        # Update the target sequence (of length 1).
        target_seq = np.zeros((1, 1, num_decoder_tokens))
        target_seq[0, 0, sampled_token_index] = 1.

        # Update states
        states_value = [h, c]

    return decoded_sentence

def build_model(num_decoder_tokens, num_encoder_tokens, latent_dim):
    # Define an input sequence and process it.
    encoder_inputs = Input(shape=(None, num_encoder_tokens))
    encoder = Bidirectional(LSTM(latent_dim, return_state=True)) # Bi LSTM
    encoder_outputs, state_f_h, state_f_c, state_b_h, state_b_c = encoder(encoder_inputs)# Bi LSTM
    state_h = Concatenate()([state_f_h, state_b_h])# Bi LSTM
    state_c = Concatenate()([state_f_c, state_b_c])# Bi LSTM

    # We discard `encoder_outputs` and only keep the states.
    encoder_states = [state_h, state_c]# Bi GRU, LSTM, BHi LSTM
    
    decoder_inputs = Input(shape=(None, num_decoder_tokens))
    # We set up our decoder to return full output sequences,
    # and to return internal states as well. We don't use the
    # return states in the training model, but we will use them in inference.
    decoder_lstm = LSTM(latent_dim*2, return_sequences=True, return_state=True)# Bi LSTM
    
    decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)


    decoder_dense = Dense(num_decoder_tokens, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    # Define the model that will turn
    # `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
    print('encoder-decoder  model:')
    #print(model.summary()) 
    
    encoder_model = Model(encoder_inputs, encoder_states)

    decoder_state_input_h = Input(shape=(latent_dim*2,))# Bi LSTM
    decoder_state_input_c = Input(shape=(latent_dim*2,)) # Bi LSTM
    
    decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
    
    decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)

    decoder_states = [state_h, state_c]
    decoder_outputs = decoder_dense(decoder_outputs)
    decoder_model = Model([decoder_inputs] + decoder_states_inputs, [decoder_outputs] + decoder_states)
     
    return model, encoder_model, decoder_model
    
def exp_decay(epoch):
    initial_lrate = 0.1
    k = 0.1
    lrate = initial_lrate * np.exp(-k*epoch)
    return lrate
#lrate = LearningRateScheduler(exp_decay)

def step_decay(epoch):
    initial_lrate = 0.1
    drop = 0.5
    epochs_drop = 10.0
    lrate = initial_lrate * math.pow(drop, math.floor((1+epoch)/epochs_drop))
    return lrate
#lrate = LearningRateScheduler(step_decay)


def keras_model_fn(hyperparameters):
    
    logging.info('Training model.')
    
    #model, encoder_model, decoder_model = build_model(num_decoder_tokens, num_encoder_tokens, latent_dim)
        # Define an input sequence and process it.
    encoder_inputs = Input(shape=(None, num_encoder_tokens))
    encoder = Bidirectional(LSTM(latent_dim, return_state=True)) # Bi LSTM
    encoder_outputs, state_f_h, state_f_c, state_b_h, state_b_c = encoder(encoder_inputs)# Bi LSTM
    state_h = Concatenate()([state_f_h, state_b_h])# Bi LSTM
    state_c = Concatenate()([state_f_c, state_b_c])# Bi LSTM

    # We discard `encoder_outputs` and only keep the states.
    encoder_states = [state_h, state_c]# Bi GRU, LSTM, BHi LSTM
    
    decoder_inputs = Input(shape=(None, num_decoder_tokens))
    # We set up our decoder to return full output sequences,
    # and to return internal states as well. We don't use the
    # return states in the training model, but we will use them in inference.
    decoder_lstm = LSTM(latent_dim*2, return_sequences=True, return_state=True)# Bi LSTM
    
    decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)


    decoder_dense = Dense(num_decoder_tokens, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    # Define the model that will turn
    # `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
    logging.info('encoder-decoder  model:')
    print(model.summary()) 
    
    encoder_model = Model(encoder_inputs, encoder_states)

    decoder_state_input_h = Input(shape=(latent_dim*2,))# Bi LSTM
    decoder_state_input_c = Input(shape=(latent_dim*2,)) # Bi LSTM
    
    decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
    
    decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)

    decoder_states = [state_h, state_c]
    decoder_outputs = decoder_dense(decoder_outputs)
    decoder_model = Model([decoder_inputs] + decoder_states_inputs, [decoder_outputs] + decoder_states)
     
    logging.info('encoder_model')
    print(encoder_model.summary())
    logging.info('decoder_model')
    print(decoder_model.summary())
    
    model.compile(optimizer=tf.keras.optimizers.Adam(lr=lr), loss='categorical_crossentropy', metrics=['categorical_accuracy'])

    return model

def serving_input_fn(hyperpameters):
    tensor = tf.placeholder(tf.float32, shape=[None, max_sent_len])
    inputs = {PREDICT_INPUTS: tensor}
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)

def train_input_fn(training_dir, hyperpameters):

    logging.info("----------------------------------------train-------------------------------------------")
    
    return generate_input_fn(training_dir, 'test_inputs.txt', 'test_targets.txt')


def eval_input_fn(training_dir, hyperpameters):
    
    logging.info("----------------------------------------test-------------------------------------------")
    
    return generate_input_fn(training_dir, 'train_inputs.txt', 'train_targets.txt')

def _generate_input_fn(training_dir, input_filename, target_filename):
    logging.info('generator function')
    with open (os.path.join(training_dir, input_filename), 'r') as f:
        i_t = f.read()
            
    with open (os.path.join(training_dir, target_filename), 'r') as f:
        t_t = f.read()
    
    input_texts = i_t.split('\n')
    target_texts = i_t.split('\n')
    encoder_input_data, decoder_input_data, decoder_target_data = vectorize_data(input_texts=input_texts,
                                                                             target_texts=target_texts, 
                                                                             max_encoder_seq_length=max_encoder_seq_length, 
                                                                             num_encoder_tokens=num_encoder_tokens, 
                                                                             vocab_to_int=vocab_to_int)
    
    return {PREDICT_INPUTS: [encoder_input_data, decoder_input_data]}, decoder_target_data

**Comment by laurenyu** [comment]
hi @Harathi123, sorry for the delay. can you also include the code you're using to invoke SageMaker?

**Comment by Harathi123** [comment]
Hi @laurenyu , no problem!
This is the code I am using to invoke sagemaker:

   import os
   import sagemaker
   from sagemaker import get_execution_role
   sagemaker_session = sagemaker.Session()

   role = get_execution_role()
   
   inputs = sagemaker_session.upload_data(path='data', key_prefix='data/spell_tensor')

   from sagemaker.tensorflow import TensorFlow

   spell_estimator = TensorFlow(entry_point='spell_tensorflow_simple_concat.py',
                               role=role,
                               training_steps= 100,                                  
                               evaluation_steps= 100,
                               hyperparameters={'learning_rate': 0.01},
                               train_instance_count=1,
                               train_instance_type='ml.c4.xlarge')

   spell_estimator.fit(inputs)

**Comment by Harathi123** [comment]
Hi @laurenyu , any update on the issue...

Thanks,
Harathi

**Comment by laurenyu** [comment]
hi @Harathi123, sorry for the delayed response. I was able to reproduce your issue, but didn't yet find any noticeable causes.

I did notice that in your script, both `train_input_fn` and `eval_input_fn` call `generate_input_fn` instead of `_generate_input_fn` - was that intentional?

Also, are you able to run the Keras code locally without SageMaker?

**Comment by Harathi123** [comment]
Hi @laurenyu ,

Sorry, i forgot to update. I am able to train and deploy model with custom container created by following the sreps in the blog https://medium.com/@richardchen_81235/custom-keras-model-in-sagemaker-277a2831ac67

And I am able to run the code locally without sagemaker as well. 

And regarding _generate_input_fn, its not intentional. It is a typo error. But it is not the reason for the issue as the issue is raising in keras_model_fn while loading model itself.

Thanks,
Harathi
