### ISSUE TITLE
No file resourceconfig.json while deploying the model

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#380]
Hi,

I created custom container for sagemaker tensorflow estimator as I am getting issues with sagemaker tensorflow buitin estimator  [#378](https://github.com/awslabs/amazon-sagemaker-examples/issues/378).

With this, I am able to create training job. But while deploying the model, I am getting the following error:
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/trainer/start.py", line 35, in <module>
env = create_trainer_environment()
File "/trainer/environment.py", line 93, in create_trainer_environment
resource_config = load_resource_config()
File "/trainer/environment.py", line 51, in load_resource_config
return load_config(os.path.join(INPUT_CONFIG_PATH, RESOURCE_CONFIG_FILE))
File "/trainer/environment.py", line 42, in load_config
with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/config/resourceconfig.json'

I don't understand why I am getting this error with deploying and not while creating training job. Any suggestions on this will be helpful!

Thanks,
Harathi

**Comment by Harathi123** [comment]
I am creating custom container with the docker file 
[Dockerfile.txt](https://github.com/awslabs/amazon-sagemaker-examples/files/2312419/Dockerfile.txt)
and the entry point script is:

environment.py file is as in https://github.com/awslabs/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/keras_bring_your_own/trainer/environment.py

And input_text.txt file is 
[input_text.txt](https://github.com/awslabs/amazon-sagemaker-examples/files/2312446/input_text.txt)
`from __future__ import print_function

import tensorflow as tf
#from tensorflow.python.keras._impl.keras.backend.tensorflow_backend import set_session
from tensorflow.python.keras.layers import Input, LSTM, Dense, Bidirectional, Concatenate, GRU
from tensorflow.python.keras.models import Model
from tensorflow.python.keras import optimizers
#from tensorflow.python.keras.callbacks import ModelCheckpoint, TensorBoard, LearningRateScheduler
from tensorflow.python.saved_model.signature_constants import PREDICT_INPUTS
from sklearn.model_selection import train_test_split
import numpy as np
import os
import logging
import json

from trainer.environment import create_trainer_environment


logging.basicConfig(level=logging.DEBUG)

batch_size = 64  # Batch size for training.
epochs = 2  
lr = 0.01

SAGEMAKER_DATA_PATH = '/opt/ml/input/data/training'

#allows script to be executed inside and outside the container
base_dir = SAGEMAKER_DATA_PATH if os.path.exists(SAGEMAKER_DATA_PATH) else 'data'

MODEL_NAME = 'keras_model.h5'

#the trainer environment contains useful information about
env = create_trainer_environment()
print('creating SageMaker trainer environment:\n%s' % str(env))

#getting the hyperparameters
batch_size = env.hyperparameters.get('batch_size', object_type=int)
learning_rate = env.hyperparameters.get('learning_rate', default=.0001, object_type=float)
EPOCHS = env.hyperparameters.get('epochs', default=10, object_type=int)



def load_data_with_gt(file_name, num_samples, max_sent_len, min_sent_len):
    '''Load data from txt file, with each line has: <TXT><TAB><GT>. The  target to the decoder muxt have \t as the start trigger and \n as the stop trigger.'''
    cnt = 0  
    input_texts = []
    gt_texts = []
    target_texts = []
    #for row in open(file_name, encoding='utf8'):
    for row in open(file_name, encoding='utf8'):
        if cnt < num_samples :
            #print(row)
            sents = row.split("\t")
            input_text = sents[0]
            
            target_text = '\t' + sents[1] + '\n'
            if len(input_text) > min_sent_len and len(input_text) < max_sent_len and len(target_text) > min_sent_len and len(target_text) < max_sent_len:
                cnt += 1
                
                input_texts.append(input_text)
                target_texts.append(target_text)
                gt_texts.append(sents[1])
    return input_texts, target_texts, gt_texts


def build_vocab(all_texts):
    '''Build vocab dictionary to victorize chars into ints'''
    vocab_to_int = {}
    count = 0
    
    for sentence in all_texts:
        for char in sentence:
            if char not in vocab_to_int:
                vocab_to_int[char] = count
                count += 1
    # Add special tokens to vocab_to_int
    codes = ['\t','\n']
    for code in codes:
        if code not in vocab_to_int:
            vocab_to_int[code] = count
            count += 1
    '''''Build inverse translation from int to char'''
    int_to_vocab = {}
    for character, value in vocab_to_int.items():
        int_to_vocab[value] = character
        
    return vocab_to_int, int_to_vocab

def vectorize_data(input_texts, target_texts, max_encoder_seq_length, num_encoder_tokens, vocab_to_int):
    '''Prepares the input text and targets into the proper seq2seq numpy arrays'''
    encoder_input_data = np.zeros(
    (len(input_texts), max_encoder_seq_length, num_encoder_tokens),
    dtype='float32')
    decoder_input_data = np.zeros(
        (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
        dtype='float32')
    decoder_target_data = np.zeros(
        (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
        dtype='float32')

    for i, (input_text, target_text) in enumerate(zip(input_texts, target_texts)):
        for t, char in enumerate(input_text):
            # c0..cn
            encoder_input_data[i, t, vocab_to_int[char]] = 1.
        for t, char in enumerate(target_text):
            # c0'..cm'
            # decoder_target_data is ahead of decoder_input_data by one timestep
            decoder_input_data[i, t, vocab_to_int[char]] = 1.
            if t > 0:
                # decoder_target_data will be ahead by one timestep
                # and will not include the start character.
                decoder_target_data[i, t - 1, vocab_to_int[char]] = 1.
                
    return encoder_input_data, decoder_input_data, decoder_target_data


max_sent_len =  50#int(np.ceil(max_sent_len))
min_sent_len = 4#int(np.floor(min_sent_len))

num_samples = 1000000
correction_data = os.path.join(base_dir, 'input_text.txt')
input_texts_OCR, target_texts_OCR, gt_OCR = load_data_with_gt(correction_data, num_samples, max_sent_len, min_sent_len)

input_texts = input_texts_OCR
target_texts = target_texts_OCR

all_texts = target_texts + input_texts
vocab_to_int, int_to_vocab = build_vocab(all_texts)

input_characters = sorted(list(vocab_to_int))
target_characters = sorted(list(vocab_to_int))
num_encoder_tokens = len(input_characters)
num_decoder_tokens = len(target_characters)
max_encoder_seq_length = max([len(txt) for txt in input_texts])
max_decoder_seq_length = max([len(txt) for txt in target_texts])

#Split the data into training and testing sentences
input_texts, test_input_texts, target_texts, test_target_texts  = train_test_split(input_texts, target_texts, test_size = 0.15, random_state = 42)

latent_dim = 256 #Latent dimensionality of the encoding space.

encoder_input_data, decoder_input_data, decoder_target_data = vectorize_data(input_texts=input_texts,
                                                                             target_texts=target_texts, 
                                                                             max_encoder_seq_length=max_encoder_seq_length, 
                                                                             num_encoder_tokens=num_encoder_tokens, 
                                                                             vocab_to_int=vocab_to_int)

test_encoder_input_data, test_decoder_input_data, test_decoder_target_data = vectorize_data(input_texts=test_input_texts,
                                                                             target_texts=test_target_texts, 
                                                                             max_encoder_seq_length=max_encoder_seq_length, 
                                                                             num_encoder_tokens=num_encoder_tokens, 
                                                                             vocab_to_int=vocab_to_int)


def build_model(num_encoder_tokens, latent_dim):
    # Define an input sequence and process it.
    encoder_inputs = Input(shape=(None, num_encoder_tokens))
    encoder = Bidirectional(LSTM(latent_dim, return_state=True)) # Bi LSTM
    encoder_outputs, state_f_h, state_f_c, state_b_h, state_b_c = encoder(encoder_inputs)# Bi LSTM
    state_h = Concatenate()([state_f_h, state_b_h])# Bi LSTM
    state_c = Concatenate()([state_f_c, state_b_c])# Bi LSTM

    # We discard `encoder_outputs` and only keep the states.
    encoder_states = [state_h, state_c]# Bi GRU, LSTM, BHi LSTM
    
    decoder_inputs = Input(shape=(None, num_decoder_tokens))
    # We set up our decoder to return full output sequences,
    # and to return internal states as well. We don't use the
    # return states in the training model, but we will use them in inference.
    decoder_lstm = LSTM(latent_dim*2, return_sequences=True, return_state=True)# Bi LSTM
    
    decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)


    decoder_dense = Dense(num_decoder_tokens, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    # Define the model that will turn
    # `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
     
    return model

model = build_model(num_encoder_tokens, latent_dim)
    
print(model.summary())
 
model.compile(optimizer=tf.keras.optimizers.Adam(lr=lr), loss='categorical_crossentropy', metrics=['categorical_accuracy'])

model.fit([encoder_input_data, decoder_input_data], decoder_target_data,
          validation_data = ([test_encoder_input_data, test_decoder_input_data], test_decoder_target_data),
          batch_size=batch_size,
          epochs=EPOCHS,
          shuffle=True)

model_path = os.path.join(env.model_dir, MODEL_NAME)
model.save(model_path)
print('Saved trained model at %s ' % model_path)
`
I am able to create training job. But while deploying the model, none of the 'opt\ml\' paths (i.e., data, config) are getting loaded while deploying...

Thanks,
Harathi

**Comment by sermolin** [comment]
I am getting similar error No such file or directory: '/opt/ml/input/config/resourceconfig.json. 
Trying to upgrade to TF container 1.12. The directory 'opt/ml' does not seem to exist. I see this issue marked as "closed". What was the resolution?

**Comment by bee-keeper** [comment]
I'm also running into this problem running training locally in Docker.

`root@f50f0c81ec1b:/opt/ml/code# python cnn_train2.py 
Creating tmpvgagcp0u_algo-1-6p4ae_1 ... done
Attaching to tmpvgagcp0u_algo-1-6p4ae_1
algo-1-6p4ae_1  | jq: error: Could not open file /opt/ml/input/config/resourceconfig.json: No such file or directory
algo-1-6p4ae_1  | changehostname.c: In function ‘gethostname’:
algo-1-6p4ae_1  | changehostname.c:15:21: error: expected expression before ‘;’ token
algo-1-6p4ae_1  |    const char *val = ;
algo-1-6p4ae_1  |                      ^
algo-1-6p4ae_1  | gcc: error: changehostname.o: No such file or directory
algo-1-6p4ae_1  | ERROR: ld.so: object '/libchangehostname.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
algo-1-6p4ae_1  | ERROR: ld.so: object '/libchangehostname.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
algo-1-6p4ae_1  | Reporting training FAILURE
algo-1-6p4ae_1  | framework error: 
algo-1-6p4ae_1  | Traceback (most recent call last):
algo-1-6p4ae_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 47, in train
algo-1-6p4ae_1  |     env = sagemaker_containers.training_env()
algo-1-6p4ae_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/__init__.py", line 26, in training_env
algo-1-6p4ae_1  |     resource_config=_env.read_resource_config(),
algo-1-6p4ae_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_env.py", line 237, in read_resource_config
algo-1-6p4ae_1  |     return _read_json(resource_config_file_dir)
algo-1-6p4ae_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_env.py", line 193, in _read_json
algo-1-6p4ae_1  |     with open(path, 'r') as f:
algo-1-6p4ae_1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/config/resourceconfig.json'
algo-1-6p4ae_1  | 
algo-1-6p4ae_1  | [Errno 2] No such file or directory: '/opt/ml/input/config/resourceconfig.json'
tmpvgagcp0u_algo-1-6p4ae_1 exited with code 2`

Any ideas?

**Comment by Chen0523** [comment]
I m running to the same Isusse, anyone get any idea :) ?

**Comment by srstfca** [comment]
Hi all,
in my case it happens when loading remotely, but as https://stackoverflow.com/a/60081773 says, it happened to him when running locally. Hope this helps.

**Comment by myprogrammerpersonality** [comment]
It seems that this file has been renamed from "resourceConfig.json" to "resourceconfig.json".
