### ISSUE TITLE
Bug: DeepAR cat

### ISSUE THREAD

**Issue by pjebs** [awslabs/amazon-sagemaker-examples#389]
If you provide a `cat` field and you only have 1 time series and field is `"cat":[0]`.

When you run the predictor endpoint, if you provide a cat, it says the model was trained without a cat.

**Comment by djarpin** [comment]
Thanks for letting us know @pjebs .  I'll provide this feedback to the engineering team.

**Comment by aalexandrov** [comment]
Hi @pjebs,

could you share the hyperparameters for your training job?

**Comment by pjebs** [comment]
I think these were it:
```
Key	Value
cardinality	auto
context_length	14
dropout_rate	0.1
early_stopping_patience	100
embedding_dimension	10
epochs	300
learning_rate	0.001
likelihood	student-t
mini_batch_size	128
num_cells	40
num_dynamic_feat	auto
num_eval_samples	44
num_layers	3
prediction_length	14
test_quantiles	[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
time_freq	1D
```

**Comment by aalexandrov** [comment]
Thanks, we fixed a small bug with `cardinality=auto` used in combination with a dataset containing only a single categorical value.

**Comment by pjebs** [comment]
Should I close this? I haven't encountered it recently, but I don't think I made the same mistake either to test the fix.
