### ISSUE TITLE
 Export SageMakerModel to a XGBoost model 

### ISSUE THREAD

**Issue by msobroza** [awslabs/amazon-sagemaker-examples#396]
I would like to know if there is any way to export a trained SageMakerModel to xgboost python model format ? 
Basically the inverse functionality of https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/xgboost_bring_your_own_model/xgboost_bring_your_own_model.ipynb
Thanks you

**Comment by vijaykiran** [comment]
Do you mean SMXGboost to xgboost ? Can't you just use the pkl model and load it ?  (https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html)

**Comment by kevinsoucy** [comment]
@msobroza We had the same confusion. You have to download the file from S3, unzip it, which gives you a file called  'xgboost-model', and then you can use the code provided by AWS:

import pickle as pkl 
model = pkl.load(open('xgboost-model', 'rb'))

**Comment by msobroza** [comment]
Thanks you :+1:
