### ISSUE TITLE
Is it possible to mount an S3 bucket onto a Sagemaker notebook?

### ISSUE THREAD

**Issue by sophia-wright-blue** [awslabs/amazon-sagemaker-examples#401]
How do you mount an S3 bucket onto a Sagemaker notebook? Mounting would make it easier to download any large datasets (~1TB) directly on an S3 bucket, and then process it.

**Comment by djarpin** [comment]
Hi @sophia-wright-blue - You can't mount an S3 bucket to a SageMaker notebook instance the way you might mount an EFS file system.  But, maybe something like [S3Fs](https://s3fs.readthedocs.io/en/latest/) might work for your use case?

**Comment by sophia-wright-blue** [comment]
thanks for replying @djarpin , S3FS works when working with S3, but some portions of my code are canned and use python's os module, so I'll need to replace the os module parts with S3FS equivalent code. I think as a future feature, it'd be great if we could clone git repos and run them with minimal modifications. thanks again.
