### ISSUE TITLE
AWS Lambda Integration with Sagemaker Endpoint

### ISSUE THREAD

**Issue by murtuza07** [awslabs/amazon-sagemaker-examples#404]
Hi,

I'm using AWS Lambda for creating an API of Sagemaker, I have followed this tutorial: https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/ .  

I successfully completed the entire integration. 

Below is the function code written for the lambda service:
----------------------------------------------------------
import os
import io
import boto3
import json
import csv
import binascii
import struct

# grab environment variables
ENDPOINT_NAME = os.environ['ENDPOINT_NAME']
runtime= boto3.client('runtime.sagemaker')

def lambda_handler(event, context):
    #When we get the byte array we will directly use it as the payload
    #payload = bytearray(payload)
    data = json.loads(json.dumps(event))
    payload = data['data']
    print(payload)

   payload=bytes(payload.encode())

    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME, 
                                       ContentType='application/x-image', 
                                       Body=ba)
    result = response['Body'].read()
    # result will be in json format and convert it to ndarray
    result = json.loads(result)
    # the result will output the probabilities for all classes
    # find the class with maximum probability and print the class index
    index = np.argmax(result)
    #object_categories = ['ak47', 'american-flag', 'backpack', 'baseball-bat', 'baseball-glove', 'basketball-hoop', 'bat', 'bathtub', 'bear']
    object_categories = ['babycorn','bagara_rice','bailey_drinking_water','bhendi_masala','bhutan_chicken','bisleri_water','black_rice','boiled_egg','bombil_fry','butter_phulka']
    print(index)
    print(result)
    dict_result = dict(zip(object_categories, result))

    print("Result: label - " + object_categories[index] + ", probability - " + str(result[index]))
    return dict_result

----------------------------------------------------------

Input is a json file, example: 
{'data':'kasdhuadshaslxm12380u20913nzxlkai00jka01nx90kn19zn01j0znao10n'}

The value is a Base64 String. I'm converting this base64 string into bytearray (because the invoke endpoint accepts a bytearray) and passing the body to invoke endpoint.

But I'm getting this error:

"errorMessage": "An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message \"unable to evaluate payload provided: 'NoneType' object has no attribute 'shape'\". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/DEMO-imageclassification-ep--2018-09-12-07-30-43 in account 386239551216 for more information.",
  "errorType": "ModelError",
  "stackTrace": [
    [

------------------------------------------

2. **Converting Input file to Byte Array**(**Works Correctly**):

import json
import numpy as np

with open('example.jpg', 'rb') as f:
    payload = f.read()
    payload = bytearray(payload)
    print(payload[0:100])
 Output:  
bytearray(b'\xff\xd8\xff\xe1\x00\x7fExif\x00\x00MM\x00*\x00\x00\x00\x08\x00\x05\x01\x0f\x00\x02\x00\x00\x00\x08\x00\x00\x00J\x01\x12\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x00R\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x00Z\x011\x00\x02\x00\x00\x00\x15\x00\x00\x00b\x00\x00\x00\x00BeFunky\x00\x00\x00\x01,\x00\x00')

2. **Converting Base64 (Derived from an Image) to Byte Array**(**Produces Error**):
Input:
event = {"data":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgS}
data = json.loads(json.dumps(event))
payload = data['data']
payload = bytearray(payload.encode())

bytearray(b'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgS')

So, the output arrays of the both the methods are different, that is causing the error.

How can I convert Base64 Image String to Byte Array of this format bytearray(b'\xff\xd8\xff\xe1\x00\x7fExif\x00\x00MM\x00*\x00\) so that invoke_endpoint accepts and processes sucessfully.

Thanks!!

Murtuza

**Comment by ChoiByungWook** [comment]
Please reopen or create a new issue if you are stilling having problems.

Thanks!
