### ISSUE TITLE
[BUG] tensorflow_pipemode_example - not functional

### ISSUE THREAD

**Issue by eL0ck** [awslabs/amazon-sagemaker-examples#410]
```python
from sagemaker_tensorflow import PipeModeDataset
...
ImportError: No module named sagemaker_tensorflow
```

Greping through [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) shows the only reference to this dataset to be in `src/sagemaker/tensorflow/README.rst`.

**Comment by djarpin** [comment]
Hi @eL0ck - Can you confirm which version of the SageMaker TensorFlow container you're running this in when you get an error?  e.g. What value do you have set for the `framework_version` argument of your `sagemaker.tensorflow.TensorFlow` constructor?  I'm unable to replicate your error, and this library should be installed based on the [Dockerfile](https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.9.0/final/py2/Dockerfile.gpu#L137).  But, if you're running the import in the notebook instance itself, or in an older version of the SageMaker TensorFlow container, then I'd expect this error.

**Comment by tle-kablamo** [comment]
Hi @djarpin,  Thanks for your response.

I'm running the stock example with no modifications, made available in all sagemaker notebook instances. Code: [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_pipemode_example/tensorflow_pipemode_example.ipynb)

It starts under the conda environment `tensorflow_p27`.

---
It turns out that this conda environment does not have the package installed.

I install with `!pip install sagemaker-tensorflow`.  Which gets the package but appears to fail to load shared object `libPipeModeOp.so`.

```python
from sagemaker_tensorflow import PipeModeDataset
NotFoundErrorTraceback (most recent call last)
...
NotFoundError: //home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker_tensorflow/libPipeModeOp.so: undefined symbol: _ZN10tensorflow7tracing17GetTraceCollectorEv
```

---

Would you generally expect an example to come with the packages required in the environment?

**Comment by eL0ck** [comment]
Hi @djarpin,  Thanks for your response.

I'm running the stock example with no modifications, made available in all sagemaker notebook instances. Code: [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_pipemode_example/tensorflow_pipemode_example.ipynb)

It starts under the conda environment `tensorflow_p27`.

---
It turns out that this conda environment does not have the package installed.

I install with `!pip install sagemaker-tensorflow`.  Which gets the package but appears to fail to load shared object `libPipeModeOp.so`.

```python
from sagemaker_tensorflow import PipeModeDataset
NotFoundErrorTraceback (most recent call last)
...
NotFoundError: //home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker_tensorflow/libPipeModeOp.so: undefined symbol: _ZN10tensorflow7tracing17GetTraceCollectorEv
```

---

Would you generally expect an example to come with the packages required in the environment?

**Comment by djarpin** [comment]
Thanks for pointing this out @eL0ck and @tle-kablamo - I see how this could be confusing now.  The third code cell is actually a snippet taken out of `pipemode.py` and isn't intended to be run in the notebook itself.  [Pipe mode](https://docs.aws.amazon.com/sagemaker/latest/dg/API_AlgorithmSpecification.html#SageMaker-Type-AlgorithmSpecification-TrainingInputMode) is a construct that currently only exists within SageMaker's separate, managed training environment.  So, even if you would install sagemaker-tensorflow, there isn't a pipe streaming data into the notebook instance from S3 to read data from.  Skipping that cell and running the rest of the notebook (where `pipemode.py` is passed to the SageMaker TensorFlow container that's running in SageMaker training) should work fine.  We'll look to convert that third code cell to markdown to avoid future confusion.

Thanks.

**Comment by eL0ck** [comment]
happy to make that change myself @djarpin.  Will send a PR when I'm across it.

**Comment by eL0ck** [comment]
https://github.com/awslabs/amazon-sagemaker-examples/pull/419
