### ISSUE TITLE
pytorch_extending_our_containers: image does not exist 

### ISSUE THREAD

**Issue by smart-patrol** [awslabs/amazon-sagemaker-examples#414]
Getting the following error when trying to reproduce notebook as is:

`Get https://520713654638.dkr.ecr.us-west-2.amazonaws.com/v2/sagemaker-pytorch/manifests/0.4.0-cpu-py3: no basic auth credentials
Error response from daemon: No such image: pytorch-extending-our-containers-cifar10-example:latest
An image does not exist locally with the tag: 501239978509.dkr.ecr.us-east-1.amazonaws.com/pytorch-extending-our-containers-cifar10-example`

**Comment by djarpin** [comment]
Hi @smart-patrol - I'm having trouble replicating your error.  Can you confirm:
1. Are you running this in a fresh SageMaker notebook instance?
   1.  If so, is internet access enabled?
1. Which code cell this occurs in?
   1.  If it occurs in one of the later code cells, can you confirm if there is a more detailed error in the output of the second code cell (i.e. the one that starts with "%%sh")?

Thanks.

**Comment by smart-patrol** [comment]
@djarpin  Sorry, for the delayed response David. Here's the output:
`Login Succeeded
Login Succeeded
Sending build context to Docker daemon  13.31kB
Step 1/5 : FROM 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3
The push refers to repository [501239978509.dkr.ecr.us-east-1.amazonaws.com/pytorch-extending-our-containers-cifar10-example]
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Get https://520713654638.dkr.ecr.us-west-2.amazonaws.com/v2/sagemaker-pytorch/manifests/0.4.0-cpu-py3: no basic auth credentials
Error response from daemon: No such image: pytorch-extending-our-containers-cifar10-example:latest
An image does not exist locally with the tag: myaccount#.dkr.ecr.us-east-1.amazonaws.com/pytorch-extending-our-containers-cifar10-example`

The offending line of code is in the docker file here:
`# SageMaker PyTorch image
FROM 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3
`
Looks like an account # pasted in. 
Shall I create pull request and fix it?

**Comment by djarpin** [comment]
Hi @smart-patrol - Account 520713654638 is intentionally hard coded.  That's the AWS account that the pre-built deep learning framework containers are published to.  Based on the error "An image does not exist locally with the tag..." it looks like the problem may be occurring when you're attempting to build and tag your own extended version of that container locally.  Is there an additional error further up in the logs?  Perhaps when these lines are being executed?
```sh
docker build  -t ${algorithm_name} .
docker tag ${algorithm_name} ${fullname}
```
Thanks.

**Comment by smart-patrol** [comment]
@djarpin  David, I was able to get it to work running from **us-west2**.
The other 2 runs were from **us-east1**. 

`Successfully built 2edd1ca06849
Successfully tagged pytorch-extending-our-containers-cifar10-example:latest
The push refers to repository [501239978509.dkr.ecr.us-west-2.amazonaws.com/pytorch-extending-our-containers-cifar10-example]`

**Comment by smart-patrol** [comment]
Fine with closing this but wonder if the regional difference should be noted lest someone get the same error?

**Comment by djarpin** [comment]
Thanks for bringing this to our attention @smart-patrol , and sorry I didn't quite get your problem initially.  The hard-coded region in the Dockerfile is an issue and something we should look to fix.

**Comment by alexeygrigorev** [comment]
I'm experiencing a similar issue

```
git clone https://github.com/awslabs/amazon-sagemaker-examples.git
cd amazon-sagemaker-examples/advanced_functionality/pytorch_extending_our_containers/
cd container
docker build -t cifar .
```
I get 

```
Sending build context to Docker daemon  13.82kB
Step 1/6 : ARG REGION=us-west-2
Step 2/6 : FROM 520713654638.dkr.ecr.$REGION.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3
Get https://520713654638.dkr.ecr.us-west-2.amazonaws.com/v2/sagemaker-pytorch/manifests/0.4.0-cpu-py3: no basic auth credentials
```

Authentication doesn't help:

```
eval `aws ecr get-login --no-include-email`
docker build -t cifar .
```

Results in the same error.

I try to run it from my local computer (with an user that can perform `ecr get-login`) and on a sagemaker jupyter notebook. Both cases end with the same error

**Comment by domino14** [comment]
I have a similar issue as well, I can't access that `520713654638` account; I've tried us-west-2, us-east-1, etc and I get the same problem as @alexeygrigorev

**Comment by laurenyu** [comment]
@domino14, @alexeygrigorev - the ECR documentation around this is rather hard to find, but the way to authenticate to a public repo is

```bash
$(aws ecr get-login --no-include-email --registry-ids 520713654638)
```

**Comment by mfobert** [comment]
> @domino14, @alexeygrigorev - the ECR documentation around this is rather hard to find, but the way to authenticate to a public repo is
> 
> ```shell
> $(aws ecr get-login --no-include-email --registry-ids 520713654638)
> ```

Now that ecr get-login is deprecated, how can we go about fixing this issue?  I see https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html that we should use

`aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws`

but when i try this in practice,

`aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws && docker pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-eia:1.5.1-cpu-py36-ubuntu16.04`

I get
```
WARNING! Your password will be stored unencrypted in /home/mark/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Error response from daemon: Get https://763104351884.dkr.ecr.us-east-1.amazonaws.com/v2/pytorch-inference-eia/manifests/1.5.1-cpu-py36-ubuntu16.04: no basic auth credentials
```

Many thanks!
