### ISSUE TITLE
NTM Example uploads training data for the validation data S3 location

### ISSUE THREAD

**Issue by bt-jjh** [awslabs/amazon-sagemaker-examples#428]
In https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/ntm_20newsgroups_topic_modeling/ntm_20newsgroups_topic_model.ipynb

In the S3 section there is a cell with these lines:

split_convert_upload(train_vectors, bucket=bucket, prefix=train_prefix, fname_template='train_part{}.pbr', n_parts=8)
split_convert_upload(train_vectors, bucket=bucket, prefix=val_prefix, fname_template='val_part{}.pbr', n_parts=1)

Note the second line passes train_vectors for the first parameter but the path is for the validation s3 input.    Second line should be:

split_convert_upload(val_vectors, bucket=bucket, prefix=val_prefix, fname_template='val_part{}.pbr', n_parts=1)

**Comment by ChoiByungWook** [comment]
Hello @bt-jjh,

Thank you for bringing this to our attention.

I have submitted a PR to change the line.

https://github.com/awslabs/amazon-sagemaker-examples/pull/432

**Comment by ChoiByungWook** [comment]
The PR has been merged!
