### ISSUE TITLE
DeepAR context_length

### ISSUE THREAD

**Issue by pjebs** [awslabs/amazon-sagemaker-examples#441]
The documentation states `context_length` controls how far in the past the network can see.
`prediction_length` is how far into the future we want predictions for.

In https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_hyperparameters.html:

> The value for this parameter (context_length) should be about the same as the prediction_length.

Our prediction length is always the same: 4 weeks.
We always give full data which could be as long as 2 years of time series data.

Is it advantageous (in terms of prediction accuracy) to increase the context_length to cover the maximum length of data (albeit at performance cost)? I would assume the higher the context_length, the predictions will be more accurate.

**Comment by pjebs** [comment]
Does inputting less data that the context_length also mean that a model can't be generated?

**Comment by geoalgo** [comment]
Hi pjebs, thanks for trying DeepAR! 

The context length should indeed be set to a number roughly similar to the prediction length in general. 

So if you have 2 years of time-series data, and want to predict 4 weeks, the context length should be set to a comparable number say between 2 and 12, not the maximum length of the data (which would be around 2 * 52 if I understood you correctly).

If you look at [this page](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_how-it-works.html), you can see a visual explanation of the context length which is set in a much smaller value than the total length of the dataset (if you set the context length to the length of the dataset, there will only be very few available training examples).

So I suggest to use context_length = prediction_length = 4 in your case, if you are interested in learning a better value, you can use automatic model tuning https://aws.amazon.com/blogs/aws/sagemaker-automatic-model-tuning/ for instance.
