### ISSUE TITLE
Calling the tensorflow_iris_dnn example in tf.serve

### ISSUE THREAD

**Issue by jorgeb49** [awslabs/amazon-sagemaker-examples#444]
Hello, I am trying to serve the model artifacts created with the example _tensorflow_iris_dnn_classifier_using_estimators_   into tensorflow serve. 

The model builds with no problems but when calling the predictor with 
`curl -d '{"inputs":[1,2,3,4]}'   -X POST http://localhost:8501/v1/models/iris_model:predict`
I get this error:
{ "error": "JSON Value: 1 Type: Number is not of expected type: string" }

The serving input function is defined as
```

def serving_input_fn(hyperparameters):
    feature_spec = {INPUT_TENSOR_NAME: tf.FixedLenFeature(dtype=tf.float32, shape=[4])}
    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()

```

Where INPUT_TENSOR_NAME has been defined previously as 
`INPUT_TENSOR_NAME = 'inputs'`

Seems like it's expecting a string. But the feature_spec clearly says float32 :(
Have tried several options with no success.

Any help is much appreciated...

**Comment by mvsusp** [comment]
Hello @jorgeb49,

Looking at your request, it seems that your are trying to request against TF serving using the REST API. If that is the case, following TF serving API [request format](https://www.tensorflow.org/serving/api_rest#predict_api):

```json
{
  // (Optional) Serving signature to use.
  // If unspecifed default serving signature is used.
  "signature_name": <string>,

  // Input Tensors in row ("instances") or columnar ("inputs") format.
  // A request can have either of them but NOT both.
  "instances": <value>|<(nested)list>|<list-of-objects>
  "inputs": <value>|<(nested)list>|<object>
}
```

I would try ```curl -d '{"instances":[1.0,2.0,3.0,4.4]}' -X POST http://localhost:8501/v1/models/iris_model:predict

I'm closing this ticket for now, given that is a TensorFlow question.

Thanks for using SageMaker.
Best,
Márcio
