### ISSUE TITLE
Notebook sagemaker-countycensusclustering: S3 bucket aws-ml-blog-sagemaker-census-segmentation access denied

### ISSUE THREAD

**Issue by elangovana** [awslabs/amazon-sagemaker-examples#445]
Hi Team,
The bucket "aws-ml-blog-sagemaker-census-segmentation" used by the notebook [sagemaker-countycensusclustering]( https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb) is no longer public and hence get access denied even if the sagemaker role has access to all buckets.

Possible solutions to either move the dataset to [AWS public datasets](https://registry.opendata.aws/) or change the bucket policy to allow access to all accounts and all users

**Comment by TimBanks** [comment]
👍

**Comment by djarpin** [comment]
Thanks @elangovana - The bucket policy has been updated so the data should now be available publicly.  Let us know if you continue to experience issues.

**Comment by MbProg** [comment]
It is not available and I get access denied error message: 
`ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied`
