### ISSUE TITLE
Pytorch sagemaker container: Not implemented Error in model_fn

### ISSUE THREAD

**Issue by macsharma** [awslabs/amazon-sagemaker-examples#448]
Hi, 
I have defined model_fn in my test.py code, yet the cloud watch logs says model_fn not implemented.
trained_model_location: 's3://my-bucket/model/model.tar.gz'
model = PyTorchModel(model_data=trained_model_location,
                     role=role,
                     framework_version='0.4.0',
                     entry_point='test.py',
                     source_dir='source',
                     predictor_cls=JSONPredictor)

**Comment by nadiaya** [comment]
that should be working (e.g. https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_lstm_word_language_model/pytorch_rnn.ipynb ).

Is `test.py` located inside `source` directory?

Would it be possible to see the source code?

**Comment by macsharma** [comment]
Hi,
FOR THE MODELS  TRAINED ON EC2 and endpoint to be created on Sagemaker:
What I found was, since the model was trained on EC2 instance, we need to write a dummy train procedure (train.py), saving just the model files from EC2 and generating an estimator.

During hosting phase, we need to write our own model_fn, predict_fn, output_fn and input_fn in the same training script (train.py). A new test script (test.py) similar to the one in https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_lstm_word_language_model/pytorch_rnn.ipynb despite being in the same folder does not work.
Code for deployment is something like this:
predictor = estimator.deploy(endpoint_name='name', initial_instance_count=1, instance_type='ml.m4.xlarge')

By default the pytorch docker uses content type as 'application/npy', for json content types use the following:
predictor.content_type = 'application/json'
predictor.serializer = json_serializer
predictor.deserializer = json_deserializer
