### ISSUE TITLE
Sagemaker not Finishing the Training Process

### ISSUE THREAD

**Issue by bhairavmehta95** [awslabs/amazon-sagemaker-examples#470]
I am running a custom Sagemaker container, and the last lines of my file (for example) look like:

```
torch.save(...)
print("All done!")
return
```

I see the `"All done!"`, but the notebook cell never returns / completes. Is there something special that needs to be done for a clean exit of the specified `SAGEMAKER_PROGRAM`?

**Comment by laurenyu** [comment]
can you share your Dockerfile?

**Comment by bhairavmehta95** [comment]
https://github.com/duckietown/aido-on-sagemaker/blob/master/duckietown-pytorch-rl/container/Dockerfile

**Comment by bhairavmehta95** [comment]
Related to #469
