### ISSUE TITLE
DeepAR daily/weekly trends

### ISSUE THREAD

**Issue by pjebs** [awslabs/amazon-sagemaker-examples#502]
We are using DeepAR for forecasting sales data.

Would it be beneficial to use a category to indicate Sat and Sun or is DeepAR already good at detecting weekends just from the date information?

**Comment by lostella** [comment]
Hi @pjebs, there's no need to add such features in your data, DeepAR uses some predefined calendar-related features, see https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_how-it-works.html
