### ISSUE TITLE
Issue with AWS elastic Inference

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#503]
Hi,

I am trying to use AWS Elastic Inference feature. For that, I followed the notebook https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_mnist/mxnet_mnist_elastic_inference.ipynb

I am trying to deploy a trained MXNet model by loading weights from S3. When I tried to deploy it, I got the below error.

ValueError: Error hosting endpoint sagemaker-mxnet-eia-2018-11-29-23-14-31-700: Failed Reason:  The image '520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-eia:1.2-cpu-py3' does not exist.

Any suggestions will be helpful!

Thanks in advance!
Harathi

**Comment by ChoiByungWook** [comment]
Hello @Harathi123,

Thanks for using SageMaker!

As of now, Amazon Elastic Inference only supports 1.3 for MXNet and 1.11 for TensorFlow.

https://github.com/aws/sagemaker-python-sdk#mxnet-sagemaker-estimators
https://github.com/aws/sagemaker-python-sdk#tensorflow-sagemaker-estimators

To find the supported versions for each framework please check the SageMaker Python SDK README.

Please let me know if there is anything else I can clarify.

**Comment by Harathi123** [comment]
Thanks @ChoiByungWook!
Will it work for Gluon?
When I am trying to load Gluon model with mx.eia() context, i am getting error:
**ImportModuleError: 'module' object has no attribute 'eia'**

Can you please help me understand why its throwing error?

Thanks in advance,
Harathi

**Comment by ChoiByungWook** [comment]
I believe EI should work for Gluon.

Are you using our MXNet containers? 
Can you please post your stack trace along with the Python SDK code you are using to do this?

As of now Amazon Elastic Inference relies on a modified version of MXNet, which currently exists in our EI MXNet containers. That modified version of MXNet has the support for the mx.eia() context. If you are using an unsupported version of MXNet or your own binary than EI will not work as of now.

**Comment by Harathi123** [comment]
I am using AWS MXNet container. This the image name i am giving while creating model: 
**'520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet:1.3.0-cpu-py2'**
Is this correct?

Thanks,
Harathi

**Comment by ChoiByungWook** [comment]
That is incorrect. It should be 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-eia:1.3.0-cpu-py2

If you are using the Python SDK, then the image should have been generated properly on your behalf. Can you please share the code you are using to deploy your MXNet model?

**Comment by Harathi123** [comment]
Actually I trained the model on my local machine and uploaded that to S3 and using that to create model
I am doing it as follows:

from sagemaker.mxnet.model import MXNetModel
sagemaker_model = MXNetModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/localization_model/model.tar.gz',
                                  role = role,
                                  image = '520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet:1.3.0-cpu-py2', 
                                  entry_point = 'source_dir/localization.py')

Let me try with the image name you shared and will let you know whether it worked.

Thank you!
Harathi

**Comment by ChoiByungWook** [comment]
Awesome! Please let me know!

In order to avoid this problem, please specify the framework_version and not the image_name. The deploy() handles whether or not the EI image should be used if an accelerator_type was specified.

**Comment by Harathi123** [comment]
Don't i need to mention image_name? Just framework version is enough? And this is how i am deploying the model:
predictor = sagemaker_model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge', accelerator_type='ml.eia1.medium')

**Comment by anirudh2290** [comment]
Gluon is not supported for mxnet eia. It is only supported with module or symbol API. Linking the docs here:
```https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-mxnet-elastic-inference.html```

**Comment by Harathi123** [comment]
Thanks @anirudh2290 , got it!

Thanks,
Harathi
