### ISSUE TITLE
no examples for the api documentation

### ISSUE THREAD

**Issue by radsimu** [awslabs/amazon-sagemaker-examples#515]
the boto3 version of the sdk, is no where near the api as described in the aws documentation. There's no such thing as a sagemaker session in there, and that changes everything and makes things very difficult. I had to guess my way around to actually get things working from java

**Comment by jesterhazy** [comment]
Hi!

The sagemaker session is in the [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk), not in boto3. Sorry if this wasn't clear from the example you looked at.
