### ISSUE TITLE
DeepAR : When to build new model

### ISSUE THREAD

**Issue by ChandraLingam** [awslabs/amazon-sagemaker-examples#521]
Scenario:
We have two years worth of daily production data and need to forecast production for next 7 days.
At end of every day, we get actual production numbers for that day.

Based on deepar best practices document, for predictions, we need to pass the entire timeseries (in this case two years) to get prediction for the next 7 days

What is the suggested approach for handling new data?

1. Append new production data to the series, use existing model to forecast for subsequent 7 days
2. Rebuild model everyday with new training data?
3. any other option?

**Comment by lostella** [comment]
@ChandraLingam option 1 should be the first try. Whether the model's prediction accuracy degrades over time is highly problem dependent, I would say. Option 2 is usually an overkill. But it certainly is a good idea to monitor the predictions accuracy over time, and if that degrades significantly then consider training a new model.

**Comment by ChandraLingam** [comment]
@lostella Thank you
