### ISSUE TITLE
tensorflow_script_mode_using_shell_commands fails

### ISSUE THREAD

**Issue by sermolin** [awslabs/amazon-sagemaker-examples#533]
Failing notebook cell:
inputs = {'training': f'file://{data_dir}'}
estimator.fit(inputs)

Error message:
INFO:sagemaker:Creating training-job with name: sagemaker-tensorflow-scriptmode-2018-12-17-19-38-16-966
Creating tmp5nvkuj9k_algo-1-TQHT4_1 ... 
Attaching to tmp5nvkuj9k_algo-1-TQHT4_12mdone
algo-1-TQHT4_1  | 2018-12-17 19:38:41,863 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training
algo-1-TQHT4_1  | 2018-12-17 19:38:41,868 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
algo-1-TQHT4_1  | 2018-12-17 19:38:41,948 sagemaker-containers ERROR    Reporting training FAILURE
algo-1-TQHT4_1  | 2018-12-17 19:38:41,949 sagemaker-containers ERROR    framework error: 
algo-1-TQHT4_1  | Traceback (most recent call last):
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 66, in train
algo-1-TQHT4_1  |     entrypoint()
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py", line 152, in main
algo-1-TQHT4_1  |     s3_utils.configure(env.hyperparameters.get('model_dir'), os.environ.get('SAGEMAKER_REGION'))
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/s3_utils.py", line 23, in configure
algo-1-TQHT4_1  |     os.environ['S3_REGION'] = _s3_region(job_region, model_dir)
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/s3_utils.py", line 39, in _s3_region
algo-1-TQHT4_1  |     bucket_location = s3.get_bucket_location(Bucket=bucket_name)['LocationConstraint']
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 320, in _api_call
algo-1-TQHT4_1  |     return self._make_api_call(operation_name, kwargs)
algo-1-TQHT4_1  |   File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 624, in _make_api_call
algo-1-TQHT4_1  |     raise error_class(parsed_response, operation_name)
algo-1-TQHT4_1  | botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
algo-1-TQHT4_1  | 
algo-1-TQHT4_1  | An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
tmp5nvkuj9k_algo-1-TQHT4_1 exited with code 1
Aborting on container exit...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in train(self, input_data_config, output_data_config, hyperparameters, job_name)
    130         try:
--> 131             _stream_output(process)
    132         except RuntimeError as e:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in _stream_output(process)
    574     if exit_code != 0:
--> 575         raise RuntimeError("Process exited with code: %s" % exit_code)
    576 

RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-9-274879a8d731> in <module>()
      1 inputs = {'training': f'file://{data_dir}'}
      2 
----> 3 estimator.fit(inputs)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, run_tensorboard_locally)
    314                 tensorboard.join()
    315         else:
--> 316             fit_super()
    317 
    318     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    293 
    294         def fit_super():
--> 295             super(TensorFlow, self).fit(inputs, wait, logs, job_name)
    296 
    297         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    230         self._prepare_for_training(job_name=job_name)
    231 
--> 232         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    233         if wait:
    234             self.latest_training_job.wait(logs=logs)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in start_new(cls, estimator, inputs)
    561             train_args['image'] = estimator.train_image()
    562 
--> 563         estimator.sagemaker_session.train(**train_args)
    564 
    565         return cls(estimator.sagemaker_session, estimator._current_job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in train(self, input_mode, input_config, role, job_name, output_config, resource_config, vpc_config, hyperparameters, stop_condition, tags, metric_definitions, enable_network_isolation, image, algorithm_arn)
    311         LOGGER.info('Creating training-job with name: {}'.format(job_name))
    312         LOGGER.debug('train request: {}'.format(json.dumps(train_request, indent=4)))
--> 313         self.sagemaker_client.create_training_job(**train_request)
    314 
    315     def compile_model(self, input_model_config, output_model_config, role,

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/local_session.py in create_training_job(self, TrainingJobName, AlgorithmSpecification, OutputDataConfig, ResourceConfig, InputDataConfig, **kwargs)
     72         training_job = _LocalTrainingJob(container)
     73         hyperparameters = kwargs['HyperParameters'] if 'HyperParameters' in kwargs else {}
---> 74         training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)
     75 
     76         LocalSagemakerClient._training_jobs[TrainingJobName] = training_job

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/entities.py in start(self, input_data_config, output_data_config, hyperparameters, job_name)
     68         self.state = self._TRAINING
     69 
---> 70         self.model_artifacts = self.container.train(input_data_config, output_data_config, hyperparameters, job_name)
     71         self.end = datetime.datetime.now()
     72         self.state = self._COMPLETED

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/local/image.py in train(self, input_data_config, output_data_config, hyperparameters, job_name)
    134             # which contains the exit code and append the command line to it.
    135             msg = "Failed to run: %s, %s" % (compose_command, str(e))
--> 136             raise RuntimeError(msg)
    137 
    138         artifacts = self.retrieve_artifacts(compose_data, output_data_config, job_name)

RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmp5nvkuj9k/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

**Comment by sermolin** [comment]
The error is similar to https://github.com/awslabs/amazon-sagemaker-examples/issues/534

**Comment by ChoiByungWook** [comment]
These notebooks are missing the setup.sh file which is responsible for configuring the SageMaker notebook instance to enable training properly in local mode.

https://github.com/awslabs/amazon-sagemaker-examples/pull/534
