### ISSUE TITLE
scikit-bring-your own

### ISSUE THREAD

**Issue by walidsliti** [awslabs/amazon-sagemaker-examples#561]
hzllo @djarpin 

I'am trying to run the scikit BYO without changing anything and I get this error when I'am trying to fit the model

![image](https://user-images.githubusercontent.com/26322476/50835059-f54b2000-1355-11e9-8df4-881a8fc34ddd.png)

 ValueError: Error for Training job decision-trees-sample-2019-01-08-13-51-19-635: Failed Reason: AlgorithmError: Exit Code: 1

**Comment by Schmidtbit** [comment]
I am getting the same error.

**Comment by tandfy** [comment]
I removed fixed version of installing numpy in [Dockerfile](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/Dockerfile#L23) then training job worked well.

```
    pip install numpy==1.14.5 scipy scikit-learn pandas flask gevent gunicorn && \
```
↓
```
    pip install numpy scipy scikit-learn pandas flask gevent gunicorn && \
```
