### ISSUE TITLE
deepracer training stucked

### ISSUE THREAD

**Issue by P00L** [awslabs/amazon-sagemaker-examples#563]
Hi,

I'm trying to run the training job on sagemaker for the **rl_deepracer_robomaker_coach_gazebo** notebook but I'm having some problems. The training phase seems stucked at this line of code `graph_manager.fetch_from_worker(graph_manager.agent_params.algorithm.num_consecutive_playing_steps)` of the **training_worker.py** file.

The only difference between my notebook and the original one is that i removed the VPC mode execution.

Any suggestion to solve the problems?

Thanks

**Comment by bbalaji-ucsd** [comment]
The training will not work without VPC as it cannot communicate with the RoboMaker simulator then.
 
Can you please elaborate why you would like to disable VPC?

**Comment by P00L** [comment]
> The training will not work without VPC as it cannot communicate with the RoboMaker simulator then.
> 
> Can you please elaborate why you would like to disable VPC?

Hi, thanks for the suggestion. 
I didn't use the VPC simply because I don't manage it and also because we don't use the default VPC so I have to set up manually the configuration, since the code in the notebook is able to get only the configuration of the default VPC (if i remember correctly).
