### ISSUE TITLE
Wrong entrypoints in HVAC RL examples?

### ISSUE THREAD

**Issue by jbkoh** [awslabs/amazon-sagemaker-examples#572]
Hi there,

I am looking through the examples and they look great!

It looks like the entry points for model registration in the following file are incorrect:
https://github.com/awslabs/amazon-sagemaker-examples/blob/af765120763364193f099af0b283767cc2228ad3/reinforcement_learning/rl_hvac_coach_energyplus/src/eplus/__init__.py#L5
https://github.com/awslabs/amazon-sagemaker-examples/blob/af765120763364193f099af0b283767cc2228ad3/reinforcement_learning/rl_hvac_coach_energyplus/src/eplus/__init__.py#L10

According to 
https://github.com/awslabs/amazon-sagemaker-examples/blob/af765120763364193f099af0b283767cc2228ad3/reinforcement_learning/rl_hvac_coach_energyplus/src/eplus/envs/__init__.py#L1
and
https://github.com/awslabs/amazon-sagemaker-examples/blob/af765120763364193f099af0b283767cc2228ad3/reinforcement_learning/rl_hvac_coach_energyplus/src/eplus/envs/__init__.py#L2
, I think the entrypoints should be changed to:
```python
entry_point='eplus.envs:LargeOfficeEnv,' 
```
and 
```python
 entry_point='eplus.envs:DataCenterEnv,'
```

**Comment by jbkoh** [comment]
I see. Thanks for the comments!

**Comment by bbalaji-ucsd** [comment]
Fixed here: https://github.com/awslabs/amazon-sagemaker-examples/pull/590
