### ISSUE TITLE
Question: how to salvage intermediate checkpoints?

### ISSUE THREAD

**Issue by yifeim** [awslabs/amazon-sagemaker-examples#588]
Hi there,

I was wondering if I save model checkpoints to `model_dir` and then early-terminate training. Will I still be able to salvage the intermediate results and deploy them in inference servers?

https://docs.aws.amazon.com/sagemaker/latest/dg/API_StoppingCondition.html

According to this document, the containers have 2-minute response time before shutdown. I was wondering if sagemaker would actually use this grace period to upload existing artifacts. Does it guarantee successful uploads? If so, this probably needs to be better documented.

Btw, I was using MXNET estimator, but I think the observation generalizes to other frameworks as well.

Thanks.

**Comment by yifeim** [comment]
Related: 
* What is the best practice to guarantee atomic writes so saving does not conflict with uploading?
* If I have HPO but the logs do not contain the regex (because training has not actually finished), will HPO results be still usable but ordered by the latest finish time? Or will HPO fail, but still leave the last run as the dummy `bestTrainingJob`?

**Comment by ishaaq** [comment]
Hi yifeim,
This really depends on your algorithm and whether it is able to trap the SIGTERM signal and take advantage of the 2-minute grace period to save a model to the `/opt/ml/model` dir. Note that the 2-minute grace period is for *your* algorithm to finish up, SageMaker still has additional time after your container is finally terminated to do all its post-processing tasks (uploading the model is one of these tasks).

In addition to the documentation you linked to, there is additional information here as well:

https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo.html#your-algorithms-training-algo-dockerfile

Again, SageMaker only uploads the model *after* your algorithm container exits, so there is no conflict between what you write and the model SageMaker uploads. Just make sure you write a consistent model out well before your container gets force-terminated via a SIGKILL.

Early stopping in HPO works by inspecting your objective metrics and stopping the job early if the objective metric that matched the regex show worse performance. So, by definition, your early-stopped job MUST have at least one objective metric value emitted.

Hope that helps, let me know if you have additional questions or if something I said above isn't clear.

Thanks,
Ishaaq

**Comment by yifeim** [comment]
Thanks a lot. This is a good place to get started!
