### ISSUE TITLE
SageMaker Script Mode Serving

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#594]
I've trained a tensorflow.keras model using SageMaker Script Mode like this:

```
import os

import sagemaker
from sagemaker.tensorflow import TensorFlow

estimator = TensorFlow(entry_point='train.py',
                       source_dir='src',
                       train_instance_type=train_instance_type,
                       train_instance_count=1,
                       hyperparameters=hyperparameters,
                       role=sagemaker.get_execution_role(),
                       framework_version='1.12.0',
                       py_version='py3', 
                       script_mode=True)

```
However, how do I specify what the serving code is when I call estimator.deploy()? And what is it by default? Also is there any way to modify the nginx.conf using Script Mode?

**Comment by yangaws** [comment]
Hi @austinmw ,

Script mode uses SageMaker's `Tensorflow Serving Container` (TFS), you don't need to specify any serving codes. You could refer to the instruction here (https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst) to deploy your model from the estimator.

If you want to figure out what's TFS doing by default, you could check the repo https://github.com/aws/sagemaker-tensorflow-serving-container

And currently there's no easy way to modify nginx.conf during serving and we usually don't recommend users to modify the configs. Could you provide more details what you want to change for nginx.conf? If that's a general use case, we will consider to add features for that.

Thanks!

**Comment by austinmw** [comment]
@yangaws Hi, thanks. I'm mostly interested in adding a custom input function, which I now think I can do while still using the default serve.py. For nginx I would like to be able to increase timeouts. Also increasing payload size beyond 5 MiB to maybe 10-15 MiB would be very helpful.
