### ISSUE TITLE
what example to pursue 

### ISSUE THREAD

**Issue by walidsliti** [awslabs/amazon-sagemaker-examples#603]
hello,

I'am trying to deploy my own algorithm it's a neural network model which use tensorflow keras and other python librairies and frameworks that not supported in sagemker like [NILMTK](https://github.com/nilmtk/nilmtk/tree/master/docs/manual/user_guide)
I putted the artifacts in S3(my model trained out of sagemaker ) so the next step is to create the docker image and pushed on ECR. I'am not sure what should I put in the container, I saw the examples there some container that have (predictor,nginx, wsgi, server) and others not.
Can you please help me in that and give what example should I pursue? I need to mention that the problem is the conatiner files and not the dockerfile

Thank you

**Comment by laurenyu** [comment]
hi @walidsliti, we have an example notebook for building your own TF image here: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_bring_your_own/tensorflow_bring_your_own.ipynb

You can also reference the code used in the official SageMaker images:
* TF: https://github.com/aws/sagemaker-tensorflow-container
* TF Serving: https://github.com/aws/sagemaker-tensorflow-serving-container/

Alternatively, you might be able to use a shell script as your entry point with the TF Script Mode image to install NILMTK and other libraries before running training. You can find an example of using a shell script as your entry point here: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_using_shell_commands/tensorflow_script_mode_using_shell_commands.ipynb.

Hope that helps!
