### ISSUE TITLE
Unable to install opencv on custom pytorch container

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#614]
Hi,

I am following the example of pytorch extending container for creating custom container for my deploying my model. I need to install opencv in that. But while installing opencv, i am getting error regarding missing of libgtk module. So i installed that as well. Now i am getting another error:
**ImportError: No module named pkg_resources**

Full traceback:
File "/usr/local/bin/serve", line 6, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

Then i tried to install pkg_resources and also tried to reinstall setup-tools with the following command:
**RUN sudo apt-get install -y python3-pkg-resources python3-setuptools --reinstall**

But still getting the error.
Any suggestions will be helpful!

Thanks in advance,
Harathi

**Comment by andremoeller** [comment]
Hey @Harathi123 ,

Depending on your base image, you may have to install additional dependencies from Ubuntu repositories. Our Chainer has OpenCV installed. I've highlighted the relevant commands, depending on whether you want to make a CPU or GPU image:

Base CPU image:
https://github.com/aws/sagemaker-chainer-container/blob/a296cbc3a6a4ef0d9299ea4fd15b77772bc4f369/docker/base/Dockerfile.cpu#L1-L15

Final CPU image:
https://github.com/aws/sagemaker-chainer-container/blob/a296cbc3a6a4ef0d9299ea4fd15b77772bc4f369/docker/5.0.0/final/py3/Dockerfile.cpu#L1-L8

Base GPU image:
https://github.com/aws/sagemaker-chainer-container/blob/a296cbc3a6a4ef0d9299ea4fd15b77772bc4f369/docker/base/Dockerfile.gpu#L1-L5

Final GPU image:
https://github.com/aws/sagemaker-chainer-container/blob/a296cbc3a6a4ef0d9299ea4fd15b77772bc4f369/docker/5.0.0/final/py3/Dockerfile.cpu#L1-L8

And about the `pkg_resources` error, I suggest that you double-check to make sure that your `python` executable points to the expected python interpreter (python2 vs python3). In the Chainer Python 3 containers, for example, we replace the `/usr/bin/python` symlink to make sure we're running python3, not python2:

https://github.com/aws/sagemaker-chainer-container/blob/a296cbc3a6a4ef0d9299ea4fd15b77772bc4f369/docker/5.0.0/final/py3/Dockerfile.cpu#L5-L8

Hope this helps!

**Comment by Harathi123** [comment]
Thanks for the suggestions. I will try them out.
And please find the dockerfile below:

FROM 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3
 
RUN apt-get update && \
apt-get install sudo

RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN sudo apt install -y git
 
RUN sudo apt-get install -y cmake

RUN pip3 install cffi
 
RUN apt-get install -y python3-setuptools
 
# revised warpctc build step to match instructions at https://github.com/SeanNaren/warp-ctc
RUN git clone https://github.com/SeanNaren/warp-ctc.git && \
    cd warp-ctc && \
    git checkout ac045b6072b9bc3454fb9f9f17674f0d59373789 && \
    mkdir build; cd build && \
    cmake .. && \
    make && \
    cd ../pytorch_binding && \
    python3 setup.py install 
    # also need to install to correct python version
RUN pip3 install numpy scipy scikit-learn pandas flask gevent gunicorn && \
        rm -rf /root/.cache    
RUN pip3 install Pillow
RUN pip3 install python-Levenshtein
RUN python3 -m pip install opencv-python-headless
RUN apt-get update
RUN apt-get install -y libgtk2.0-dev
#RUN sudo apt-get install -y python3-pkg-resources python3-setuptools --reinstall
RUN python3 -m pip install --upgrade setuptools
#RUN pip3 install opencv-python-headless
ENV PATH="/opt/ml/code:${PATH}"

COPY /handwriting-ocr /opt/ml/code

RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /root/.cache
 
ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1 \
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
ENV SAGEMAKER_PROGRAM handwriting-ocr.py
ENV GUNICORN_CMD_ARGS="--timeout 1200"
WORKDIR /opt/ml/code

Thanks,
Harathi

**Comment by andremoeller** [comment]
Hey @Harathi123 ,

Thanks for posting!

```
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get install -y python3-setuptools
```

I'm not sure on this, but I think installing these dependencies might be causing the `setuptools` problem -- the python 3 PyTorch container itself should already have python3 and pip3 installed. I'd also suggest removing these lines.

HTH

**Comment by Harathi123** [comment]
Thanks @andremoeller,

Initially I tried without installing python, pip and setuptools. As I got error, I tried with installing them. Even though the error exists.

Thanks,
Harathi

**Comment by Harathi123** [comment]
Hi @andremoeller , 
I also tried installing opencv with apt-get. This is the dockerfile i used. I didnt installed python3, pip and setuptools.

FROM 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3
 
RUN apt-get update && \
apt-get install sudo

RUN sudo apt-get install -y cmake
RUN pip3 install cffi
 
# revised warpctc build step to match instructions at https://github.com/SeanNaren/warp-ctc
RUN git clone https://github.com/SeanNaren/warp-ctc.git && \
    cd warp-ctc && \
    git checkout ac045b6072b9bc3454fb9f9f17674f0d59373789 && \
    mkdir build; cd build && \
    cmake .. && \
    make && \
    cd ../pytorch_binding && \
    python3 setup.py install 

RUN pip3 install Pillow
RUN pip3 install python-Levenshtein

RUN sudo apt-get install -y python-opencv

ENV PATH="/opt/ml/code:${PATH}"

COPY /handwriting-ocr /opt/ml/code

RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /root/.cache
 
ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1 \
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
ENV SAGEMAKER_PROGRAM handwriting-ocr.py
ENV GUNICORN_CMD_ARGS="--timeout 1200"
WORKDIR /opt/ml/code

Even with this, i am getting pkg_resources error.

Traceback (most recent call last):
File "/usr/local/bin/serve", line 6, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

Any suggestions!
Thanks,
Harathi

**Comment by andremoeller** [comment]
Hi @Harathi123 ,

OK, I'll try reproducing this -- you're following this notebook, is that right?

https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/pytorch_extending_our_containers

**Comment by Harathi123** [comment]
Thanks @andremoeller , yes i am following the one you mentioned.

**Comment by ChoiByungWook** [comment]
@Harathi123,

Can you tell me what pip version you are on?

pip --version

If it is 19.0.1, I believe there have been numerous reports of errors with installing modules.

Try downgrading to 18.0 or 19.0.2 and trying again.

**Comment by Harathi123** [comment]
Hi @choiByungWook, I created custom container and installed everything from scratch instead of extending pytorch container. Now the issue got resolved.

**Comment by mehdizade** [comment]
@Harathi123 , I am experiencing the error that you just mentioned. 
To create and deploy on the Sagemaker, I am also planning to create a custom container. Where can I find the docker file associated with this base image:
520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:0.4.0-cpu-py3 on sa
