### ISSUE TITLE
Jupyterlab matplotlib widgets

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#624]
In a SageMaker jupyterlab environment I'm trying to use interactive matplotlib plots. For example:

```python
%matplotlib widget
import matplotlib.pyplot as plt
plt.figure()
x = [1,2,3]
y = [4,5,6]
plt.plot(x,y)
plt.show()
```

However, this just prints out:
`FigureCanvasNbAgg()`

As per [these instructions](https://github.com/matplotlib/jupyter-matplotlib) I opened a terminal and ran:

```
pip install ipympl
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
```

Then restarted my jupyterlab kernel, but still have the same output. How can I use **%matplotlib widget** in SageMaker jupyterlab environment?

**Comment by ChoiByungWook** [comment]
Hi @austinmw,

Are you using the same conda environment you installed your dependency in?

If not most likely you need to install your dependency in the same conda environment your notebook kernel is running in.

Please try this in the notebook cell and restart the kernel.

`! pip install ipympl`

Or you can also activate the conda environment in the terminal and install your dependency.

```
# list the available conda envs
conda env list

# EXAMPLE activate the tensorflow_p27 env
source activate tensorflow_p27

pip install ipympl
```

Let me know if this works for you.

**Comment by austinmw** [comment]
@ChoiByungWook Thanks, I think that was it. Installing the jupyter lab extensions with ! did not seem to work, but using %%bash did.
