### ISSUE TITLE
A way to delete failed batch transform jobs

### ISSUE THREAD

**Issue by odgiv** [awslabs/amazon-sagemaker-examples#633]
Hello, is there any way to delete a failed batch transform job. I am kind of stuck here. 

![capture](https://user-images.githubusercontent.com/18517999/53031093-7248d980-346c-11e9-8c04-732b9a667088.PNG)

**Comment by mmeidl** [comment]
Hello @odgiv, there is no way to delete a SageMaker Transform Job. The name of each Transform Job must be unique, and each job's metadata will be persisted forever, whether the job Failed or Completed. The same is true for SageMaker Training Jobs.

Apologies for the overdue response. I hope that this answers your question.

**Comment by chriss1245** [comment]
give me more recent information

**Comment by chriss1245** [comment]
Hi, I just wanted to verify that this is still the case. I wanted to delete training jobs from the console.
