### ISSUE TITLE
tensorflow_script_mode_quickstart script_mode and py_version setting contradict SDK documentation

### ISSUE THREAD

**Issue by sermolin** [awslabs/amazon-sagemaker-examples#635]
- Documentation (https://sagemaker.readthedocs.io/en/stable/sagemaker.tensorflow.html) says:
"script_mode (bool) – If set to True will the estimator will use the Script Mode containers (default: False). This will be ignored if py_version is set to ‘py3’."

- Yet the example https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_quickstart/tensorflow_script_mode_quickstart.ipynb
shows   py_version='py3', script_mode=True)

estimator = TensorFlow(entry_point='train.py',
                       source_dir='char-rnn-tensorflow',
                       train_instance_type='ml.c4.xlarge', # Executes training in a ml.c4.xlarge instance
                       train_instance_count=1,
                       hyperparameters=hyperparameters,
                       role=sagemaker.get_execution_role(),
                       framework_version='1.11.0',
                       py_version='py3',
                       script_mode=True)

Hopefully the problem is with the documentation....

**Comment by nadiaya** [comment]
Setting any of those parameters (`py_version='py3'` or `script_mode=True`) will make the estimator to use Script Mode containers.

If you set `script_mode=False` and ` py_version='py3'`, `script_mode=False` will be ignored and estimator would still use Script Mode container.

Both the documentation and the notebook are correct, though notebook is a bit redundant for sake of showing possible settings more explicitly to the users.
