### ISSUE TITLE
Outdated numpy version in containers

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#636]
I've deployed a PyTorch model locally like this:

```python
model = PyTorchModel(name=name_from_image('Pytorch-model'),
                     model_data=estimator.model_data,
                     role=role,
                     framework_version='1.0.0',
                     entry_point='serve.py',
                     source_dir=os.getcwd()+'/src/',
                     sagemaker_session=my_local_session,
                     predictor_cls=ImagePredictor)

predictor = model.deploy(initial_instance_count=1, instance_type='local')
```

Although deploying seems to work and I'm able to get responses from my endpoint, the deploy command also outputs these errors:

```
algo-1-eathq_1  | ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
algo-1-eathq_1  | ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
algo-1-eathq_1  | ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
algo-1-eathq_1  | ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

I'm pretty sure this is related to not having numpy v1.16.1 in these containers. Is there any chance that the version could be updated?

**Comment by nadiaya** [comment]
Yes, the version was frozen to 1.15.4 because of the numpy bug introduced in 1.16.0 in one of the core sagemaker packages in the container.
We already removed the restriction and the containers with newer numpy version will be available in the near future.
