### ISSUE TITLE
Pipe input mode for successive binary files

### ISSUE THREAD

**Issue by TomoakiPeterSano** [awslabs/amazon-sagemaker-examples#648]
I'm trying to use Pipe-Input mode for training job.

In advance, I made an example case; training samples are in `s3://my-bucket/dataset/training/0.sample` thru `s3://my-bucket/dataset/training/15.sample` and all samples are 1536 Bytes(float32 x (16 x 24) matrices).

And here is `trainer.py`
```python
fifo_path = os.path.join(data_dir, "{}_{}".format(channel, epoch))
  
wait_till_fifo_exists(fifo_path)
fifo = open(fifo_path, "rb", buffering=0)
print("Opened FIFO: %s" % fifo_path)
data = bytearray(4*(16*24)*8)
start = time.time()
bytes_read = fifo.readinto(data)
print(bytes_read)
while bytes_read == 4*(16*24)*8 and not terminated:
    X = np.array(struct.unpack("f"*(16*24)*8, data).reshape(8, 16, -1))
    print(X)
    start =time.time()
    bytes_read = fifo.readinto(data)

fifo.close()
```
`trainer.py` is a script that executed by `python` in my dokcer image when `train` command is issued by SageMaker, and in this case I assume that batch size is `8` , so I thought being able to read 12288 (=1536x8)Bytes in one `readinto()` is convenient.

Here is InputDataConfig of training request parameter.
```json
"InputDataConfig": [
    {
        "ChannelName": "training",
        "DataSource": {
            "S3DataSource": {
                "S3DataType": "S3Prefix",
                "S3Uri": "s3://my-bucket/dataset/training/",
                "S3DataDistributionType": "FullyReplicated"
            }
        },
        "InputMode": "Pipe"
    }
]
```

But when I created training job, in CloudWatch Logs, there is many `1536`s produced by `print(bytes_read)`, not `12288` I expected.

My Question is, is it able to read some successive binary files(fixed size) in one `readinto` instruction?

Many thanks for your reading.

**Comment by ishaaq** [comment]
Like in any call to `readinto()` only the bytes that are immediately available will be read. You will have to buffer up all the individual bytes until you accumulate 12288 bytes if that is what you want to do.
