### ISSUE TITLE
"scikit-learn=0.20.2"

### ISSUE THREAD

**Issue by Afonia27** [awslabs/amazon-sagemaker-examples#649]
In the "amazon-sagemaker-examples/advanced_functionality/scikit_bring_your_own/container/Dockerfile" line 23 has a statement `scikit-learn=0.20.2` as a part of the pip install campaign. This statement will cause problems such as: 

```
Invalid requirement: 'scikit-learn=0.20.2' = is not a valid operator. Did you mean == ?"  
```
and would imply chain reaction of problems such as:

`Error response from daemon: No such image:...`
and
`An image does not exist locally with the tag:`. 

Solution is simply to replace 
`scikit-learn=0.20.2` with `scikit-learn==0.20.2`

**Comment by mvsusp** [comment]
Hi @Afonia27 ,

Thanks for your bug report. We made the suggested fix and the example is working again.

Thanks for using SageMaker!
