### ISSUE TITLE
Sagemaker working with tf records for batch transform jobs (Example), fails to invoke the result

### ISSUE THREAD

**Issue by Karan970** [awslabs/amazon-sagemaker-examples#667]
Error message

{ "error": "JSON Value: {\n \"signature_name\": \"predict\",\n \"instances\": []\n} not formatted correctly. Expecting object with 'instances' or \'input\' key and a list/array or object as the value respectively." }

This a default example, I suspect the serving container, not parsing the tfrecords and returning the arrays of records to invoke

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/working_with_tfrecords/tfrecord-transformer-container/app/main.py

**Comment by Karan970** [comment]
I am using the same iris record in the given notebook

**Comment by apacker** [comment]
I've put out a PR with a fix: https://github.com/awslabs/amazon-sagemaker-examples/pull/682
