### ISSUE TITLE
SageMaker Train job is not creating /opt/ml/input/data/training directory

### ISSUE THREAD

**Issue by deneshkumar** [awslabs/amazon-sagemaker-examples#670]
I am trying to create a custom algorithm by following the instruction given in this tutorial <>. 

When I am running the train job it is failing with error No such file or directory: '/opt/ml/input/data/training'.

As per the documentation, SageMaker should create these documents and copy the data and artifacts during the runtime.  But this is not happening.

Please share your thoughts on this.

**Comment by ishaaq** [comment]
SageMaker will only create that directory and contents if you configure it to do so via input data. I don't see the tutorial link you mentioned so can't confirm what it is you are testing. Resolving this for now - please reopen with more details if you'd like us to investigate further.

**Comment by ZoranPandovski** [comment]
@deneshkumar I got a similar issue and found out the channel_name is changed to `train` instead of `training`.
