### ISSUE TITLE
Change repo title and tags

### ISSUE THREAD

**Issue by yanisIk** [awslabs/amazon-sagemaker-examples#672]
After looking at a recent [AWS Online Tech Talk about RL with SageMaker](https://www.youtube.com/watch?v=xGD6rkPuQ7Q), I found this repo (which is referenced in the video) and I asked myself why I didn't see it before when I was looking for RL information.

I found that the following can be changed:

**Change title from:**

> Example notebooks that show how to apply machine learning and deep learning in Amazon SageMaker

**to:**

> Example notebooks that show how to apply machine learning, deep learning and reinforcement learning in Amazon SageMaker

**Add the following tags:**

> RL, Reinforcement learning

This will improve the visibility of the repo, since a lot of people are searching using RL keywords to find code examples.

This repo contains many well written RL examples, that work on SageMaker and have the potential to attract people to your platform.

**Comment by vrkhare** [comment]
Hi @yanisIk thanks for the suggestions. I have made the suggested changes. Thanks!
