### ISSUE TITLE
image-classification-lst-format seems to be broken

### ISSUE THREAD

**Issue by alex9311** [awslabs/amazon-sagemaker-examples#681]
I've tried the [example notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/imageclassification_caltech/Image-classification-lst-format.ipynb) for "image classification training with image format" a few times and keep getting failed training with `Customer Error: Invalid lst file in the train channel.` All I change in the notebook is the bucket name at the top.

When I download the lst files from s3 or from the jupyter notebook they seem fine to me.

**Comment by wiltonwu** [comment]
Hi,

I apologize for the delayed response. This issue should be fixed now. I'm going to close this issue, but please reopen if you still see the `Customer Error: Invalid lst file in the train channel.` issue again.

**Comment by alex9311** [comment]
thanks! Would you mind pointing me to the commit that made the fix? The notebook hasn't been updated since sept 2018

**Comment by wiltonwu** [comment]
The fix was located on our end in the SageMaker Image Classification algorithm.
