### ISSUE TITLE
module initialization error, lambda to sagemaker?

### ISSUE THREAD

**Issue by ilyes-hamrouni** [awslabs/amazon-sagemaker-examples#693]
i am trying this tutorial
https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/

whenever i try the lambda function, i get this error 
`module initialization error: 'ENDPOINT_NAME'`

this is the code i wrote
`import os
import io
import boto3
import json
import csv

# grab environment variables
runtime= boto3.client('runtime.sagemaker')
ENDPOINT_NAME = os.environ['factorization-machines-2019-03-23-19-41-56-103']  //problem is right here.

def lambda_handler(event, context):
// rest of the handler
`

**Comment by jesterhazy** [comment]
@ilyes-hamrouni 

Thanks for using SageMaker!

The issue you describe seems to be a problem with the lambda code in the blog post, not the code in the example notebook here in this repo. The blog post has a comment feature, and I see the author has been responding to other users' questions there. I suggest you repost your question there.

I am closing this issue. Feel free to open a new one if you run into trouble with the notebook!

**Comment by jesterhazy** [comment]
@ilyes-hamrouni 

the line you are having trouble with should be:

`ENDPOINT_NAME = os.environ['ENDPOINT_NAME']`

**Comment by dicksonj** [comment]
if you have endpoint created then this line is supposed to be:
ENDPOINT_NAME = '<name_of_endpoint>' not os.environ['ENDPOINT_NAME']
