### ISSUE TITLE
Unable to train Object detection with other base network than resnet-50 and vgg-16

### ISSUE THREAD

**Issue by Bannaro** [awslabs/amazon-sagemaker-examples#710]
Hello, I know that right now we can only train an object-detection model with resnet-50 or vgg-16 as base network.

But I would like to know why are they the only one to be allowed as hyperparameters.
In my case I have a small dataset (~300 pictures) and after doing some researchI found that resnet-18 is better than resnet-50 for small datasets.

So isn't it possible to train this algorithm with other base network than resnet-50 and vgg-16 because they are the only compatible (by design) ? Or is it just a limitation to avoid weird behaviors and results ?

Thank you in advance for your guidance

**Comment by wiltonwu** [comment]
Hi,

Unfortunately, it is by design. SageMaker Object Detection currently only supports resnet-50 and vgg-16. We'll consider your use case and log this issue as a feature request for more base networks.
