### ISSUE TITLE
sagemaker pipeline with sklearn preprocessor and xgboost 

### ISSUE THREAD

**Issue by ChandraLingam** [awslabs/amazon-sagemaker-examples#729]
I built a sagemaker pipeline with preprocessor built on sklearn (similar to abalone sagemaker example) and model built using XGBoost.

When I deployed the inference pipeline,  it appears XGBoost predict call is made using application/json.  

For the realtime predictor, I had specified both content-type and accept to 'text/csv'

> ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (415) from container-2 with message "Content-type application/json not supported. Supported content-type is text/csv, text/libsvm

```
scikit_learn_inference_model = sklearn_preprocessor.create_model()
learner_model = estimator.create_model()

model_name = 'inference-pipeline-' + timestamp_prefix
endpoint_name = 'inference-pipeline-ep-' + timestamp_prefix
sm_model = PipelineModel(
    name=model_name, 
    role=role, 
    models=[
        scikit_learn_inference_model, 
        learner_model])

sm_model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge', endpoint_name=endpoint_name)

```
**Predictor Code:**
```
from sagemaker.predictor import json_serializer, csv_serializer, json_deserializer, RealTimePredictor
from sagemaker.content_types import CONTENT_TYPE_CSV, CONTENT_TYPE_JSON

predictor = RealTimePredictor(
    endpoint=endpoint_name,
    sagemaker_session=sagemaker_session,
    serializer=csv_serializer,
    content_type=CONTENT_TYPE_CSV,
    accept=CONTENT_TYPE_CSV)

print(predictor.predict(payload))
```
How I do ensure the content type and accept request are honored.  It appears that internally, it is converted to application/json before invoking XGBoost

**Comment by vjammar** [comment]
Hi Chandra, 
I also faced this issue recently. Apparently XGBoost will only accept csv or libsvm. To ensure the content coming out from container 1 (the sklearn model) is in the right format, you have to set the environment variable on that container. Most models will take json but currently XGBoost does not so that's why this issue exists.

You have to do something like:
`scikit_learn_inference_model.env = {"SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT":"text/csv"}`
before you create the PipelineModel.

This will ensure the scikit learn model produces csv to feed into the next container. 
Currently I am trying to get json out of the XGBoost container but no matter what, it returns csv.

**Comment by asadoughi** [comment]
Hi ChandraLingam, the suggestion provided by vjammar should work. In fact, you should be able to specify `env` as a keyword argument to [create_model](https://github.com/aws/sagemaker-python-sdk/blob/6aa409bfdd1fc65212a787bb605dea558d033ab0/src/sagemaker/sklearn/estimator.py#L116). For example, `sklearn_preprocessor.create_model(env={"SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT": "text/csv"})`

Hi vjammar - XGBoost's response format only supports `text/csv` in the current implementation.

**Comment by DanyalAndriano** [comment]
Hi @vjammar,

I was wondering whether you set this environment variable in the notebook or in the entry script?

**Comment by vjammar** [comment]
Hi @DanyalAndriano ,
The environment variable was set in the notebook when creating the pipeline. 

Something like:
```
preprocessor_model = preprocessor.create_model()
preprocessor_model.env = {"SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT":"text/csv"}
OTHER MODELS...

model.pipeline = PipelineModel(
        name=model_name, 
        role=role, 
        models=[
            preprocessor_model,
            LIST OF OTHER MODELS IN PIPELINE
       ])

```

**Comment by anno1406** [comment]
Hi, I followed the instructions to set the SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT env variable but I'm getting an 

`ValueError: Content type text/csv; charset=utf-8 is not supported.` error when running the batch transform job on the 2nd (xgboost) container that is following the sklearn container. 

My pipeline code looks as following:

   ```
 feature_model = SKLearnModel(
       model_data=feature_model_s3,
       sagemaker_session=sagemaker_session,
       role=role,
       framework_version=params.sagemaker_feature_transform.framework_version,
       entry_point = os.path.join(BASE_DIR, "scripts", "sagemaker_feature_transform.py")
    )

    feature_model.env = {"SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT":"text/csv"}

xgb_train = XGBoost(
        entry_point= os.path.join(BASE_DIR, "scripts", "sagemaker_xgb_training.py"),
        role=role,
        instance_count=training_instance_count,
        instance_type=training_instance_type,
        framework_version="1.0-1",
        sagemaker_session=sagemaker_session,
        base_job_name= "model-train" ,
        hyperparameters = { .... },
    )

    step_train = TrainingStep(
        name="train-model" ,
        estimator=xgb_train,
        inputs={
            "train": TrainingInput(
                s3_data=step_train_feature_model.properties.ProcessingOutputConfig.Outputs["train"].S3Output.S3Uri,
                content_type="text/csv",
            ),
            "validation": TrainingInput(
                s3_data=step_train_feature_model.properties.ProcessingOutputConfig.Outputs["validate"].S3Output.S3Uri,
                content_type="text/csv",
            ),
        },
    )

    model = XGBoostModel(
        framework_version="1.0-1",
        model_data=step_train.properties.ModelArtifacts.S3ModelArtifacts,
        sagemaker_session=sagemaker_session,
        entry_point= os.path.join(BASE_DIR, "scripts", "sagemaker_xgb_training.py"),
        role=role
    )

    pipeline_model = PipelineModel(
        name= "pipeline-model",
        role=role,
        models=[feature_model, model],
        sagemaker_session=sagemaker_session
    )

```

For inference output code of container 1 (sklearn) I am using:

```
from sagemaker_containers.beta.framework import ( encoders, worker)

def output_fn(prediction, accept):
    if accept == "text/csv":
        return worker.Response(encoders.encode(prediction, accept), mimetype=accept)
    else:
        raise RuntimeException("{} accept type is not supported by this script.".format(accept))

```

For inference input code of container 2 (xgb) I am using:

```
def input_fn(request_body, request_content_type):

    if request_content_type == "text/libsvm":
        return xgb_encoders.libsvm_to_dmatrix(request_body)
    elif request_content_type == "text/csv":
        return xgb_encoders.csv_to_dmatrix(request_body)
    else:
        raise ValueError("Content type {} is not supported.".format(request_content_type))
```

It seems like even though I am forcing the output content type of container 1 to "text/csv", what is arriving in container 2 is an unkown "text/csv; charset=utf-8" format. Any ideas of what I am doing wrong ?

Thank you for your help!
