### ISSUE TITLE
How to test Predictive Auto-scaling with Amazon SageMaker RL

### ISSUE THREAD

**Issue by yahavb** [awslabs/amazon-sagemaker-examples#730]
I deployed the notebook and now I want to get the predictions needed to fulfill the idea of the sample. Anything I do fails. 
the boto code I could glean from searching over google is:
```
#!/usr/bin/python
  
import boto3

client = boto3.client('sagemaker-runtime')

endpoint_name = "...."
content_type = "application/json"
accept = "application/json"
payload = "{'0.0'}"

response = client.invoke_endpoint(
    EndpointName=endpoint_name,
    ContentType=content_type,
    Accept=accept,
    Body=payload
    )

print(response['Body'])
```
it fails with error `botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "{ "error": "JSON Parse error: Missing a name for object member. at offset: 15" }". See..`

I tried to use:
```
payload = "{'0.0'}"

payload = "{'instances': '[1.0,2.0,5.0]'}

payload = "{'instances': '1.0,2.0,5.0'}
```

none works. Is there a way to use the endpoint?

**Comment by yahavb** [comment]
I am looking for example like in https://cloud.google.com/ml-engine/docs/tensorflow/custom-prediction-routine-keras under `Serving online predictions`

**Comment by tao2020** [comment]
The error comes from incorrect json format, the correct format should be `payload = '{"instance": [1.0, 2.0, 5.0]}'.`

 More details of how it works please read [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/predictor.py#L62)

Basically the predictor would use (or not) a serializer and a deserializer for the data. When you use json (de)serializer (as you show in your example), it will  [serializes the input data first](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/predictor.py#L299) before calling the `invoke_endpoint` function and [querying the endpoint model](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/local_session.py#L177). So you could simply provide a python list or array as input, and use the json serializer to figure out the correct format. eg.
```
from sagemaker.content_types import CONTENT_TYPE_JSON
from sagemaker.predictor import json_serializer, json_deserializer

# use list or numpy array as input, the serializer will provide the correct format
payload = {'instance': [1.0, 2.0, 5.0]}   # or payload = [1.0, 2.0, 5.0]
payload = json_serializer(payload)        # payload = '{"instance": [1.0, 2.0, 5.0]}'  or '[1.0, 2.0, 5.0]'

response = client.invoke_endpoint(...)

# then deserialize
print(json_deserializer(response['Body'], response['ContentType']))     # response['ContentType'] == CONTENT_TYPE_JSON
```

If you follow the notebook example of autoscaling, you don't need to do all these (de)serializing work, the notebook provides an example
```
predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.c5.xlarge')  # for hosting the endpoint model
observation = np.arange(1, 26)   
action = predictor.predict(observation)   # for inference
print(action)  
```

the `predictor` by default will use the json (de)serializer, and will do all the dirty work for you.

**Comment by yahavb** [comment]
Thanks. none of the options worked for me. Perhaps I am lost with the sterilization and deserialization. Also, you notes on the notebook example not clear as well. 
Let me ask it differently, I want to get prediction continuously. It is not just to check the predictor or else is working. Is there a complete example that describes how to get predictions thru a job that is outside of the notebook? to me and maybe I am wrong, the notebook is the training application. it decoupled from the endpoint that seeks for predictions. If I am wrong, what is the recommended data flow or architecture for consuming continuously predictions?

**Comment by yahavb** [comment]
Just to give another example of the Boto client of the previous Amazon ML service

```
@app.route('/predict/{region}')
def predict(region):
  try:
    time.strftime('%Y-%m-%d %H:%M:%S')
    timestamp=time.strftime('%Y-%m-%d %H:%M:%S')
    instance_to_predict = {
        "Var1"      : region,
        "Var3"       : timestamp
    }
    response = ml_client_connection.predict(
       MLModelId = MLModelId,
       Record = instance_to_predict,
       PredictEndpoint = EndpointUrl
    )
    return {'Prediction':{'num_of_gameservers':response["Prediction"]["predictedValue"],'region':region,'timestamp':timestamp}}
  except Exception as e:
    logger.error("ERROR: %s",str(e))```

Is there any similar way one can query the model without all the acrobatics or with example?

**Comment by yahavb** [comment]
ok this was an RTFM case on my side. 
I mimicked the part from notebook and your code worked 
```
payload = np.arange(1, 26)
payload = json_serializer(payload)

response = client.invoke_endpoint(
    EndpointName=endpoint_name,
    ContentType=content_type,
    Accept=accept,
    Body=payload
    )

# then deserialize
print(json_deserializer(response['Body'], response['ContentType']))
print(payload)
```
