### ISSUE TITLE
SageMaker PySpark XGBoost Exception

### ISSUE THREAD

**Issue by sumeshmr** [awslabs/amazon-sagemaker-examples#732]
Hello,

PySpark XGBoost example is throwing an error when I call the fit method. It used to work earlier.

**ValueError**: Param Param(parent='Identifiable_d8de2913f225', name='lambda', doc='L2 regularization term on weights, increase this value will make model more conservative.') does not belong to Identifiable_d8de2913f225.

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-spark/pyspark_mnist/pyspark_mnist_xgboost.ipynb

**Comment by wiltonwu** [comment]
Hello,

PySpark recently released new versions and it seems to contain breaking changes.  We recently released a fix here: https://github.com/aws/sagemaker-spark/pull/83 to mitigate that issue. Please let us know if the error still persists.
