### ISSUE TITLE
scikit-bring-your-own: local test script broken

### ISSUE THREAD

**Issue by tomfaulhaber** [awslabs/amazon-sagemaker-examples#742]
In commit 57e8717d1dd8e45d67f60f14831d95b01b438785, we started dropping the first column of the input (which is the label in the training data). You can see the change here: https://github.com/awslabs/amazon-sagemaker-examples/commit/57e8717d1dd8e45d67f60f14831d95b01b438785#diff-e67285ffa1c077a429c35c8eebaf6ac0R76

This is probably the wrong thing. The inference function should not assume that it has labels (after all, the whole point of inference is that we're trying to find that value).

In particular, that breaks the local testing code that's included in this package. This is because the `payload.csv` file doesn't have labels.

We should fix the problem the right way, but in the meantime, an easy workaround is to add a dummy label to the test payload:

```
$ sed 's/^/0,/' payload.csv > payload-1.csv
$ ./predict.sh payload-1.csv
```

**Comment by j3ffreyjohn** [comment]
Addressed by #771 . Resolving!
