### ISSUE TITLE
[Feature Request] Modifying SM_MODULE_DIR

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#745]
Not being able to change `SM_MODULE_DIR` can make s3 organization very ugly. For example, I have a bucket named `sagemaker-research` with subdirectories like `datasets`, `classification-jobs`, `object-detection-jobs`, etc. I can specify that a training job's output is placed into, for example, `classification-jobs/<training_job_name>/output`, but instead of placing the source code upload directly next to the output, it's placed in the root path of the bucket, really cluttering my s3 organization.

We should be able to change this with either a `module_dir` hyperparameter or by passing a `SM_MODULE_DIR` environment variable to the estimators.

**Comment by leolorenzoluis** [comment]
@austinmw What was your solution?
