### ISSUE TITLE
from misc import get_execution_role, wait_for_s3_object

### ISSUE THREAD

**Issue by saunak14** [awslabs/amazon-sagemaker-examples#746]
The above-mentioned `wait_for_s3_object` import statement in any of the reinforcement learning (rl) python notebook examples do not work. Please help.

**Comment by yijiezz** [comment]
Hi @saunak14,

Can you elaborate a little bit on how it failed?
Does the line `from misc import get_execution_role, wait_for_s3_object` simply failed?

**Comment by chester755** [comment]
Hi,

Yeah, I have a similar problem trying to run that on my local machine (as I want to see how that performance).
Below is the error message I get:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8094e9abd582> in <module>
     10 from time import gmtime, strftime
     11 sys.path.append("common")
---> 12 from misc import get_execution_role, wait_for_s3_object
     13 from sagemaker.rl import RLEstimator, RLToolkit, RLFramework

ModuleNotFoundError: No module named 'misc'

From the research, it seems like the misc package is the AWS package.
Could you please help me with that?

**Comment by sidd1809** [comment]
Hi @chester755 ,

Can you provide details on how you are using the example notebook?

'misc' and other modules are present in common/  and we append common/ to sys.path before importing any module. We moved this common module one level up, and symlink-ed  the common directory in each example notebooks. If you are copying the notebook folder else were, you might want to use -L flag with the cp  command as explained here: https://unix.stackexchange.com/questions/94714/cp-l-vs-cp-h

**Comment by chester755** [comment]
Hi @sidd1809 

Thanks for your reply.
Sure I am basically git clone the repository into my windows machine, where I have Anaconda, Jupyter notebook installed,
After starting the Jupyter notebook and navigate to the example I want to try locally, I have started to run the example (rl_traveling_salesman_vehicle_routing_coach).
Two things are failed at the moment, one of them is can't find module sagemaker, the other one is the 'misc' module which I think I can bypass now.
The error message whenever I tried to install sagemaker through conda pip are as follows:

Installing collected packages: jmespath, botocore, s3transfer, boto3, protobuf, protobuf3-to-dict, PyYAML, idna, requests, cached-property, texttable, docopt, websocket-client, dockerpty, pypiwin32, pynacl, bcrypt, paramiko, docker, docker-compose, sagemaker
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by e0003315** [comment]
i faced the same issue today. Is instructions on how to create the proper environments to run RL example codes. i tried running on my Jupiter notebook instance with rl_cartpole_batch_coach example but packages are missing.

**Comment by annaluo676** [comment]
Hey, instead of `sys.path.append("common")`, can you try `sys.path.append("/root/amazon-sagemaker-examples/reinforcement_learning/rl_cartpole_batch_coach/common")`?

**Comment by PalmsDragon** [comment]
Hi, has this been solved ? I get the same issue. Im opening the notebooks in Jupyter using Sagemaker notebook instance. - I get no module named 'misc' 
![bug in notebook in misc import](https://user-images.githubusercontent.com/59027456/71109340-03730480-2193-11ea-8b08-3c3285efe258.PNG)

**Comment by PalmsDragon** [comment]
I changed the 'misc' import to sagemaker --> its ok with get_execution_role, but not so with wait_for_s3_object. Any help ??
![bug in notebook in sagemaker import](https://user-images.githubusercontent.com/59027456/71109452-35846680-2193-11ea-8c99-4c24827c4064.PNG)

**Comment by annaluo676** [comment]
Have you tried `sys.path.append("/root/amazon-sagemaker-examples/reinforcement_learning/rl_cartpole_batch_coach/common")`?  If you are using SageMaker Studio, the path can be different as it's mounted on EFS (see https://github.com/awslabs/amazon-sagemaker-examples/issues/955).

**Comment by annaluo676** [comment]
Closing this issue due to the date of the last activity on it. Please feel free to re-open if you still see any related errors.
