### ISSUE TITLE
SageMaker Notebook instances: update JupyterLab in order to use Altair visualizations

### ISSUE THREAD

**Issue by dennari** [awslabs/amazon-sagemaker-examples#795]
I'd love to be able to use the lovely [Altair](https://altair-viz.github.io/index.html) library for data visualization on my SageMaker Notebook instance. However it seems that this requires at least JupyterLab v1.0, which was just released. Could you please update the default JupyterLab installation and perhaps also include Altair?

I know I can install extra Python packages easily, but updating JupyterLab seems to not be as trivial.

**Comment by dleen** [comment]
Hi,

JupyterLab 1.0 is now available on SageMaker Notebooks!
