### ISSUE TITLE
How to predict without deploy using instance

### ISSUE THREAD

**Issue by jguo16** [awslabs/amazon-sagemaker-examples#798]
Hi,
I am using deepar model for a time series prediction, wondering after estimator.fit(input)
how can I directly predict without deploy, since I jus want to get the result locally. Thanks

**Comment by jzhufd** [comment]
batch transformer can be used for prediction. 
Please find the sample notebook:
https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker_batch_transform/introduction_to_batch_transform

**Comment by apacker** [comment]
@jguo16 you can get predictions locally by specifying `instance_type='local'` when calling `deploy()` on your estimator.

You can use the DeepAR example notebook for an example of how to build a DeepAR predictor class: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/deepar_electricity/DeepAR-Electricity.ipynb

And then create a local predictor:
```
predictor = estimator.deploy(
    initial_instance_count=1,
    instance_type='local',
    predictor_cls=DeepARPredictor)
```
