### ISSUE TITLE
How to end a failed batch transform job

### ISSUE THREAD

**Issue by lucaventurini** [awslabs/amazon-sagemaker-examples#815]
Hi,

I have a question on how, or when, does a Batch Transform end in case of a failure.
 I modified the scikit BYO example to load a custom model, and when this load fails, I return a 404, like here: https://github.com/awslabs/amazon-sagemaker-examples/blob/57e8717d1dd8e45d67f60f14831d95b01b438785/advanced_functionality/scikit_bring_your_own/container/decision_trees/predictor.py#L54

Now, I see in the logs that, since I returned 404, AWS keeps sending a ping request. I'd expect the Batch Transform job to eventually timeout, but I didn't see this behavior, and job continues forever (until I don't stop it) with this ping every second.

So, my questions are:
* how should I reply in case of errors? Is there any code that would stop the job?
* can I set a timeout in the job for only the loading phase (until ping replies 200)? And for the all job?

**Comment by andremoeller** [comment]
Hey @lucaventurini ,

Thanks for the report!

Currently, the job will stop after 30 minutes if the container responds with a 400 -- we're seeing whether we can make this behavior clearer and more transparent. You can provide a timeout in your own code by exiting with a non-zero exit code after a timer exceeds the timeout you'd like to set, but there's currently no facility through the API to specify a timeout.

Thanks again for the report -- please reach out if you have more questions or comments.

**Comment by sridharr24** [comment]
Is there a script to stop batch transform job that runs for ever? Is this still not updated, for a timeout to setup?
