### ISSUE TITLE
[Question] Can customized inference image downloading files from s3

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-sagemaker-examples#825]
Hi, we want to use our  customized inference image to do batch transform and may need to download s3 file, I'm wondering is it possible?

**Comment by apacker** [comment]
You may use the AWS SDK from within your customize inference image to download additional files from S3. Please be sure to review the documentation (https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-batch.html) as the batch transform platform will be performing the S3 operations for your input data set.

Please reopen this issue if you require any additional details/clarifications
