### ISSUE TITLE
An error occurred (ModelError) when calling the InvokeEndpoint operation occur

### ISSUE THREAD

**Issue by banan405** [awslabs/amazon-sagemaker-examples#833]
I follow this instruction. 
tensorflow_BYOM_iris.ipynb

I successfully create model, it works well, I deployed on Sagemaker, my endpoint state is 'InService'.

`
predictor=sagemaker.tensorflow.model.TensorFlowPredictor('end-point name', sagemaker_session)
predictor.predict([1,2,3,4])
`
this gives error
like this
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-tensorflow-2019-08-03-00-47-21-110 in account 516134860041 for more information.

Would you help me to solve this problem?

**Comment by jsanders67** [comment]
@banan405 Did you look into the logs referenced in the log message? Logs from the model you deploy on SageMaker are uploaded into your account and they should give some insight into what is going on. Once you are able to find them, perhaps paste some relevant snippets here and others may be better able to assist.

**Comment by banan405** [comment]
I change the model to DNN then it is working, I think liner is not working

2019년 12월 12일 (목) 오후 2:55, James (@sanjams) <notifications@github.com>님이 작성:
