### ISSUE TITLE
MXNet MNIST Notebook not working for inference

### ISSUE THREAD

**Issue by anirudhacharya** [awslabs/amazon-sagemaker-examples#837]
This notebook does not work properly - https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_mnist/mxnet_mnist.ipynb

Under the section **Making an inference request** when we run 
```python
response = predictor.predict(data)
```
the variable `data` is not defined.

**Comment by sandeep-krishnamurthy** [comment]
@zxy844288792 - Can you please take a look? Thank you.

**Comment by zxy844288792** [comment]
@anirudhacharya 
Hi there,
`
from IPython.display import HTML
HTML(open("input.html").read())
`
After you run this block, there should be a white board displayed and you need to draw a digit in that white board. After you draw something, the data will be defined and you can proceed.

Best
