### ISSUE TITLE
some questions about directory

### ISSUE THREAD

**Issue by ForeverPs** [awslabs/amazon-sagemaker-examples#841]
I'm new here , I just want to know where is directory of opt/ml/

**Comment by jesterhazy** [comment]
Hi @ForeverPs, thanks for using SageMaker!

SageMaker uses the `/opt/ml` directory path for lots of things -- storing configuration files, code, training input and output data etc.

For more info, check out [this doc](https://docs.aws.amazon.com/sagemaker/latest/dg/amazon-sagemaker-containers.html).

**Comment by ForeverPs** [comment]
many thanks. 
I do really want to know how to create an inference image. 
Now, I have a trained model which has been transformed into tar.gz, and then, I want to deploy this model with my own inference code. 
What should I do? Please give me some introduction or reference doc.
Best wishes.
an aws user


---Original---
