### ISSUE TITLE
error transforming data after training scikit following pipeline inference example

### ISSUE THREAD

**Issue by jorgeecr** [awslabs/amazon-sagemaker-examples#852]
I'm following the [example](https://aws.amazon.com/blogs/machine-learning/preprocess-input-data-before-making-predictions-using-amazon-sagemaker-inference-pipelines-and-scikit-learn/) for a scikit-learn pipeline with sagemaker, with some modifications (you can see my script [here](https://github.com/jorgeecr/aws/blob/master/scikitlearn_aws.py)). Everything up to the step 5 (including step 5) goes well, so the model trains well. After that I define a transformer as in the example but when I call transform, it takes forever and at the end I get the following error:
UnexpectedStatusException: Error for Transform job sagemaker-scikit-learn-2019-08-20-17-28-31-209: Failed. Reason: AlgorithmError: Model container failed to respond to ping. Please ensure /ping endpoint is implemented and responds with an HTTP 200 status code

The purpose of my script is to transform text data into a vector for later use in a tensorflow model (which I've deployed succesfully using sagemaker).

Do you have any idea on why this is happening?

**Comment by mh-mburkhardt** [comment]
Were you able to resolve this? I am experiencing the same issue.

**Comment by jorgeecr** [comment]
Sorry but no, I just closed the issue because I thought nobody would read
it and then I just deployed my model with a different platform. Good luck

**Comment by ThrinathMphasis** [comment]
hi ,
i have the same issue!! 

Client error: AlgorithmError: Model container failed to respond to ping. Please ensure /ping endpoint is implemented and responds with an HTTP 200 status code

**Comment by diptanshu-singh** [comment]
Same issue

**Comment by iairUbank** [comment]
Same issue here using the sagemaker_session.create_model_from_job() first to create the model and then i use the model_name given as an argument to the following function:

request = {
    "TransformJobName": batch_job_name,
    "ModelName": model_test,
    "TransformOutput": {
        "S3OutputPath": 's3://sagemaker-us-east-1-524172448451/clasificador-transacciones-chile/batch/coopeuch/results/',
    },
    "TransformInput": {
        "DataSource": {
            "S3DataSource": {
                "S3DataType": "S3Prefix",
                "S3Uri": batch_input_s3 
            }
        },
    },
    "TransformResources": { 
        "InstanceCount": 1,
        "InstanceType": 'ml.m5.2xlarge'
   }
}

**Comment by chubzor** [comment]
Same issue after trying to set up EstimatorTransformer using SKLearn estimator in a pipelines project.
Training step passes, CreateModelStep passes but TransformStep fails with:
AttributeError: 'NoneType' object has no attribute 'startswith'
[208] [ERROR] Error handling request /ping
It's confusing since the pipeline builds and it seems that. the. workflow is valid, only the transform job fails for this reason which doesn't really make any sense.

**Comment by AyonzOnTop** [comment]
Hello,
I have exactly the same issue.
Any solutions please?

**Comment by olofssy** [comment]
I'm experiencing the same issue with the transform-step @chubzor & @AyonzOnTop mentions, when using a custom-script SKLearn estimator and attempting to execute a pipeline of estimator-training-step > create-model-step > transform-step. Any inputs on how to resolve this greatly appreciated.

**Comment by cmarshall10450** [comment]
I'm having this same issue as well after following [this](https://docs.aws.amazon.com/sagemaker/latest/dg/define-pipeline.html). Its the last thing that I need to get working in my project. Are there any ideas on what may be causing this?

**Comment by AyonzOnTop** [comment]
I had to dig into the log files for the error
There was another error causing the "Model container failed to respond to ping.".
Check the all the relevant log files to find the cause error.
