### ISSUE TITLE
DeepAR producing negative values in the output for the counts data

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-sagemaker-examples#866]
While trying to build DeepAR based sales forecasting model, the Sagemaker batch transform output consists of negative values. Since number of sales is the counts data, ideally the minimum value should be 0 as training output is always >=0. Why does this happen?

**Comment by jaheba** [comment]
To close this: The output domain is determined by `likelihood` parameter. In this case, `negative-binomial` appears to be the right one.

See https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_hyperparameters.html
