### ISSUE TITLE
Bash commands not working inside R kernel

### ISSUE THREAD

**Issue by sp-anna-jones** [awslabs/amazon-sagemaker-examples#912]
Hi

I'm having issues running bash commands inside jupyter notebooks running on the R kernel. They work fine in the conda-python kernels, but in R they aren't recognised. I get an "unexpected symbol" error message.

![Screenshot 2019-11-04 at 10 16 59](https://user-images.githubusercontent.com/15875811/68110017-4b441200-feec-11e9-82d1-438f98e4d58e.png)

Could you help me? I need to be able to run terminal commands to get the rJava package installed correctly.

Thanks,

**Comment by sp-anna-jones** [comment]
![Screenshot 2019-11-04 at 10 18 11](https://user-images.githubusercontent.com/15875811/68110058-6ca4fe00-feec-11e9-9ce4-bcfd6db0fe31.png)

Another example of something simpler to show that it's not the command itself

**Comment by neelamgehlot** [comment]
Hi @sp-anna-jones 

You can run bash command in R kernel using  `system()`  function.  
For example `system("ls", intern=TRUE)` 
![RunningBashCmdInR](https://user-images.githubusercontent.com/15882916/70839779-49ab1b00-1dc3-11ea-9bcf-015fed314800.png)

For more information checkout https://github.com/IARCbioinfo/R-tricks#running-bash-commands-from-r .

Thanks,
Neelam
