### ISSUE TITLE
Confused by logic in example Step functions `ChoiceRule`

### ISSUE THREAD

**Issue by rragundez** [awslabs/amazon-sagemaker-examples#922]
In the step function example:

https://github.com/awslabs/amazon-sagemaker-examples/blob/438429411541375b267110d833ab541cab768730/step-functions-data-science-sdk/hello_world_workflow/hello_world_workflow.ipynb#L434

first the `variable` is defined in a `ChouiceRule` which is already strange because I would expect the `variable` to depend only the previous step. Then both steps are chained `workflow_definition=Chain([start_pass_state, choice_state])` which is also weird. So I can chain with any step not necessarily the `start_pass_state` as the `ChoiceRule` is defined specifically for `start_pass_state` which is confusing as I would expect the rule to work only on the output of the previous step without having to hardcode anything to which step we are referring to in `ChoiceRule`.

**Comment by vaib-amz** [comment]
Hi,

You are right in that the choice state only accepts variables from the previous step. The variable you choose from your previous state's output must be specified in the `variable` field for the `ChoiceRule`.

In the case of the Step Functions Data Science Python SDK, we provide [placeholders](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/placeholders.html) to aid users in passing dynamic values in a workflow, such as the output from a previous step. Here:

`rule=ChoiceRule.BooleanEquals(variable=start_pass_state.output()["IsHelloWorldExample"], value=True)`

the `start_pass_state.output()` [provides this placeholder](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/states.html#stepfunctions.steps.states.State.output) of the expected output from the `start_pass_state`. When we attempt to create the Workflow in the notebook like:

```
workflow_definition=Chain([start_pass_state, choice_state]

workflow = Workflow(
    name="MyWorkflow_v1234",
    definition=workflow_definition,
    role=workflow_execution_role
)
```

the Workflow creation step will validate that the placeholder referenced in `choice_state` is from the output of the `start_pass_state`. If that isn't the case, the workflow creation will fail.

In the case that you want the rule to work only on the output of the previous step without having to hardcode anything to which step we are referring to, you can use the `$.<variableName>` format as shown in an example in the Step Functions docs: https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html 

For this notebook, the rule would then look like:

`rule=ChoiceRule.BooleanEquals(variable=$["IsHelloWorldExample"], value=True)` or
`rule=ChoiceRule.BooleanEquals(variable=$.IsHelloWorldExample, value=True)`

Thanks,
Vaib

**Comment by rragundez** [comment]
thanks for the explanation.
