### ISSUE TITLE
Training semantic segmentation using AugmentedManifest format

### ISSUE THREAD

**Issue by Ritika-a** [awslabs/amazon-sagemaker-examples#960]
I am trying to train my data using the inbuilt semantic segmentation algorithm.
A line of my 'augmented-manifest-train.manifest' file looks like  
{"source-ref":"s3://XXX/train/0001 to 0017.jpg", "annotation-ref":"s3://XXXX/train_annotation/0001 to 0017.png"} 

s3_train_data_path refers to the path of my manifest file.
train_data = sagemaker.session.s3_input(
                                        distribution='FullyReplicated',
                                        content_type='image/jpeg',
                                        s3_data_type='AugmentedManifestFile',
                                        attribute_names=['source-ref', 'annotation-ref'],
                                       s3_data = s3_train_data_path) 
validation_data = sagemaker.session.s3_input(,
                                        distribution='FullyReplicated',
                                        content_type='image/jpeg',
                                        s3_data_type='AugmentedManifestFile',
                                        attribute_names=['source-ref', 'annotation-ref'],
                                            s3_data = s3_validation_data_path) 
data_channels = {'train': train_data, 
                 'validation': validation_data,}
ss_model.fit(inputs=data_channels, logs=True)

When I fit the model , I get the following error , 
ClientError: No data found in the training channel. Please ensure that your training dataset location is correct.
However, I have copied the path directly from the s3 bucket. The path definitely exists. Are there any solutions to this?

**Comment by JSpenced** [comment]
What was the issue and how did you fix it? Did you need to split up the source and annotation file or was it fine to keep it seperate?

**Comment by ohbuchim** [comment]
If the number of training images or validation images is less than mini_batch_size (default is 16), you will get that error.
