### ISSUE TITLE
Step Function Data Science SDK example not deploying model endpoint properly

### ISSUE THREAD

**Issue by antje** [awslabs/amazon-sagemaker-examples#965]
Hi @shunjd,

This is the sample noteboook I'm executing: 

https://github.com/awslabs/amazon-sagemaker-examples/blob/346811d27ba9e1cd6a3db94a90f584b951f7aa33/step-functions-data-science-sdk/training_pipeline_pytorch_mnist/training_pipeline_pytorch_mnist.ipynb

The Training Pipeline is not deploying the model endpoint. CloudWatch logs show the following errors: 

```FileNotFoundError: [Errno 2] No such file or directory: 'nginx': 'nginx'```

and 

```
Traceback (most recent call last):
  File "/opt/conda/bin/serve", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/cli/serve.py", line 19, in main
    server.start(env.ServingEnv().framework_module)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_containers/_server.py", line 82, in start
    nginx = subprocess.Popen(["nginx", "-c", nginx_config_file])
  File "/opt/conda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

Any suggestions? Thanks!

**Comment by antje** [comment]
![image](https://user-images.githubusercontent.com/23338582/71531787-911bc600-28f0-11ea-9282-9e6b4e6a1b38.png)

The Step Function workflow shows actually as successful, but the endpoint creation failed. 

![image](https://user-images.githubusercontent.com/23338582/71531812-b1e41b80-28f0-11ea-83bf-bfe7d6e69b6f.png)

**Comment by cfregly** [comment]
@shunjd i'm also having this issue.  any update?

**Comment by shunjd** [comment]
Hi @cfregly @antje, thanks for reporting the issue, we are investigating it with the SageMaker team.

**Comment by Bjarten** [comment]
Hi @shunjd, I'm also having the same issue, any updates?

**Comment by shunjd** [comment]
Hi @Bjarten, we are still waiting for the SageMaker team to respond, I will update the ticket once they have finished their investigation.

**Comment by shunjd** [comment]
While we are fixing the issue, we recommend our customers to try PyTorch 1.1 instead, it will result in a successful endpoint creation.

```python
estimator = PyTorch(entry_point='mnist.py',
                    role=sagemaker_execution_role,
                    framework_version='1.1.0', # <-- Downgrade to 1.1.0
                    train_instance_count=2,
                    train_instance_type='ml.c4.xlarge',
                    hyperparameters={
                        'epochs': 6,
                        'backend': 'gloo'
                    })
```

We will update the issue once the fix is ready.

**Comment by shunjd** [comment]
This issue has been fixed, please reinstall the latest version of Sagemaker SDK by running `pip install -U sagemaker`.
