### ISSUE TITLE
Sagemaker Neo - Detectron2 - unable to compile

### ISSUE THREAD

**Issue by wiamadaya** [awslabs/amazon-sagemaker-examples#996]
is it possible to compile Mask R-CNN model trained on Detectron2 using PyTorch? i received the following error

![image](https://user-images.githubusercontent.com/26107990/72867126-73375a80-3d10-11ea-82a3-5b0556193445.png)

ClientError: InputConfiguration: Invalid PyTorch model or input-shape mismatch. Make sure that inputs are lexically ordered and of the correct dimensionality.

**Comment by alexwong** [comment]
Bubble internal answer here.
Neo compiler does not support object detection models (such as Mask R-CNN) for PyTorch currently. It is in the roadmap but is far away at the moment.
